var createTaisei=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg;h.totalDependencies=0;h.monitorRunDependencies=function(a){h.totalDependencies=Math.max(h.totalDependencies,a);h.setStatus(a?"Preparing… ("+(h.totalDependencies-a)+"/"+h.totalDependencies+")":"All downloads complete.")};h.initFilesystem=function(){k("/persistent");l.bj(p,{},"/persistent")};var ba=h.preinitializedWebGLContext;ba.getSupportedExtensions().forEach(function(a){ba.getExtension(a)});
function ca(a,b){l.pk(a,function(c){h.ccall("vfs_sync_callback",null,["boolean","string","number"],[a,c,b],{async:!0})})}"undefined"===typeof da&&(da=h.dynCall=function(a,b,c){return ea.get(b).apply(this,c)});var fa="./this.program",ha="",ia;try{ha=(new URL(".",_scriptName)).href}catch{}ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var ja=console.log.bind(console),ka=console.error.bind(console),la,ma=!1,na,oa,pa,u,w,qa,sa,ta,ua,y,z,va=!1;function wa(){var a=xa.buffer;u=new Int8Array(a);qa=new Int16Array(a);w=new Uint8Array(a);sa=new Uint16Array(a);ta=new Int32Array(a);ua=new Uint32Array(a);y=new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a);z=new DataView(a);ya()}
function A(a){h.onAbort?.(a);a="Aborted("+a+")";ka(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");pa?.(a);throw a;}var za;async function Aa(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==za&&la)a=new Uint8Array(la);else throw"both async and sync fetching of the wasm failed";return a}async function Ba(a,b){try{var c=await Aa(a);return await WebAssembly.instantiate(c,b)}catch(d){ka(`failed to asynchronously prepare wasm: ${d}`),A(d)}}
async function Ca(a){var b=za;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ka(`wasm streaming compile failed: ${d}`),ka("falling back to ArrayBuffer instantiation")}return Ba(b,a)}class Da{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ea=a=>{for(;0<a.length;)a.shift()(h)},Fa=[],Ga=[],Ha=()=>{var a=h.preRun.shift();Ga.push(a)},Ia=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},B={},da=(a,b,c=[])=>{a=a.replace(/p/g,"i");return(0,B[a])(b,...c)},Ja=!0;
function Ka(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":u[a]=b;break;case "i8":u[a]=b;break;case "i16":z.setInt16(2*(a>>1),b,!0);break;case "i32":z.setInt32(4*(a>>2),b,!0);break;case "i64":z.setBigInt64(8*(a>>3),BigInt(b),!0);break;case "float":z.setFloat32(4*(a>>2),b,!0);break;case "double":z.setFloat64(8*(a>>3),b,!0);break;case "*":z.setUint32(4*(a>>2),b,!0);break;default:A(`invalid type for setValue: ${c}`)}}
var Ma=()=>{var a=z.getInt32(4*(+La>>2),!0);La+=4;return a},Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Ra=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Sa=(a,b)=>Pa(a+"/"+b),Ta=()=>a=>crypto.getRandomValues(a),Ua=a=>{(Ua=Ta())(a)},Va=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:l.tk();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Oa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Wa=(a,b)=>{function c(g){for(var m=0;m<g.length&&""===g[m];m++);for(var n=
g.length-1;0<=n&&""===g[n];n--);return m>n?[]:g.slice(m,n-m+1)}a=Va(a).slice(1);b=Va(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Xa=globalThis.TextDecoder&&new TextDecoder,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;
if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ya=[],Za=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);
if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},$a=a=>{var b=Array(Za(a)+1);a=D(a,b,0,b.length);b.length=a;return b},ab=[];function bb(a,b){ab[a]={input:[],output:[],Hj:b};cb(a,db)}
var db={open(a){var b=ab[a.node.nk];if(!b)throw new l.Wi(43);a.cj=b;a.seekable=!1},close(a){a.cj.Hj.xk(a.cj)},xk(a){a.cj.Hj.xk(a.cj)},read(a,b,c,d){if(!a.cj||!a.cj.Hj.pl)throw new l.Wi(60);for(var e=0,f=0;f<d;f++){try{var g=a.cj.Hj.pl(a.cj)}catch(m){throw new l.Wi(29);}if(void 0===g&&0===e)throw new l.Wi(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Fj=Date.now());return e},write(a,b,c,d){if(!a.cj||!a.cj.Hj.Zk)throw new l.Wi(60);try{for(var e=0;e<d;e++)a.cj.Hj.Zk(a.cj,b[c+e])}catch(f){throw new l.Wi(29);
}d&&(a.node.gj=a.node.lj=Date.now());return e}},eb={pl(){a:{if(!Ya.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ya=$a(a)}a=Ya.shift()}return a},Zk(a,b){null===b||10===b?(ja(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},xk(a){0<a.output?.length&&(ja(C(a.output)),a.output=[])},em(){return{Fm:25856,Hm:5,Em:191,Gm:35387,Dm:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},fm(){return 0},gm(){return[24,
80]}},fb={Zk(a,b){null===b||10===b?(ka(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},xk(a){0<a.output?.length&&(ka(C(a.output)),a.output=[])}},hb=a=>{a=65536*Math.ceil(a/65536);var b=gb(65536,a);b&&w.fill(0,b,b+a);return b},F={Bj:null,bj(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=24576===(c&61440))||(e=4096===(c&61440));if(e)throw new l.Wi(63);F.Bj||(F.Bj={dir:{node:{qj:F.Xi.qj,uj:F.Xi.uj,Tj:F.Xi.Tj,rj:F.Xi.rj,Xj:F.Xi.Xj,Dj:F.Xi.Dj,Cj:F.Xi.Cj,Nj:F.Xi.Nj,wj:F.Xi.wj},
stream:{ij:F.Yi.ij}},file:{node:{qj:F.Xi.qj,uj:F.Xi.uj},stream:{ij:F.Yi.ij,read:F.Yi.read,write:F.Yi.write,Vj:F.Yi.Vj,bk:F.Yi.bk}},link:{node:{qj:F.Xi.qj,uj:F.Xi.uj,Oj:F.Xi.Oj},stream:{}},kl:{node:{qj:F.Xi.qj,uj:F.Xi.uj},stream:l.Il}});c=l.createNode(a,b,c,d);H(c.mode)?(c.Xi=F.Bj.dir.node,c.Yi=F.Bj.dir.stream,c.$i={}):l.isFile(c.mode)?(c.Xi=F.Bj.file.node,c.Yi=F.Bj.file.stream,c.jj=0,c.$i=F.Rl??(F.Rl=new Uint8Array(0))):40960===(c.mode&61440)?(c.Xi=F.Bj.link.node,c.Yi=F.Bj.link.stream):8192===(c.mode&
61440)&&(c.Xi=F.Bj.kl.node,c.Yi=F.Bj.kl.stream);c.Fj=c.gj=c.lj=Date.now();a&&(a.$i[b]=c,a.Fj=a.gj=a.lj=c.Fj);return c},Xi:{qj(a){var b={};b.Ql=8192===(a.mode&61440)?a.id:1;b.dm=a.id;b.mode=a.mode;b.lm=1;b.uid=0;b.am=0;b.nk=a.nk;H(a.mode)?b.size=4096:l.isFile(a.mode)?b.size=a.jj:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Fj=new Date(a.Fj);b.gj=new Date(a.gj);b.lj=new Date(a.lj);b.Gl=4096;b.il=Math.ceil(b.size/b.Gl);return b},uj(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&
(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.jj!=b&&(c=a.$i,a.$i=new Uint8Array(b),a.$i.set(c.subarray(0,Math.min(b,a.jj))),a.jj=b))},Tj(){F.Hk||(F.Hk=new l.Wi(44),F.Hk.stack="<generic error, no stack>");throw F.Hk;},rj(a,b,c,d){return F.createNode(a,b,c,d)},Xj(a,b,c){try{var d=ib(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.$i)throw new l.Wi(55);jb(d)}delete a.parent.$i[a.name];b.$i[c]=a;a.name=c;b.lj=b.gj=a.parent.lj=a.parent.gj=Date.now()},Dj(a,b){delete a.$i[b];a.lj=a.gj=Date.now()},Cj(a,b){var c=
ib(a,b),d;for(d in c.$i)throw new l.Wi(55);delete a.$i[b];a.lj=a.gj=Date.now()},Nj(a){return[".","..",...Object.keys(a.$i)]},wj(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},Oj(a){if(40960!==(a.mode&61440))throw new l.Wi(28);return a.link}},Yi:{read(a,b,c,d,e){if(e>=a.node.jj)return 0;d=Math.min(a.node.jj-e,d);b.set(a.node.$i.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.gj=a.lj=Date.now();if(f)a.$i=b.subarray(c,c+d),a.jj=d;else if(0===
a.jj&&0===e)a.$i=b.slice(c,c+d),a.jj=d;else{f=e+d;var g=a.$i.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.$i.subarray(0,a.jj),a.$i=new Uint8Array(f),a.$i.set(g));a.$i.set(b.subarray(c,c+d),e);a.jj=Math.max(a.jj,e+d)}return d},ij(a,b,c){1===c?b+=a.position:2===c&&l.isFile(a.node.mode)&&(b+=a.node.jj);if(0>b)throw new l.Wi(28);return b},Vj(a,b,c,d,e){if(!l.isFile(a.node.mode))throw new l.Wi(43);a=a.node.$i;if(e&2||a.buffer!==u.buffer){d=!0;e=hb(b);if(!e)throw new l.Wi(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{vl:e,Ij:d}},bk(a,b,c,d){F.Yi.write(a,b,0,d,c,!1);return 0}}},kb=a=>{"string"==typeof a&&(a=$a(a));a.subarray||(a=new Uint8Array(a));return a},lb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},p={uk:{},indexedDB:()=>indexedDB,zl:21,Qj:"FILE_DATA",ck:a=>{function b(){"again"===a.Sj?c():a.Sj=0}function c(){a.Sj="idb";p.pk(a,!1,b)}a.Sj?"idb"===a.Sj&&(a.Sj="again"):
a.Sj=setTimeout(c,0)},bj:a=>{var b=F.bj(a);if(a?.tl?.ym){a.Sj=0;var c=b.Xi;b.Xi={...b.Xi};b.Xi.rj=(d,e,f,g)=>{var m=c.rj(d,e,f,g);m.Xi=b.Xi;m.bm=b.bj;m.Vk=m.Yi;m.Yi={...m.Yi};m.Yi.write=(n,q,r,t,v,E)=>{n.node.rl=!0;return m.Vk.write(n,q,r,t,v,E)};m.Yi.close=n=>{var q=n.node;q.rl&&(p.ck(q.bm),q.rl=!1);if(q.Vk.close)return q.Vk.close(n)};p.ck(b.bj);return m};b.Xi.Cj=(...d)=>(p.ck(b.bj),c.Cj(...d));b.Xi.wj=(...d)=>(p.ck(b.bj),c.wj(...d));b.Xi.Dj=(...d)=>(p.ck(b.bj),c.Dj(...d));b.Xi.Xj=(...d)=>(p.ck(b.bj),
c.Xj(...d))}return b},pk:(a,b,c)=>{p.Yl(a,(d,e)=>{if(d)return c(d);p.Zl(a,(f,g)=>{if(f)return c(f);p.pm(b?g:e,b?e:g,c)})})},om:()=>{for(var a of Object.values(p.uk))a.close();p.uk={}},Wl:(a,b)=>{var c=p.uk[a];if(c)return b(null,c);try{var d=p.indexedDB().open(a,p.zl)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(p.Qj)?g=e.objectStore(p.Qj):g=f.createObjectStore(p.Qj);g.indexNames.contains("timestamp")||
g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;p.uk[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},Yl:(a,b)=>{function c(m){return"."!==m&&".."!==m}function d(m){return n=>Pa(m+"/"+n)}var e={};for(a=l.Nj(a.lk).filter(c).map(d(a.lk));a.length;){var f=a.pop();try{var g=l.stat(f,!0)}catch(m){return b(m)}H(g.mode)&&a.push(...l.Nj(f).filter(c).map(d(f)));e[f]={timestamp:g.gj}}return b(null,{type:"local",entries:e})},Zl:(a,b)=>{var c={};p.Wl(a.lk,(d,
e)=>{if(d)return b(d);try{var f=e.transaction([p.Qj],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(p.Qj).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},jm:(a,b)=>{try{var c=I(a).node;var d=l.stat(a,!0)}catch(e){return b(e)}return H(d.mode)?b(null,{timestamp:d.gj,mode:d.mode}):40960===(d.mode&61440)?b(null,{timestamp:d.gj,mode:d.mode,
link:c.link}):l.isFile(d.mode)?(c.$i=c.$i.subarray(0,c.jj),b(null,{timestamp:d.gj,mode:d.mode,contents:c.$i})):b(Error("node type not supported"))},um:(a,b,c)=>{try{if(H(b.mode)){var d=b.mode,e=a.split("/"),f="",g;for(g of e)if(g){if(f||"/"===a.charAt(0))f+="/";f+=g;try{k(f,d)}catch(t){if(20!=t.ej)throw t;}}}else if(40960===(b.mode&61440))l.wj(b.link,a);else if(l.isFile(b.mode)){f=b.contents;d={Hl:!0};d.flags=d.flags||577;var m=l.open(a,d.flags,d.mode);f=kb(f);l.write(m,f,0,f.byteLength,void 0,d.Hl);
l.close(m)}else return c(Error("node type not supported"));mb(a,b.mode);var n=b.timestamp,q=b.timestamp,r=I(a,{pj:!0}).node;nb(r.Xi.uj,63)(r,{Fj:n,gj:q})}catch(t){return c(t)}c(null)},rm:(a,b)=>{try{var c=l.stat(a,!0);H(c.mode)?l.Cj(a):l.Dj(a)}catch(d){return b(d)}b(null)},km:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},vm:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},
sm:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},pm:(a,b,c)=>{function d(v){if(v&&!q)return q=!0,c(v)}var e=0,f=[],g;for([g,n]of Object.entries(a.entries)){var m=b.entries[g];m&&n.timestamp.getTime()==m.timestamp.getTime()||(f.push(g),e++)}var n=[];for(g of Object.keys(b.entries))a.entries[g]||(n.push(g),e++);if(!e)return c(null);var q=!1;a=("remote"===a.type?a.db:b.db).transaction([p.Qj],"readwrite");var r=a.objectStore(p.Qj);a.onerror=a.onabort=
v=>{d(v.target.error);v.preventDefault()};a.oncomplete=()=>{q||c(null)};for(const v of f.sort())"local"===b.type?p.km(r,v,(E,G)=>{if(E)return d(E);p.um(v,G,d)}):p.jm(v,(E,G)=>{if(E)return d(E);p.vm(r,v,G,d)});for(var t of n.sort().reverse())"local"===b.type?p.rm(t,d):p.sm(r,t,d)}},ob=async a=>{a=await ia(a);return new Uint8Array(a)},pb=0,qb=null,rb=()=>{pb--;h.monitorRunDependencies?.(pb);if(0==pb&&qb){var a=qb;qb=null;a()}},sb=()=>{pb++;h.monitorRunDependencies?.(pb)},tb=[],wb=async(a,b)=>{"undefined"!=
typeof ub&&vb();for(var c of tb)if(c.canHandle(b))return c.handle(a,b);return a},yb=async(a,b,c,d,e,f,g,m)=>{var n=b?Va(Pa(a+"/"+b)):a,q=`cp ${n}`;sb(q);try{var r=c;"string"==typeof c&&(r=await ob(c));r=await wb(r,n);m?.();f||xb(a,b,r,d,e,g)}finally{rb(q)}};function k(a,b=511){return l.rj(a,b&1023|16384,0)}function cb(a,b){l.ml[a]={Yi:b}}function H(a){return 16384===(a&61440)}
function ib(a,b){var c=H(a.mode)?(c=zb(a,"x"))?c:a.Xi.Tj?0:2:54;if(c)throw new l.Wi(c);for(c=l.Gj[Ab(a.id,b)];c;c=c.Wj){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return l.Tj(a,b)}function jb(a){var b=Ab(a.parent.id,a.name);if(l.Gj[b]===a)l.Gj[b]=a.Wj;else for(b=l.Gj[b];b;){if(b.Wj===a){b.Wj=a.Wj;break}b=b.Wj}}
function I(a,b={}){if(!a)throw new l.Wi(44);b.wk??(b.wk=!0);"/"===a.charAt(0)||(a=l.tk()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=l.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Qa(e),l.Rk(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Pa(e+"/"+a[f]);try{d=ib(d,a[f])}catch(m){if(44===m?.ej&&g&&b.mm)return{path:e};throw m;}!d.sj||g&&!b.wk||(d=d.sj.root);if(40960===(d.mode&61440)&&(!g||
b.pj)){if(!d.Xi.Oj)throw new l.Wi(52);d=d.Xi.Oj(d);"/"===d.charAt(0)||(d=Qa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new l.Wi(32);}function mb(a,b,c){a="string"==typeof a?I(a,{pj:!c}).node:a;Bb(null,a,b,c)}function xb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Cb(a),g=b?Pa(a+"/"+b):a);a=lb(d,e);g=l.create(g,a);c&&(c=kb(c),mb(g,a|146),b=l.open(g,577),l.write(b,c,0,c.length,0,f),l.close(b),mb(g,a))}
function Cb(a){for(var b;;){if(l.Rk(a))return a=a.bj.lk,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%l.Gj.length}function Db(a){var b=Ab(a.parent.id,a.name);a.Wj=l.Gj[b];l.Gj[b]=a}function zb(a,b){return l.ql?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}
function Eb(a,b){if(!H(a.mode))return 54;try{return ib(a,b),20}catch(c){}return zb(a,"wx")}function Fb(a,b,c){try{var d=ib(a,b)}catch(e){return e.ej}if(a=zb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(l.Rk(d)||Cb(d)===l.tk())return 10}else if(H(d.mode))return 31;return 0}function nb(a,b){if(!a)throw new l.Wi(b);return a}function L(a){a=l.$l(a);if(!a)throw new l.Wi(8);return a}
function Gb(a,b=-1){a=Object.assign(new l.Bl,a);if(-1==b)a:{for(b=0;b<=l.Cl;b++)if(!l.streams[b])break a;throw new l.Wi(33);}a.fd=b;return l.streams[b]=a}function Hb(a,b=-1){a=Gb(a,b);a.Yi?.Om?.(a);return a}function Ib(a,b,c){var d=a?.Yi.uj;a=d?a:b;d??=b.Xi.uj;nb(d,63);d(a,c)}function Jb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.mk)}return b}
function Kb(a){var b={Cm:4096,Xm:4096,il:1E6,Bm:5E5,Am:5E5,files:l.Wk,Vm:l.Wk-1,Ym:42,flags:2,gn:255};a.Xi.wl&&Object.assign(b,a.Xi.wl(a.bj.tl.root));return b}function Lb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return l.rj(a,b|8192,c)}function Bb(a,b,c,d){Ib(a,b,{mode:c&4095|b.mode&-4096,lj:Date.now(),nl:d})}function Mb(a,b,c){if(H(b.mode))throw new l.Wi(31);if(!l.isFile(b.mode))throw new l.Wi(28);var d=zb(b,"w");if(d)throw new l.Wi(d);Ib(a,b,{size:c,timestamp:Date.now()})}
function Nb(a,b){a="string"==typeof a?a:Cb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pa(a+"/"+c);try{k(d)}catch(e){if(20!=e.ej)throw e;}a=d}}return d}function Ob(a,b,c,d){a="string"==typeof a?a:Cb(a);b=Pa(a+"/"+b);return l.create(b,lb(c,d))}
function Pb(a){if(!(a.hm||a.im||a.link||a.$i))if(globalThis.XMLHttpRequest)A("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.$i=(void 0)(a.url)}catch(b){throw new l.Wi(29);}}
function Qb(a,b,c,d,e){function f(r,t,v,E,G){r=r.node.$i;if(G>=r.length)return 0;E=Math.min(r.length-G,E);if(r.slice)for(var J=0;J<E;J++)t[v+J]=r[G+J];else for(J=0;J<E;J++)t[v+J]=r.get(G+J);return E}class g{Ej=!1;aj=[];hj=void 0;dk=0;ak=0;get(r){if(!(r>this.length-1||0>r)){var t=r%this.gk;return this.hj(r/this.gk|0)[t]}}Jl(r){this.hj=r}fk(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);200<=r.status&&300>r.status||304===r.status||A("Couldn't load "+c+". Status: "+r.status);var t=Number(r.getResponseHeader("Content-length")),
v,E=(v=r.getResponseHeader("Accept-Ranges"))&&"bytes"===v;r=(v=r.getResponseHeader("Content-Encoding"))&&"gzip"===v;var G=1048576;E||(G=t);var J=this;J.Jl(R=>{var Z=R*G,aa=(R+1)*G-1;aa=Math.min(aa,t-1);if("undefined"==typeof J.aj[R]){var ra=J.aj;Z>aa&&A("invalid range ("+Z+", "+aa+") or no bytes requested!");aa>t-1&&A("only "+t+" bytes available! programmer error!");var x=new XMLHttpRequest;x.open("GET",c,!1);t!==G&&x.setRequestHeader("Range","bytes="+Z+"-"+aa);x.responseType="arraybuffer";x.overrideMimeType&&
x.overrideMimeType("text/plain; charset=x-user-defined");x.send(null);200<=x.status&&300>x.status||304===x.status||A("Couldn't load "+c+". Status: "+x.status);Z=void 0!==x.response?new Uint8Array(x.response||[]):$a(x.responseText||"");ra[R]=Z}"undefined"==typeof J.aj[R]&&A("doXHR failed!");return J.aj[R]});if(r||!t)G=t=1,G=t=this.hj(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.dk=t;this.ak=G;this.Ej=!0}get length(){this.Ej||this.fk();return this.dk}get gk(){this.Ej||
this.fk();return this.ak}}if(globalThis.XMLHttpRequest){A("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var m=new g;var n=void 0}else n=c,m=void 0;var q=Ob(a,b,d,e);m?q.$i=m:n&&(q.$i=null,q.url=n);Object.defineProperties(q,{jj:{get:function(){return this.$i.length}}});a={};for(const [r,t]of Object.entries(q.Yi))a[r]=(...v)=>{Pb(q);return t(...v)};a.read=(r,t,v,E,G)=>{Pb(q);return f(r,t,v,E,G)};a.Vj=(r,t,v)=>{Pb(q);var E=hb(t);
if(!E)throw new l.Wi(48);f(r,u,E,t,v);return{vl:E,Ij:!0}};q.Yi=a;return q}
var l={root:null,mk:[],ml:{},streams:[],Wk:1,Gj:null,ll:"/",Pk:!1,ql:!0,Ul:null,Ck:0,Wi:class{name="ErrnoError";constructor(a){this.ej=a}},Bl:class{aj={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.aj.flags}set flags(a){this.aj.flags=a}get position(){return this.aj.position}set position(a){this.aj.position=a}},Al:class{Xi={};Yi={};sj=null;constructor(a,b,c,d){a||=this;this.parent=a;this.bj=a.bj;this.id=l.Wk++;this.name=b;this.mode=c;this.nk=d;this.Fj=
this.gj=this.lj=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get im(){return H(this.mode)}get hm(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new l.Al(a,b,c,d);Db(a);return a},Rk(a){return a===a.parent},isFile(a){return 32768===(a&61440)},an(a){return 49152===(a&49152)},Cl:4096,$l:a=>l.streams[a],Il:{open(a){a.Yi=l.Xl(a.node.nk).Yi;a.Yi.open?.(a)},
ij(){throw new l.Wi(70);}},Tk:a=>a>>8,dn:a=>a&255,Uj:(a,b)=>a<<8|b,Xl:a=>l.ml[a],pk(a,b){function c(m){l.Ck--;return b(m)}function d(m){if(m){if(!d.Sl)return d.Sl=!0,c(m)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);l.Ck++;1<l.Ck&&ka(`warning: ${l.Ck} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Jb(l.root.bj),f=0,g;for(g of e)g.type.pk?g.type.pk(g,a,d):d(null)},bj(a,b,c){var d="/"===c;if(d&&l.root)throw new l.Wi(10);if(!d&&c){var e=I(c,{wk:!1});c=e.path;
e=e.node;if(e.sj)throw new l.Wi(10);if(!H(e.mode))throw new l.Wi(54);}b={type:a,tl:b,lk:c,mk:[]};a=a.bj(b);a.bj=b;b.root=a;d?l.root=a:e&&(e.sj=b,e.bj&&e.bj.mk.push(b));return a},sn(a){a=I(a,{wk:!1});if(!a.node.sj)throw new l.Wi(28);a=a.node;var b=a.sj,c=Jb(b);for([,e]of Object.entries(l.Gj))for(;e;){var d=e.Wj;c.includes(e.bj)&&jb(e);var e=d}a.sj=null;a.bj.mk.splice(a.bj.mk.indexOf(b),1)},Tj(a,b){return a.Xi.Tj(a,b)},rj(a,b,c){var d=I(a,{parent:!0}).node;a=Ra(a);if(!a)throw new l.Wi(28);if("."===
a||".."===a)throw new l.Wi(20);var e=Eb(d,a);if(e)throw new l.Wi(e);if(!d.Xi.rj)throw new l.Wi(63);return d.Xi.rj(d,a,b,c)},wl(a){return Kb(I(a,{pj:!0}).node)},on(a){return Kb(a.node)},create(a,b=438){return l.rj(a,b&4095|32768,0)},wj(a,b){if(!Va(a))throw new l.Wi(44);var c=I(b,{parent:!0}).node;if(!c)throw new l.Wi(44);b=Ra(b);var d=Eb(c,b);if(d)throw new l.Wi(d);if(!c.Xi.wj)throw new l.Wi(63);return c.Xi.wj(c,b,a)},Xj(a,b){var c=Qa(a),d=Qa(b),e=Ra(a),f=Ra(b);var g=I(a,{parent:!0});var m=g.node;
g=I(b,{parent:!0});g=g.node;if(!m||!g)throw new l.Wi(44);if(m.bj!==g.bj)throw new l.Wi(75);var n=ib(m,e);a=Wa(a,d);if("."!==a.charAt(0))throw new l.Wi(28);a=Wa(b,c);if("."!==a.charAt(0))throw new l.Wi(55);try{var q=ib(g,f)}catch(r){}if(n!==q){b=H(n.mode);if(e=Fb(m,e,b))throw new l.Wi(e);if(e=q?Fb(g,f,b):Eb(g,f))throw new l.Wi(e);if(!m.Xi.Xj)throw new l.Wi(63);if(n.sj||q&&q.sj)throw new l.Wi(10);if(g!==m&&(e=zb(m,"w")))throw new l.Wi(e);jb(n);try{m.Xi.Xj(n,g,f),n.parent=g}catch(r){throw r;}finally{Db(n)}}},
Cj(a){var b=I(a,{parent:!0}).node;a=Ra(a);var c=ib(b,a),d=Fb(b,a,!0);if(d)throw new l.Wi(d);if(!b.Xi.Cj)throw new l.Wi(63);if(c.sj)throw new l.Wi(10);b.Xi.Cj(b,a);jb(c)},Nj(a){a=I(a,{pj:!0}).node;return nb(a.Xi.Nj,54)(a)},Dj(a){var b=I(a,{parent:!0}).node;if(!b)throw new l.Wi(44);a=Ra(a);var c=ib(b,a),d=Fb(b,a,!1);if(d)throw new l.Wi(d);if(!b.Xi.Dj)throw new l.Wi(63);if(c.sj)throw new l.Wi(10);b.Xi.Dj(b,a);jb(c)},Oj(a){a=I(a).node;if(!a)throw new l.Wi(44);if(!a.Xi.Oj)throw new l.Wi(28);return a.Xi.Oj(a)},
stat(a,b){a=I(a,{pj:!b}).node;return nb(a.Xi.qj,63)(a)},bn(a,b){mb(a,b,!0)},Tm(a,b){a=L(a);Bb(a,a.node,b,!1)},cn(a){a="string"==typeof a?I(a,{pj:!1}).node:a;Ib(null,a,{timestamp:Date.now(),nl:!0})},Um(a){a=L(a);Ib(a,a.node,{timestamp:Date.now(),nl:!1})},truncate(a,b){if(0>b)throw new l.Wi(28);a="string"==typeof a?I(a,{pj:!0}).node:a;Mb(null,a,b)},Zm(a,b){a=L(a);if(0>b||0===(a.flags&2097155))throw new l.Wi(28);Mb(a,a.node,b)},open(a,b,c=438){if(""===a)throw new l.Wi(44);if("string"==typeof b){var d=
{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=I(a,{pj:!(b&131072),mm:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new l.Wi(20);}else{if(e)throw new l.Wi(31);d=l.rj(a,c|511,0);f=!0}if(!d)throw new l.Wi(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new l.Wi(54);if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&
3],b&512&&(e+="w"),e=H(d.mode)&&("r"!==e||b&576)?31:zb(d,e)):e=44,e))throw new l.Wi(e);b&512&&!f&&l.truncate(d,0);b&=-131713;b=Gb({node:d,path:Cb(d),flags:b,seekable:!0,position:0,Yi:d.Yi,wm:[],error:!1});b.Yi.open&&b.Yi.open(b);f&&mb(d,c&511);return b},close(a){if(null===a.fd)throw new l.Wi(8);a.Rj&&(a.Rj=null);try{a.Yi.close&&a.Yi.close(a)}catch(b){throw b;}finally{l.streams[a.fd]=null}a.fd=null},ij(a,b,c){if(null===a.fd)throw new l.Wi(8);if(!a.seekable||!a.Yi.ij)throw new l.Wi(70);if(0!=c&&1!=
c&&2!=c)throw new l.Wi(28);a.position=a.Yi.ij(a,b,c);a.wm=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new l.Wi(28);if(null===a.fd)throw new l.Wi(8);if(1===(a.flags&2097155))throw new l.Wi(8);if(H(a.node.mode))throw new l.Wi(31);if(!a.Yi.read)throw new l.Wi(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new l.Wi(70);b=a.Yi.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new l.Wi(28);if(null===a.fd)throw new l.Wi(8);if(0===
(a.flags&2097155))throw new l.Wi(8);if(H(a.node.mode))throw new l.Wi(31);if(!a.Yi.write)throw new l.Wi(28);a.seekable&&a.flags&1024&&l.ij(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new l.Wi(70);b=a.Yi.write(a,b,c,d,e,f);g||(a.position+=b);return b},Vj(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new l.Wi(2);if(1===(a.flags&2097155))throw new l.Wi(2);if(!a.Yi.Vj)throw new l.Wi(43);if(!b)throw new l.Wi(28);return a.Yi.Vj(a,b,c,d,e)},bk(a,b,c,d,
e){return a.Yi.bk?a.Yi.bk(a,b,c,d,e):0},Qk(a,b,c){if(!a.Yi.Qk)throw new l.Wi(59);return a.Yi.Qk(a,b,c)},kn(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&A(`Invalid encoding type "${b.encoding}"`);var c=l.open(a,b.flags);a=l.stat(a).size;var d=new Uint8Array(a);l.read(c,d,0,a,0);"utf8"===b.encoding&&(d=C(d));l.close(c);return d},tk:()=>l.ll,Im(a){a=I(a,{pj:!0});if(null===a.node)throw new l.Wi(44);if(!H(a.node.mode))throw new l.Wi(54);var b=zb(a.node,
"x");if(b)throw new l.Wi(b);l.ll=a.path},om(){l.Pk=!1;for(var a of l.streams)a&&l.close(a)},Wm(a,b){try{var c=I(a,{pj:!b});a=c.path}catch(f){}var d=!1,e=null;try{c=I(a,{parent:!0}),Ra(a),c=I(a,{pj:!b}),d=!0,e=c.node}catch(f){}return d?e:null},Jj(a,b,c,d){a=Sa("string"==typeof a?a:Cb(a),b);b=lb(!!c,!!d);var e;(e=l.Jj).Tk??(e.Tk=64);e=l.Uj(l.Jj.Tk++,0);cb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var q=0,r=0;r<n;r++){try{var t=c()}catch(v){throw new l.Wi(29);}if(void 0===
t&&0===q)throw new l.Wi(6);if(null===t||void 0===t)break;q++;g[m+r]=t}q&&(f.node.Fj=Date.now());return q},write(f,g,m,n){for(var q=0;q<n;q++)try{d(g[m+q])}catch(r){throw new l.Wi(29);}n&&(f.node.gj=f.node.lj=Date.now());return q}});return Lb(a,b,e)}},Rb=(a,b)=>a?C(w,a,b):"";function Sb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?l.tk():L(a).path;if(0==b.length){if(!c)throw new l.Wi(44);return a}return a+"/"+b}
function Tb(a,b){z.setUint32(4*(a>>2),b.Ql,!0);z.setUint32(4*(a+4>>2),b.mode,!0);z.setUint32(4*(a+8>>2),b.lm,!0);z.setUint32(4*(a+12>>2),b.uid,!0);z.setUint32(4*(a+16>>2),b.am,!0);z.setUint32(4*(a+20>>2),b.nk,!0);z.setBigInt64(8*(a+24>>3),BigInt(b.size),!0);z.setInt32(4*(a+32>>2),4096,!0);z.setInt32(4*(a+36>>2),b.il,!0);var c=b.Fj.getTime(),d=b.gj.getTime(),e=b.lj.getTime();z.setBigInt64(8*(a+40>>3),BigInt(Math.floor(c/1E3)),!0);z.setUint32(4*(a+48>>2),c%1E3*1E6,!0);z.setBigInt64(8*(a+56>>3),BigInt(Math.floor(d/
1E3)),!0);z.setUint32(4*(a+64>>2),d%1E3*1E6,!0);z.setBigInt64(8*(a+72>>3),BigInt(Math.floor(e/1E3)),!0);z.setUint32(4*(a+80>>2),e%1E3*1E6,!0);z.setBigInt64(8*(a+88>>3),BigInt(b.dm),!0);return 0}
var La=void 0,Ub=[0,31,60,91,121,152,182,213,244,274,305,335],Vb=[0,31,59,90,120,151,181,212,243,273,304,334],Wb=[],Xb=(a,b)=>{Wb.length=0;for(var c;c=w[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Wb.push(112==c?z.getUint32(4*(b>>2),!0):106==c?z.getBigInt64(8*(b>>3),!0):105==c?z.getInt32(4*(b>>2),!0):z.getFloat64(8*(b>>3),!0));b+=d?8:4}return Wb},Zb=(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},ic=(a,b)=>{$b=a;ac=b;if(!bc)return 1;cc||=!0;if(0==a)dc=function(){setTimeout(ec,Math.max(0,fc+b-performance.now())|
0)};else if(1==a)dc=function(){gc(ec)};else{if(!hc)if(globalThis.setImmediate)hc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);hc=d=>{c.push(d);postMessage("setimmediate","*")}}dc=function(){hc(ec)}}return 0},jc=0,kc=a=>{na=a;Ja||0<jc||(h.onExit?.(a),ma=!0);throw new Da(a);},lc=a=>{if(a instanceof Da||"unwind"==a)return na;throw a;},mc=()=>{if(!(Ja||0<jc))try{var a=na;na=a;kc(a)}catch(b){lc(b)}},
wc=(a,b,c,d,e)=>{function f(){return g<nc?(mc(),!1):!0}bc=a;oc=d;var g=nc;cc=!1;ec=function(){if(!ma)if(0<pc.length){var m=pc.shift();m.$m(m.xm);if(qc){var n=qc,q=0==n%1?n-1:Math.floor(n);qc=m.Km?q:(8*n+(q+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=qc??0,q=rc.Qm??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(ec,0)}else if(f())if(sc=sc+1|0,1==$b&&1<ac&&0!=sc%ac)dc();else{0==$b&&(fc=performance.now());a:if(!ma){for(m of tc)if(!1===
m())break a;uc(a);for(n of vc)n()}f()&&dc()}};e||(0<b?ic(0,1E3/b):ic(1,1),dc());if(c)throw"unwind";},uc=a=>{if(!ma)try{return a()}catch(b){lc(b)}finally{mc()}},cc=!1,dc=null,nc=0,bc=null,oc=0,$b=0,ac=0,sc=0,pc=[],tc=[],vc=[];function xc(){dc=null;nc++}function yc(){nc++;var a=$b,b=ac,c=bc;bc=null;wc(c,0,!1,oc,!0);ic(a,b);dc()}var zc=0;
function gc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===zc)zc=b+1E3/60;else for(;b+2>=zc;)zc+=1E3/60;setTimeout(a,Math.max(zc-b,0))}}var rc={},fc,ec,hc,qc;function Ac(a){var b=M.mj[a];b.target.removeEventListener(b.kj,b.ol,b.xj);M.mj.splice(a,1)}
function Cc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of M.Kj)if(e.al==a&&d(e.hl,c))return;M.Kj.push({al:a,ul:b,hl:c});M.Kj.sort((f,g)=>f.ul<g.ul)}function Dc(a){M.Kj=M.Kj.filter(b=>b.al!=a)}function Ec(){return navigator.userActivation?navigator.userActivation.isActive:M.Ok&&M.Ll.gl}function Fc(){if(Ec()){var a=M.Kj;M.Kj=[];for(var b of a)b.al(...b.hl)}}
function Gc(a){if(!a.target)return-4;if(a.nj)a.ol=function(c){++M.Ok;M.Ll=a;Fc();a.Aj(c);Fc();--M.Ok},a.target.addEventListener(a.kj,a.ol,a.xj),M.mj.push(a);else for(var b=0;b<M.mj.length;++b)M.mj[b].target==a.target&&M.mj[b].kj==a.kj&&Ac(b--);return 0}function Hc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={zm:0,Nk:0,Sk:0,fn:0,fl:0,cl:0,Lk:0,Nm:0,Xk:0,Mm:0,Mk:0,Yk:0,el:0,qn:0,ln(){for(;M.mj.length;)Ac(M.mj.length-1);M.Kj=[]},Ok:0,Kj:[],mj:[],qm:(a,b)=>{for(var c=0;c<M.mj.length;++c)M.mj[c].target!=a||b&&b!=M.mj[c].kj||Ac(c--)},mn(a){let b=!1;for(let c=0;c<M.mj.length;++c){const d=M.mj[c];d.target===a.target&&d.oj===a.oj&&d.nj===a.nj&&d.yj===a.yj&&(Ac(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ic=[0,document,window],N=a=>
{a=2<a?a?C(w,a):"":a;return Ic[a]||document.querySelector(a)},Kc=a=>{var b=Za(a)+1,c=Jc(b);D(a,w,c,b);return c},Lc=a=>{var b=O(),c=Jc(8),d=c+4;a=Kc(a.id);if(a=N(a))z.setInt32(4*(c>>2),a.width,!0),z.setInt32(4*(d>>2),a.height,!0);c=[z.getInt32(4*(c>>2),!0),z.getInt32(4*(d>>2),!0)];P(b);return c},Mc=(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},Nc=(a,b,c)=>{if(a.Jm){var d=O();a=Kc(a.id);Mc(a,b,c);P(d)}else a.width=b,a.height=c},Oc={},Qc=a=>{function b(){Pc()||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),Nc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=t,a.style.paddingBottom=v,a.style.marginLeft=E,a.style.marginRight=G,a.style.marginTop=J,a.style.marginBottom=R,document.body.style.margin=Z,document.documentElement.style.overflow=aa,document.body.scroll=ra,a.style.Mj=x,
a.ek&&a.ek.Zj.viewport(0,0,d,e),Oc.rk&&Q(Oc.rk,37,0,Oc.jl))}var c=Lc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,t=a.style.paddingTop,v=a.style.paddingBottom,E=a.style.marginLeft,G=a.style.marginRight,J=a.style.marginTop,R=a.style.marginBottom,Z=document.body.style.margin,aa=document.documentElement.style.overflow,ra=document.body.scroll,x=a.style.Mj;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Rc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Sc=a=>0>Ic.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Tc=(a,b)=>{if(0!=b.$k||0!=b.Ek){Qc(a);var c=b.tm?innerWidth:screen.width,d=b.tm?innerHeight:screen.height,e=Sc(a),f=e.width;e=e.height;var g=Lc(a),m=g[0];g=g[1];3==b.$k?(Rc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.$k&&(c*g<m*d?(f=g*c/m,Rc(a,(d-f)/2,0),d=f):(f=m*d/g,Rc(a,0,(c-f)/
2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Vl&&(a.style.Mj="optimizeSpeed",a.style.Mj="-moz-crisp-edges",a.style.Mj="-o-crisp-edges",a.style.Mj="-webkit-optimize-contrast",a.style.Mj="optimize-contrast",a.style.Mj="crisp-edges",a.style.Mj="pixelated");n=2==b.Ek?devicePixelRatio:1;0!=b.Ek&&(c=c*n|0,d=d*n|0,Nc(a,c,d),a.ek&&a.ek.Zj.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();
else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return M.fullscreenEnabled()?-3:-1;Oc=b;b.rk&&Q(b.rk,37,0,b.jl);return 0},Uc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Vc=a=>{try{a()}catch(b){A(b)}};
function Wc(a){var b=(...c)=>{Xc.push(a);try{return a(...c)}finally{if(!ma&&(Xc.pop(),S&&1===Yc&&0===Xc.length&&(Yc=0,Vc(Zc),"undefined"!=typeof $c&&!ad&&bd))){ad=!0;do{c=bd;bd=0;var d=z.getUint32(4*(c>>2),!0),e=z.getUint32(4*(c+4>>2),!0);cd(d,e);P(z.getUint32(4*(c+8>>2),!0));d=z.getUint32(4*(c+12>>2),!0);0!==d?(S=null,z.setUint32(4*(c+12>>2),0,!0),dynCall_vi(d,z.getUint32(4*(c+16>>2),!0))):(S=c+=20,Yc=2,dd(c),ed(c))}while(bd);ad=!1}}};fd.set(a,b);return b}
var Yc=0,S=null,gd=0,Xc=[],hd=new Map,jd=new Map,fd=new Map,kd=0,ld=null,md=[];function nd(){return new Promise((a,b)=>{ld={resolve:a,reject:b}})}function od(){var a=pd(4108),b=a+12;z.setUint32(4*(a>>2),b,!0);z.setUint32(4*(a+4>>2),b+4096,!0);qd(a);return a}function qd(a){var b=Xc[0];if(!hd.has(b)){var c=kd++;hd.set(b,c);jd.set(c,b)}b=hd.get(b);z.setInt32(4*(a+8>>2),b,!0)}function ed(a){a=z.getInt32(4*(a+8>>2),!0);a=jd.get(a);a=fd.get(a);return uc(a)}
function rd(a){if(!ma){if(0===Yc){var b=!1,c=!1;a((d=0)=>{if(!ma&&(gd=d,b=!0,c)){Yc=2;Vc(()=>dd(S));"undefined"!=typeof rc&&bc&&yc();d=!1;try{var e=ed(S)}catch(m){e=m,d=!0}var f=!1;if(!S){var g=ld;g&&(ld=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Yc=1,S=od(),"undefined"!=typeof rc&&bc&&xc(),Vc(()=>sd(S)))}else 2===Yc?(Yc=0,Vc(td),ud(S),S=null,md.forEach(uc)):A(`invalid state: ${Yc}`);return gd}}var vd=a=>rd(async b=>{b(await a())}),bd=0,ad=!1,$c={};
function Pc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var wd=a=>{var b=Pc(),c=!!b;u[a]=c;u[a+1]=M.fullscreenEnabled();var d=c?b:M.nm,e=d?.id||"";D(Hc(d),w,a+2,128);D(e,w,a+130,128);z.setInt32(4*(a+260>>2),d?d.clientWidth:0,!0);z.setInt32(4*(a+264>>2),d?d.clientHeight:0,!0);z.setInt32(4*(a+268>>2),screen.width,!0);z.setInt32(4*(a+272>>2),screen.height,!0);c&&(M.nm=b)},xd=(a,b)=>{z.setFloat64(8*(a>>3),b.timestamp,!0);for(var c=0;c<b.axes.length;++c)z.setFloat64(8*(a+8*c+16>>3),b.axes[c],!0);for(c=0;c<b.buttons.length;++c)"object"==typeof b.buttons[c]?
z.setFloat64(8*(a+8*c+528>>3),b.buttons[c].value,!0):z.setFloat64(8*(a+8*c+528>>3),b.buttons[c],!0);for(c=0;c<b.buttons.length;++c)u[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];u[a+1104]=b.connected;z.setInt32(4*(a+1108>>2),b.index,!0);z.setInt32(4*(a+8>>2),b.axes.length,!0);z.setInt32(4*(a+12>>2),b.buttons.length,!0);D(b.id,w,a+1112,64);D(b.mapping,w,a+1176,64)},yd=a=>{setTimeout(()=>{uc(a)},1E4)},zd=!1,Ad=[];
function vb(){function a(){zd=document.pointerLockElement===h.canvas}if(!Bd){Bd=!0;tb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Cd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Cd(d)}));var f=URL.createObjectURL(e);return new Promise((g,m)=>{var n=new Image;n.onload=()=>{var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{ka(`Image ${f} could not be decoded`);m()};n.src=f})}});tb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Cd(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=()=>{if(!g){ka(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var q="",r=0,t=0,v=0;v<c.length;v++)for(r=r<<
8|c[v],t+=8;6<=t;){var E=r>>t-6&63;t-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[E]}2==t?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],q+="=="):4==t&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],q+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+q;f(n)}};n.src=m;yd(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!zd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Dd(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Ad.forEach(b=>b());vb();return a}function Cd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var ub={},Bd,T,Ed=1,Fd=[],U=[],Gd=[],Hd=[],Id=[],V=[],Jd=[],Kd=[],W=[],Ld=[],Md=[],Nd=[],Od={},Pd={},Qd=4,Rd=0,Sd=a=>{for(var b=Ed++,c=a.length;c<b;c++)a[c]=null;return b},Td=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&Sd(d);f&&(f.name=g,d[g]=f);z.setInt32(4*(b+4*e>>2),g,!0)}},Vd=(a,b)=>{if(h.preinitializedWebGLContext){var c=h.preinitializedWebGLContext;b.sl=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else a.gk||(a.gk=a.getContext,a.getContext=function(d,e){e=a.gk(d,e);
return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=a.getContext("webgl2",b);return c?Ud(c,b):0},Ud=(a,b)=>{var c=Sd(Kd);b={handle:c,attributes:b,version:b.sl,Zj:a};a.canvas&&(a.canvas.ek=b);Kd[c]=b;return c},Wd,Xd=a=>T.activeTexture(a),Yd=(a,b)=>{T.attachShader(U[a],V[b])},Zd=(a,b)=>{35051==a?T.Fk=b:35052==a&&(T.zj=b);T.bindBuffer(a,Fd[b])},$d=(a,b)=>{T.bindFramebuffer(a,Gd[b])},ae=(a,b)=>{T.bindTexture(a,Id[b])},be=a=>{T.bindVertexArray(Jd[a])},ce=(a,b)=>T.blendEquationSeparate(a,b),
de=(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),ee=(a,b,c,d,e,f,g,m,n,q)=>T.blitFramebuffer(a,b,c,d,e,f,g,m,n,q),fe=(a,b,c,d)=>{c&&b?T.bufferData(a,w,d,c,b):T.bufferData(a,b,d)},ge=(a,b,c,d)=>{c&&T.bufferSubData(a,b,w,d,c)},he=a=>T.clear(a),ie=(a,b,c,d)=>T.clearColor(a,b,c,d),je=a=>T.clearDepth(a),ke=a=>{T.compileShader(V[a])},le=(a,b,c,d,e,f,g,m,n)=>{T.zj||!m?T.compressedTexSubImage2D(a,b,c,d,e,f,g,m,n):T.compressedTexSubImage2D(a,b,c,d,e,f,g,w,n,m)},me=()=>{var a=Sd(U),b=T.createProgram();b.name=a;b.Bk=
b.zk=b.Ak=0;b.dl=1;U[a]=b;return a},ne=a=>{var b=Sd(V);V[b]=T.createShader(a);return b},oe=a=>T.cullFace(a),pe=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Fd[d];e&&(T.deleteBuffer(e),e.name=0,Fd[d]=null,d==T.Fk&&(T.Fk=0),d==T.zj&&(T.zj=0))}},qe=(a,b)=>{for(var c=0;c<a;++c){var d=z.getInt32(4*(b+4*c>>2),!0),e=Gd[d];e&&(T.deleteFramebuffer(e),e.name=0,Gd[d]=null)}},re=a=>{if(a){var b=U[a];b&&(T.deleteProgram(b),b.name=0,U[a]=null)}},se=a=>{if(a){var b=V[a];b&&(T.deleteShader(b),
V[a]=null)}},te=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Id[d];e&&(T.deleteTexture(e),e.name=0,Id[d]=null)}},ue=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0);T.deleteVertexArray(Jd[d]);Jd[d]=null}},ve=a=>T.depthFunc(a),we=a=>{T.depthMask(!!a)},xe=a=>T.disable(a),ye=a=>{T.disableVertexAttribArray(a)},ze=(a,b,c)=>{T.drawArrays(a,b,c)},Ae=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Be=[],Ce=(a,b)=>{for(var c=Be[a],d=0;d<a;d++)c[d]=z.getInt32(4*(b+4*d>>2),!0);
T.drawBuffers(c)},De=(a,b,c,d)=>{T.drawElements(a,b,c,d)},Ee=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Fe=a=>T.enable(a),Ge=a=>{T.enableVertexAttribArray(a)},He=(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,Id[d],e)},Ie=a=>T.frontFace(a),Je=(a,b)=>{Td(a,b,"createBuffer",Fd)},Ke=(a,b)=>{Td(a,b,"createFramebuffer",Gd)},Le=(a,b)=>{Td(a,b,"createTexture",Id)},Me=(a,b)=>{Td(a,b,"createVertexArray",Jd)},Ne=a=>T.generateMipmap(a),Oe=(a,b,c,d,e,f,g,m)=>{b=U[b];if(a=T[a](b,c))d=m&&D(a.name,w,m,d),e&&
z.setInt32(4*(e>>2),d,!0),f&&z.setInt32(4*(f>>2),a.size,!0),g&&z.setInt32(4*(g>>2),a.type,!0)},Pe=(a,b,c,d,e,f,g)=>Oe("getActiveUniform",a,b,c,d,e,f,g),Qe=(a,b)=>{z.setUint32(4*(a>>2),b,!0);var c=z.getUint32(4*(a>>2),!0);z.setUint32(4*(a+4>>2),(b-c)/4294967296,!0)},Re=()=>{var a="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(T.getSupportedExtensions()||[]).filter(b=>a.includes(b))},Se=()=>{var a=Re();return a=a.concat(a.map(b=>"GL_"+b))},Te=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:d=Se().length;break;case 33307:case 33308:d=33307==a?3:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z.setInt32(4*(b+4*a>>2),e[a],!0);break;case 2:z.setFloat32(4*(b+4*a>>2),e[a],!0);break;case 4:u[b+a]=e[a]?1:0}return}d=
e.name|0}}switch(c){case 1:Qe(b,d);break;case 0:z.setInt32(4*(b>>2),d,!0);break;case 2:z.setFloat32(4*(b>>2),d,!0);break;case 4:u[b]=d?1:0}}},Ue=(a,b,c,d)=>{b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:return}else if(b instanceof WebGLBuffer)a=b.name|0;else return;break;default:return}switch(d){case 1:Qe(c,a);break;case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*
(c>>2),a,!0);break;case 4:u[c]=a?1:0;break;default:A("internal emscriptenWebGLGetIndexed() error, bad type: "+d)}},Ve=(a,b)=>Te(a,b,0),We=(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);b=0<b&&d?D(a,w,d,b):0;c&&z.setInt32(4*(c>>2),b,!0)},Xe=(a,b,c)=>{if(c&&!(a>=Ed))if(a=U[a],35716==b)z.setInt32(4*(c>>2),T.getProgramInfoLog(a).length+1,!0);else if(35719==b){if(!a.Bk){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Bk=Math.max(a.Bk,T.getActiveUniform(a,b).name.length+1)}z.setInt32(4*(c>>2),a.Bk,!0)}else if(35722==
b){if(!a.zk)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.zk=Math.max(a.zk,T.getActiveAttrib(a,b).name.length+1);z.setInt32(4*(c>>2),a.zk,!0)}else if(35381==b){if(!a.Ak)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.Ak=Math.max(a.Ak,T.getActiveUniformBlockName(a,b).length+1);z.setInt32(4*(c>>2),a.Ak,!0)}else z.setInt32(4*(c>>2),T.getProgramParameter(a,b),!0)},Ye=(a,b,c)=>{if(c){a=W[a];b=2>Wd.version?T.Lj.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=
b;Qe(c,d)}},Ze=(a,b,c)=>{if(c){a=T.Lj.getQueryObjectEXT(W[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)}},$e=(a,b,c,d)=>{a=T.getShaderInfoLog(V[a]);b=0<b&&d?D(a,w,d,b):0;c&&z.setInt32(4*(c>>2),b,!0)},af=(a,b,c)=>{c&&(35716==b?(a=T.getShaderInfoLog(V[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):35720==b?(a=T.getShaderSource(V[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):z.setInt32(4*(c>>2),T.getShaderParameter(V[a],b),!0))},bf=a=>{var b=Za(a)+1,c=pd(b);c&&D(a,w,c,b);return c},
cf=a=>{var b=Od[a];if(!b){switch(a){case 7939:b=bf(Se().join(" "));break;case 7936:case 7937:case 37445:case 37446:b=(b=T.getParameter(a))?bf(b):0;break;case 7938:b=bf(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=bf(b)}Od[a]=b}return b},df=(a,b)=>{if(2>Wd.version)return 0;var c=Pd[a];if(c)return 0>b||b>=c.length?0:c[b];
switch(a){case 7939:return c=Se().map(bf),c=Pd[a]=c,0>b||b>=c.length?0:c[b];default:return 0}},ef=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ff=a=>{var b=a.qk,c=a.yl,d;if(!b){a.qk=b={};a.xl={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=T.getActiveUniform(a,d);var g=f.name;f=f.size;var m=ef(g);m=0<m?g.slice(0,m):g;var n=a.dl;a.dl+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=g,a.xl[n++]=m}}},gf=(a,b)=>{b=b?C(w,b):"";if(a=U[a]){ff(a);var c=a.qk,d=0,e=b,f=ef(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,
e=b.slice(0,f));if((e=a.yl[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}return-1},X=a=>{var b=T.Ml,c=b.qk[a];"number"==typeof c&&(b.qk[a]=c=T.getUniformLocation(b,b.xl[a]+(0<c?`[${c}]`:"")));return c},hf=(a,b,c,d)=>{if(c)if(a=U[a],ff(a),a=T.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*
(c+4*b>>2),a[b],!0)}},jf=(a,b,c)=>{hf(a,b,c,2)},kf=(a,b,c)=>{hf(a,b,c,0)},lf=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),34975==b)z.setInt32(4*(c>>2),a&&a.name,!0);else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;case 5:c=4*(c>>2),d=Math.fround(a),z.setInt32(c,d,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0);break;case 5:var e=
4*(c+4*b>>2),f=Math.fround(a[b]);z.setInt32(e,f,!0)}},mf=(a,b,c)=>{lf(a,b,c,0)},nf=a=>(a=Jd[a])?T.isVertexArray(a):0,of=a=>{a=U[a];T.linkProgram(a);a.qk=0;a.yl={}},pf=(a,b)=>{3317==a?Qd=b:3314==a&&(Rd=b);T.pixelStorei(a,b)},qf=a=>T.readBuffer(a),rf=a=>{a-=5120;return 0==a?u:1==a?w:2==a?qa:4==a?ta:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?ua:sa},sf=(a,b,c,d,e,f,g)=>{if(T.Fk)T.readPixels(a,b,c,d,e,f,g);else{var m=rf(f);g>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);T.readPixels(a,b,c,d,e,f,m,g)}},
tf=(a,b,c,d)=>T.scissor(a,b,c,d),uf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?z.getUint32(4*(d+4*f>>2),!0):void 0;e+=Rb(z.getUint32(4*(c+4*f>>2),!0),g)}T.shaderSource(V[a],e)},vf=(a,b,c,d,e)=>{a=rf(a);b=d*((Rd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Qd-1&-Qd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},wf=(a,b,c,d,e,f,g,m,n)=>{if(T.zj)T.texImage2D(a,b,c,d,e,f,g,m,n);else if(n){var q=
rf(m);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,f,g,m,q,n)}else q=n?vf(m,g,d,e,n):null,T.texImage2D(a,b,c,d,e,f,g,m,q)},xf=(a,b,c)=>T.texParameteri(a,b,c),yf=(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),zf=(a,b,c,d,e,f,g,m,n)=>{if(T.zj)T.texSubImage2D(a,b,c,d,e,f,g,m,n);else if(n){var q=rf(m);T.texSubImage2D(a,b,c,d,e,f,g,m,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=n?vf(m,g,e,f,n):null,T.texSubImage2D(a,b,c,d,e,f,g,m,n)},Af=(a,b,c)=>{b&&T.uniform1fv(X(a),y,c>>2,b)},Bf=(a,b,c)=>
{b&&T.uniform1iv(X(a),ta,c>>2,b)},Cf=(a,b,c)=>{b&&T.uniform2fv(X(a),y,c>>2,2*b)},Df=(a,b,c)=>{b&&T.uniform2iv(X(a),ta,c>>2,2*b)},Ef=(a,b,c)=>{b&&T.uniform3fv(X(a),y,c>>2,3*b)},Ff=(a,b,c)=>{b&&T.uniform3iv(X(a),ta,c>>2,3*b)},Gf=(a,b,c)=>{b&&T.uniform4fv(X(a),y,c>>2,4*b)},Hf=(a,b,c)=>{b&&T.uniform4iv(X(a),ta,c>>2,4*b)},If=(a,b,c,d)=>{b&&T.uniformMatrix3fv(X(a),!!c,y,d>>2,9*b)},Jf=(a,b,c,d)=>{b&&T.uniformMatrix4fv(X(a),!!c,y,d>>2,16*b)},Kf=a=>{a=U[a];T.useProgram(a);T.Ml=a},Lf=(a,b)=>{T.vertexAttribDivisor(a,
b)},Mf=(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},Nf=(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},Of=(a,b,c,d)=>T.viewport(a,b,c,d),Pf=(a,b)=>{if(!M.fullscreenEnabled())return-1;a=N(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ec()?Tc(a,b):b.Pl?(Cc(Tc,1,[a,b]),1):-2:-3:-4},Qf=()=>{try{if(navigator.getGamepads)return(M.yk=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Rf=(a,b)=>{var c={target:N(2),kj:"beforeunload",oj:28,yj:a,nj:b,Aj:d=>{var e=
Q(b,28,0,a);e&&=e?C(w,e):"";if(e)return d.preventDefault(),d.returnValue=e},xj:!0};return Gc(c)},Sf=(a,b,c,d,e,f)=>{M.Lk||(M.Lk=pd(256));a={target:N(a),kj:f,oj:e,yj:b,nj:d,Aj:g=>{var m=g.target.id?g.target.id:"",n=M.Lk;D(Hc(g.target),w,n+0,128);D(m,w,n+128,128);Q(d,e,n,b)&&g.preventDefault()},xj:c};return Gc(a)},Tf=(a,b,c,d,e)=>{M.Mk||(M.Mk=pd(276));return Gc({target:a,kj:e,oj:19,yj:b,nj:d,Aj:f=>{var g=M.Mk;wd(g);Q(d,19,g,b)&&f.preventDefault()},xj:c})},Uf=(a,b,c,d,e)=>{M.Nk||(M.Nk=pd(1240));b={target:N(2),
gl:!0,kj:e,oj:d,yj:a,nj:c,Aj:f=>{var g=M.Nk;xd(g,f.gamepad);Q(c,d,g,a)&&f.preventDefault()},xj:b};return Gc(b)},Vf=(a,b,c,d,e,f)=>{M.Sk||(M.Sk=pd(160));a={target:N(a),kj:f,oj:e,yj:b,nj:d,Aj:g=>{var m=M.Sk;z.setFloat64(8*(m>>3),g.timeStamp,!0);var n=m>>2;z.setInt32(4*(n+2),g.location,!0);u[m+12]=g.ctrlKey;u[m+13]=g.shiftKey;u[m+14]=g.altKey;u[m+15]=g.metaKey;u[m+16]=g.repeat;z.setInt32(4*(n+5),g.charCode,!0);z.setInt32(4*(n+6),g.keyCode,!0);z.setInt32(4*(n+7),g.which,!0);D(g.key||"",w,m+32,32);D(g.code||
"",w,m+64,32);D(g.char||"",w,m+96,32);D(g.locale||"",w,m+128,32);Q(d,e,m,b)&&g.preventDefault()},xj:c};return Gc(a)},Wf=(a,b,c)=>{var d=screen.orientation;M.Xk||(M.Xk=pd(8));return Gc({target:d,kj:"change",oj:18,yj:a,nj:c,Aj:e=>{var f=M.Xk,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],m=["portrait","portrait","landscape","landscape"],n=0;var q=window.screen?screen.orientation||screen.mozOrientation||screen.webkitOrientation:void 0;"object"===typeof q?(n=g.indexOf(q.type),
0>n&&(n=m.indexOf(q.type)),0<=n&&(n=1<<n),g=q.angle):g=window.orientation;z.setInt32(4*(f>>2),n,!0);z.setInt32(4*(f+4>>2),g,!0);Q(c,18,f,a)&&e.preventDefault()},xj:b})},Xf=(a,b,c,d)=>{M.Yk||(M.Yk=pd(257));return Gc({target:a,kj:"pointerlockchange",oj:20,yj:b,nj:d,Aj:e=>{var f=M.Yk,g=document.pointerLockElement;u[f]=!!g;var m=g?.id||"";D(Hc(g),w,f+1,128);D(m,w,f+129,128);Q(d,20,f,b)&&e.preventDefault()},xj:c})},Yf=(a,b,c,d)=>{M.cl||(M.cl=pd(36));a=N(a);return Gc({target:a,kj:"resize",oj:10,yj:b,nj:d,
Aj:e=>{if(e.target==a){var f=document.body;if(f){var g=M.cl;z.setInt32(4*(g>>2),0,!0);z.setInt32(4*(g+4>>2),f.clientWidth,!0);z.setInt32(4*(g+8>>2),f.clientHeight,!0);z.setInt32(4*(g+12>>2),innerWidth,!0);z.setInt32(4*(g+16>>2),innerHeight,!0);z.setInt32(4*(g+20>>2),outerWidth,!0);z.setInt32(4*(g+24>>2),outerHeight,!0);z.setInt32(4*(g+28>>2),pageXOffset|0,!0);z.setInt32(4*(g+32>>2),pageYOffset|0,!0);Q(d,10,g,b)&&e.preventDefault()}}},xj:c})},Zf=(a,b,c)=>{var d=Ic[1];M.el||(M.el=pd(8));return Gc({target:d,
kj:"visibilitychange",oj:21,yj:a,nj:c,Aj:e=>{var f=M.el,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);u[f]=document.hidden;z.setInt32(4*(f+4>>2),g,!0);Q(c,21,f,a)&&e.preventDefault()},xj:b})},$f=(a,b,c,d)=>{M.fl||(M.fl=pd(96));return Gc({target:a,gl:!0,kj:"wheel",oj:9,yj:b,nj:d,Aj:e=>{var f=M.fl;z.setFloat64(8*(f>>3),e.timeStamp,!0);var g=f>>2;z.setInt32(4*(g+2),e.screenX,!0);z.setInt32(4*(g+3),e.screenY,!0);z.setInt32(4*(g+4),e.clientX,!0);z.setInt32(4*(g+5),e.clientY,
!0);u[f+24]=e.ctrlKey;u[f+25]=e.shiftKey;u[f+26]=e.altKey;u[f+27]=e.metaKey;z.setInt16(2*(2*g+14),e.button,!0);z.setInt16(2*(2*g+15),e.buttons,!0);z.setInt32(4*(g+8),e.movementX,!0);z.setInt32(4*(g+9),e.movementY,!0);var m=Sc(a);z.setInt32(4*(g+10),e.clientX-(m.left|0),!0);z.setInt32(4*(g+11),e.clientY-(m.top|0),!0);z.setFloat64(8*(f+64>>3),e.deltaX,!0);z.setFloat64(8*(f+72>>3),e.deltaY,!0);z.setFloat64(8*(f+80>>3),e.deltaZ,!0);z.setInt32(4*(f+88>>2),e.deltaMode,!0);Q(d,9,f,b)&&e.preventDefault()},
xj:c})};function ag(a){var b=bg,c=b.aj.pop()||b.Ij.length;b.Ij[c]=a;return c}class cg{Ij=[void 0];aj=[];get(a){return this.Ij[a]}has(a){return void 0!==this.Ij[a]}}var bg;
function dg(a,b,c,d,e){function f(){var K=0,Y=0;x.response&&Z&&0===z.getUint32(4*(a+12>>2),!0)&&(Y=x.response.byteLength);0<Y&&(K=eg(z.getUint32(4*(a+12>>2),!0),Y),w.set(new Uint8Array(x.response),K));z.setUint32(4*(a+12>>2),K,!0);Qe(a+16,Y);Qe(a+24,0);(K=x.response?x.response.byteLength:0)&&Qe(a+32,K);z.setInt16(2*(a+40>>1),x.readyState,!0);z.setInt16(2*(a+42>>1),x.status,!0);x.statusText&&D(x.statusText,w,a+44,64);ra&&(K=bf(x.responseURL),z.setUint32(4*(a+200>>2),K,!0))}var g=z.getUint32(4*(a+8>>
2),!0);if(g){var m=g?C(w,g):"",n=a+108,q=Rb(n+0);q||="GET";var r=z.getUint32(4*(n+56>>2),!0),t=z.getUint32(4*(n+68>>2),!0),v=z.getUint32(4*(n+72>>2),!0);g=z.getUint32(4*(n+76>>2),!0);var E=z.getUint32(4*(n+80>>2),!0),G=z.getUint32(4*(n+84>>2),!0),J=z.getUint32(4*(n+88>>2),!0),R=z.getUint32(4*(n+52>>2),!0),Z=!!(R&1),aa=!!(R&2),ra=!!(R&64);t=t?t?C(w,t):"":void 0;v=v?v?C(w,v):"":void 0;var x=new XMLHttpRequest;x.withCredentials=!!w[n+60];x.aj=aa;x.open(q,m,!ra,t,v);ra||(x.timeout=r);x.hj=m;x.responseType=
"arraybuffer";E&&(m=E?C(w,E):"",x.overrideMimeType(m));if(g)for(;;){n=z.getUint32(4*(g>>2),!0);if(!n)break;m=z.getUint32(4*(g+4>>2),!0);if(!m)break;g+=8;n=n?C(w,n):"";m=m?C(w,m):"";x.setRequestHeader(n,m)}var Na=ag(x);z.setUint32(4*(a>>2),Na,!0);g=G&&J?w.slice(G,G+J):null;x.onload=K=>{bg.has(Na)&&(f(),200<=x.status&&300>x.status?b(a,x,K):c(a,K))};x.onerror=K=>{bg.has(Na)&&(f(),c(a,K))};x.ontimeout=K=>{bg.has(Na)&&c(a,K)};x.onprogress=K=>{if(bg.has(Na)){var Y=Z&&aa&&x.response?x.response.byteLength:
0,Bc=0;0<Y&&Z&&aa&&(Bc=eg(z.getUint32(4*(a+12>>2),!0),Y),w.set(new Uint8Array(x.response),Bc));z.setUint32(4*(a+12>>2),Bc,!0);Qe(a+16,Y);Qe(a+24,K.loaded-Y);Qe(a+32,K.total);z.setInt16(2*(a+40>>1),x.readyState,!0);Y=x.status;3<=x.readyState&&0===x.status&&0<K.loaded&&(Y=200);z.setInt16(2*(a+42>>1),Y,!0);x.statusText&&D(x.statusText,w,a+44,64);d(a,K)}};x.onreadystatechange=K=>{if(bg.has(Na)){z.setInt16(2*(a+40>>1),x.readyState,!0);2<=x.readyState&&z.setInt16(2*(a+42>>1),x.status,!0);if(!ra&&2===x.readyState&&
0<x.responseURL.length){var Y=bf(x.responseURL);z.setUint32(4*(a+200>>2),Y,!0)}e(a,K)}};try{x.send(g)}catch(K){c(a,K)}}else c(a,"no url specified!")}
var fg=["default","low-power","high-performance"],gg={},ig=()=>{if(!hg){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in gg)void 0===gg[b]?delete a[b]:a[b]=gg[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);hg=c}return hg},hg;new Int8Array((new Int16Array([1])).buffer);function ya(){sa.aj=a=>a&65535;ua.aj=a=>a>>>0}l.Lm=(a,b,c,d,e,f,g,m,n,q)=>{yb(a,b,c,d,e,m,n,q).then(f).catch(g)};
l.hn=yb;l.Gj=Array(4096);l.bj(F,{},"/");k("/tmp");k("/home");k("/home/web_user");(function(){k("/dev");cb(l.Uj(1,3),{read:()=>0,write:(d,e,f,g)=>g,ij:()=>0});Lb("/dev/null",l.Uj(1,3));bb(l.Uj(5,0),eb);bb(l.Uj(6,0),fb);Lb("/dev/tty",l.Uj(5,0));Lb("/dev/tty1",l.Uj(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ua(a),b=a.byteLength);return a[--b]};l.Jj("/dev","random",c);l.Jj("/dev","urandom",c);k("/dev/shm");k("/dev/shm/tmp")})();
(function(){k("/proc");var a=k("/proc/self");k("/proc/self/fd");l.bj({bj(){var b=l.createNode(a,"fd",16895,73);b.Yi={ij:F.Yi.ij};b.Xi={Tj(c,d){c=+d;var e=L(c);c={parent:null,bj:{lk:"fake"},Xi:{Oj:()=>e.path},id:c+1};return c.parent=c},Nj(){return Array.from(l.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();l.Ul={MEMFS:F,IDBFS:p};h.requestAnimationFrame=gc;h.pauseMainLoop=xc;h.resumeMainLoop=yc;h.preMainLoop&&tc.push(h.preMainLoop);
h.postMainLoop&&vc.push(h.postMainLoop);for(let a=0;32>a;++a)Be.push(Array(a));(async function(){bg=new cg})();h.noExitRuntime&&(Ja=h.noExitRuntime);h.preloadPlugins&&(tb=h.preloadPlugins);h.print&&(ja=h.print);h.printErr&&(ka=h.printErr);h.wasmBinary&&(la=h.wasmBinary);h.thisProgram&&(fa=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.callMain=jg;h.ENV=gg;h.addRunDependency=sb;h.removeRunDependency=rb;
h.ccall=(a,b,c,d,e)=>{function f(t){--jc;0!==n&&P(n);return"string"===b?t?C(w,t):"":"boolean"===b?!!t:t}var g={string:t=>{var v=0;null!==t&&void 0!==t&&0!==t&&(v=Kc(t));return v},array:t=>{var v=Jc(t.length);u.set(t,v);return v}};a=h["_"+a];var m=[],n=0;if(d)for(var q=0;q<d.length;q++){var r=g[c[q]];r?(0===n&&(n=O()),m[q]=r(d[q])):m[q]=d[q]}c=S;d=a(...m);e=e?.async;jc+=1;if(S!=c)return nd().then(f);d=f(d);return e?Promise.resolve(d):d};h.FS_preloadFile=yb;h.FS_unlink=(...a)=>l.Dj(...a);
h.FS_createPath=(...a)=>Nb(...a);h.FS_createDevice=(...a)=>l.Jj(...a);h.FS=l;h.FS_createDataFile=(...a)=>xb(...a);h.FS_createLazyFile=(...a)=>Qb(...a);
var Yb={1035352:(a,b)=>{ca(a,b)},1035372:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;"undefined"===typeof a.$j&&(a.$j=function(b){return b});"undefined"===typeof a.Dk&&(a.Dk=function(b){return b>>>2})},1035686:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,1035895:()=>{if("undefined"!==typeof h.SDL3){var a=h.SDL3;a.bl.removeEventListener("change",a.Kk);a.bl=void 0;a.Kk=void 0}},1036148:()=>
window.innerWidth,1036178:()=>window.innerHeight,1036209:a=>{h.requestFullscreen=function(){kg(a)}},1036318:(a,b)=>{a=URL.createObjectURL(new Blob([w.buffer instanceof ArrayBuffer?w.subarray(a,a+b):w.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);b.href=a},1036811:()=>{h.requestFullscreen=function(){}},
1036885:()=>window.innerWidth,1036915:()=>window.innerHeight,1036946:a=>{a=document.querySelector(a?C(w,a):"");a.El=a.style.position;a.Fl=a.style.top;a.Dl=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.aj=a;b.fk=a.parentNode;b.dk=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},
1037644:()=>{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.dk?a.fk.insertBefore(a.aj,a.dk):a.fk.appendChild(a.aj);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.aj.style.position=a.aj.El;a.aj.style.top=a.aj.Fl;a.aj.style.left=a.aj.Dl;a.remove()}},1038203:()=>{if(window.matchMedia){var a=h.SDL3;a.Kk=function(){lg()};a.bl=window.matchMedia("(prefers-color-scheme: dark)");a.bl.addEventListener("change",a.Kk)}},1038525:(a,b,c,d,e)=>{a=a?C(w,a):"";b=b?
C(w,b):"";c=c?C(w,c):"";d=d?C(w,d):"";var f=e?C(w,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},1039066:(a,b,c,d,e,f,g,m)=>{a=a?C(w,a):"";b=b?C(w,b):"";f=f?C(w,f):"";var n=g?C(w,g):"",q=m?C(w,m):"",r=document.getElementById(a);if(!r)return!1;var t=document.createElement("button");
t.innerText=b;t.style.borderColor=f;t.style.backgroundColor=n;r.addEventListener("keydown",function(v){d&&"Enter"===v.key?(v.preventDefault(),t.click()):e&&"Escape"===v.key&&(v.preventDefault(),t.click())});r.addEventListener("cancel",function(v){v.preventDefault()});t.onmouseenter=function(){t.style.backgroundColor=q};t.onmouseleave=function(){t.style.backgroundColor=n};t.onclick=function(){r.close(c)};r.append(t);return!0},1040075:a=>{a=a?C(w,a):"";return(a=document.getElementById(a))?a.open:!1},
1040213:a=>{a=a?C(w,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},1040395:(a,b)=>{alert((a?C(w,a):"")+"\n\n"+(b?C(w,b):""))},1040452:(a,b,c,d)=>{d=d?C(w,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.Kl!==e){d.hk=Dd(e);if(!d.hk)return!1;d.Kl=e}if(d.w!==a||d.h!==b||d.cm!==d.hk)d.image=d.hk.createImageData(a,b),d.w=a,d.h=b,d.cm=d.hk;a=d.image.data;c/=4;d.Ol!==a&&(d.Nl=new Int32Array(a.buffer),d.Ol=a);a=d.Nl;a.set(ta.subarray(c,c+a.length));
d.hk.putImageData(d.image,0,0);return!0},1041201:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;5>b;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&
(d.mouse_buttons[c.button]=!1)})},1041889:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(ta.subarray(e,e+b.length));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=mg(c.length+1);D(c,w,d,c.length+1);return d},1042547:a=>{h.canvas&&(h.canvas.style.cursor=a?C(w,a):"")},1042630:()=>{h.canvas&&(h.canvas.style.cursor="none")},
1042699:()=>h.SDL3.mouse_x,1042737:()=>h.SDL3.mouse_y,1042775:a=>h.SDL3.mouse_buttons[a],1042823:a=>{document.hj=function(b){"CapsLock"!=b.key&&"NumLock"!=b.key&&"ScrollLock"!=b.key&&ng(h.SDL3.$j(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.hj)},1043250:()=>{document.removeEventListener("keydown",document.hj)},1043334:a=>{var b=document;b&&(b.aj=function(c){var d=h.SDL3;c=d.kk(0,0,c);0!=c&&(og(d.$j(a),
c),pg(c))},b.addEventListener("pointerup",b.aj))},1043695:a=>{var b=h.SDL3;void 0===b.kk&&(b.kk=function(c,d,e){if("mouse"==e.pointerType)var f=1;else if("touch"==e.pointerType)f=2;else if("pen"==e.pointerType)f=3;else return 0;var g=mg(a);if(0!=g){var m=b.Dk(g),n=4*m++;z.setInt32(n,f,!0);n=4*m++;z.setInt32(n,e.pointerId,!0);n=4*m++;z.setInt32(n,"undefined"!==typeof e.button?e.button:-1,!0);n=4*m++;z.setInt32(n,e.buttons,!0);n=4*m++;z.setInt32(n,"pointerdown"==e.type?1:0,!0);n=4*m++;z.setFloat32(n,
e.movementX,!0);n=4*m++;z.setFloat32(n,e.movementY,!0);n=4*m++;z.setFloat32(n,e.clientX-c,!0);c=4*m++;z.setFloat32(c,e.clientY-d,!0);3==f&&(d=4*m++,z.setFloat32(d,e.pressure,!0),d=4*m++,z.setFloat32(d,e.pn,!0),d=4*m++,z.setFloat32(d,e.tiltX,!0),d=4*m++,z.setFloat32(d,e.tiltY,!0),m=4*m++,z.setFloat32(m,e.rn,!0))}return g})},1044687:a=>{a=a?C(w,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},1044853:()=>document.hasFocus(),1044885:()=>{var a=document;
a&&(a.removeEventListener("pointerup",a.aj),a.aj=void 0)},1045067:()=>document.body.clientWidth,1045105:()=>document.body.clientHeight,1045144:()=>window.innerWidth,1045174:()=>window.innerHeight,1045205:()=>window.outerWidth,1045235:()=>window.outerHeight,1045266:()=>window.pageXOffset,1045297:()=>window.pageYOffset,1045328:(a,b)=>{var c=document.querySelector(b?C(w,b):"");if(c){var d=h.SDL3;c.ak=function(e){var f=c.getBoundingClientRect();e=d.kk(f.left,f.top,e);0!=e&&(qg(d.$j(a),e),pg(e))};c.Ej=
function(e){var f=c.getBoundingClientRect();e=d.kk(f.left,f.top,e);0!=e&&(rg(d.$j(a),e),pg(e))};c.hj=function(e){var f=c.getBoundingClientRect();e=d.kk(f.left,f.top,e);0!=e&&(sg(d.$j(a),e),pg(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.ak);c.addEventListener("pointerleave",c.Ej);c.addEventListener("pointercancel",c.Ej);c.addEventListener("pointerdown",c.hj);c.addEventListener("pointermove",c.hj);c.addEventListener("pointerup",c.hj)}},1046716:(a,b,c)=>{var d=document.querySelector(b?
C(w,b):"");if(d){var e=h.SDL3,f=function(g){var m=mg(c);if(0!=m){var n=m>>2,q=d.getBoundingClientRect(),r=4*n++;z.setInt32(r,g.clientX-q.left,!0);n=4*n++;z.setInt32(n,g.clientY-q.top,!0)}return m};e.Ik=function(g){g.preventDefault();g=f(g);0!=g&&(tg(a,g),pg(g))};d.addEventListener("dragover",e.Ik);e.vk=0;try{k("/tmp/filedrop")}catch(g){}e.Jk=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=bf(g.dataTransfer.getData("text/plain")),ug(a,g),vg(g);else if(g.dataTransfer.types.includes("Files")){let m=
0;const n=g.dataTransfer.files.length;for(let q=0;q<n;q++){const r=g.dataTransfer.files.item(q),t=new FileReader;t.readAsArrayBuffer(r);t.onload=function(v){const E=`/tmp/filedrop/${e.vk}`;e.vk+=1;const G=`${E}/${r.name}`,J=bf(G);v=new Uint8Array(v.target.result);try{k(E);var R=l.open(G,"w");l.write(R,v,0,v.length,0);l.close(R);wg(a,J)}catch(Z){}vg(J);++m;m===n&&xg(a)};t.onerror=function(){++m;m===n&&xg(a)}}}xg(a)};d.addEventListener("drop",e.Jk);e.jk=function(g){g.preventDefault();xg(a)};d.addEventListener("dragend",
e.jk);d.addEventListener("dragleave",e.jk)}},1049083:a=>{if(a=document.querySelector(a?C(w,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.jk);a.removeEventListener("dragend",b.jk);a.removeEventListener("drop",b.Jk);b.vk=void 0;"/tmp/filedrop";l.Cj("/tmp/filedrop");a.removeEventListener("dragover",b.Ik);b.Ik=void 0;b.Jk=void 0;b.jk=void 0}},1049913:a=>{if(a=document.querySelector(a?C(w,a):""))a.removeEventListener("pointerenter",a.ak),a.removeEventListener("pointerleave",a.Ej),a.removeEventListener("pointercancel",
a.Ej),a.removeEventListener("pointerdown",a.hj),a.removeEventListener("pointermove",a.hj),a.removeEventListener("pointerup",a.hj),a.style.touchAction="",a.ak=void 0,a.Ej=void 0,a.hj=void 0},1050647:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1050794:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1051028:()=>{var a=h.SDL3;"undefined"===typeof a.dj&&
(a.dj={});"undefined"===typeof a.Zi&&(a.Zi={});a.fj||("undefined"!==typeof AudioContext?a.fj=new AudioContext:"undefined"!==typeof webkitAudioContext&&(a.fj=new webkitAudioContext),a.fj&&"undefined"===typeof navigator.userActivation&&Ia(a.fj));return void 0!==a.fj},1051607:()=>h.SDL3.fj.sampleRate,1051658:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.Zi.vj&&(clearInterval(g.Zi.vj),g.Zi.vj=void 0,g.Zi.Yj=void 0);g.Zi.Uk=g.fj.createMediaStreamSource(m);g.Zi.tj=g.fj.createScriptProcessor(b,a,1);
g.Zi.tj.onaudioprocess=function(n){void 0!==g&&void 0!==g.Zi&&(n.outputBuffer.getChannelData(0).fill(0),g.Zi.Gk=n.inputBuffer,da("ip",c,[d]))};g.Zi.Uk.connect(g.Zi.tj);g.Zi.tj.connect(g.fj.destination);g.Zi.stream=m}var g=h.SDL3;g.Zi.Yj=g.fj.createBuffer(a,b,g.fj.sampleRate);g.Zi.Yj.getChannelData(0).fill(0);g.Zi.vj=setInterval(function(){g.Zi.Gk=g.Zi.Yj;da("ip",c,[d])},b/g.fj.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},1053499:(a,b,c,d)=>{var e=h.SDL3;e.dj.tj=e.fj.createScriptProcessor(b,0,a);e.dj.tj.onaudioprocess=function(f){void 0!==e&&void 0!==e.dj&&(void 0!==e.dj.vj&&(clearInterval(e.dj.vj),e.dj.vj=void 0,e.dj.Yj=void 0),e.dj.sk=f.outputBuffer,da("ip",c,[d]))};e.dj.tj.connect(e.fj.destination);"suspended"===e.fj.state&&(e.dj.Yj=e.fj.createBuffer(a,b,e.fj.sampleRate),e.dj.Yj.getChannelData(0).fill(0),
e.dj.vj=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.fj.resume();e.dj.sk=e.dj.Yj;da("ip",c,[d]);e.dj.sk=void 0},b/e.fj.sampleRate*1E3))},1054815:a=>{var b=h.SDL3;if(a){void 0!==b.Zi.vj&&clearInterval(b.Zi.vj);if(void 0!==b.Zi.stream){a=b.Zi.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Zi.stream.removeTrack(a[c])}void 0!==b.Zi.tj&&(b.Zi.tj.onaudioprocess=function(){},b.Zi.tj.disconnect());void 0!==b.Zi.Uk&&b.Zi.Uk.disconnect();
b.Zi=void 0}else void 0!=b.dj.tj&&b.dj.tj.disconnect(),void 0!==b.dj.vj&&clearInterval(b.dj.vj),b.dj=void 0;void 0!==b.fj&&void 0===b.dj&&void 0===b.Zi&&(b.fj.close(),b.fj=void 0)},1055971:(a,b)=>{var c=h.SDL3;a=c.Dk(a);for(var d=c.dj.sk.numberOfChannels,e=0;e<d;++e){var f=c.dj.sk.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=z.getFloat32(4*(a+(g*d+e)),!0)}},1056504:(a,b)=>
{for(var c=h.SDL3,d=c.Zi.Gk.numberOfChannels,e=0;e<d;++e){var f=c.Zi.Gk.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ka(a+4*g,f[g],"float");else for(g=0;g<b;++g)Ka(a+4*(g*d+e),f[g],"float")}},1057131:()=>{h.SDL3.ik={};h.SDL3.ik.Pj=[];h.SDL3.ik.Pj[0]=void 0;h.SDL3.ik.Pj[1]=void 0},1057308:(a,b,c,d,e)=>{var f=h.SDL3.ik;void 0!==f.Pj[a]&&clearInterval(f.Pj[a]);f.Pj[a]=
setInterval(function(){da("vi",d,[e])},b/c*1E3)},1057500:a=>{var b=h.SDL3.ik;void 0!==b.Pj[a]&&clearInterval(b.Pj[a]);b.Pj[a]=void 0},1057631:a=>{let b=navigator.getGamepads();return b?(a=b[a])&&a.vibrationActuator?1:0:0},1057806:(a,b,c)=>{let d=navigator.getGamepads();if(!d)return 0;a=d[a];if(!a||!a.vibrationActuator)return 0;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:c/65535,strongMagnitude:b/65535});return 1},1058142:(a,b)=>{var c=void 0;if(navigator.languages&&
navigator.languages.length)c=navigator.languages;else{var d=navigator.aj||navigator.language||navigator.browserLanguage||navigator.systemLanguage;void 0!==d&&(c=[d])}if(void 0!==c){d="";for(var e=0;e<c.length;e++){var f=c[e];if(d.length+f.length+1>b)break;0<d.length&&(d+=",");d+=f}d=d.replace(/-/g,"_");b>d.length&&(b=d.length);for(e=0;e<b;e++)Ka(a+e,d.charCodeAt(e),"i8")}},1058850:a=>{var b=new URLSearchParams(window.location.search);for(const [d,e]of b)if(d.startsWith("SDL_")){b=bf(d);var c=bf(e);
0!=b&&0!=c&&da("iiii",a,[b,c,1]);vg(b);vg(c)}},1059191:()=>{h.onFirstFrame()}},vg,mg,pg,qg,rg,sg,og,tg,xg,ug,wg,ng,lg,kg,yg,gb,pd,ud,eg,zg,cd,P,Jc,O,Q,dynCall_vii,Ag,dynCall_vi,Bg,Cg,Dg,Eg,dynCall_v,dynCall_iii,Fg,Gg,sd,Zc,dd,td,xa,ea,Sg={Zc:function(a){a=navigator.getGamepads()[a];if(0<a.id.indexOf("Product: ")){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},_c:function(a){a=navigator.getGamepads()[a];
if(0<a.id.indexOf("Vendor: ")){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},Yc:function(a){return 0<=navigator.getGamepads()[a].id.toLowerCase().indexOf("xinput")},J:function(a,b,c){La=c;try{var d=L(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;l.streams[e];)e++;return Hb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),z.setInt16(2*
(e+0>>1),2,!0),0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;return-f.ej}},Hf:function(a){try{return L(a),0}catch(b){if("undefined"==typeof l||"ErrnoError"!==b.name)throw b;return-b.ej}},Ea:function(a,b){try{var c=L(a),d=c.node,e=c.Yi.qj;a=e?c:d;e??=d.Xi.qj;nb(e,63);var f=e(a);return Tb(b,f)}catch(g){if("undefined"==typeof l||"ErrnoError"!==g.name)throw g;return-g.ej}},jb:function(a,b,c){try{var d=L(a);d.Rj||(d.Rj=l.Nj(d.path));a=0;var e=l.ij(d,
0,1),f=Math.floor(e/280),g=Math.min(d.Rj.length,f+Math.floor(c/280));for(c=f;c<g;c++){var m=d.Rj[c];if("."===m){var n=d.node.id;var q=4}else if(".."===m)n=I(d.path,{parent:!0}).node.id,q=4;else{try{var r=ib(d.node,m)}catch(t){if(28===t?.ej)continue;throw t;}n=r.id;q=8192===(r.mode&61440)?2:H(r.mode)?4:40960===(r.mode&61440)?10:8}z.setBigInt64(8*(b+a>>3),BigInt(n),!0);z.setBigInt64(8*(b+a+8>>3),BigInt(280*(c+1)),!0);z.setInt16(2*(b+a+16>>1),280,!0);u[b+a+18]=q;D(m,w,b+a+19,256);a+=280}l.ij(d,280*c,
0);return a}catch(t){if("undefined"==typeof l||"ErrnoError"!==t.name)throw t;return-t.ej}},vg:function(a,b,c){La=c;try{var d=L(a);switch(b){case 21509:return d.cj?0:-59;case 21505:if(!d.cj)return-59;if(d.cj.Hj.em){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();z.setInt32(4*(e>>2),25856,!0);z.setInt32(4*(e+4>>2),5,!0);z.setInt32(4*(e+8>>2),191,!0);z.setInt32(4*(e+12>>2),35387,!0);for(var f=0;32>f;f++)u[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.cj?
0:-59;case 21506:case 21507:case 21508:if(!d.cj)return-59;if(d.cj.Hj.fm)for(e=Ma(),z.getInt32(4*(e>>2),!0),z.getInt32(4*(e+4>>2),!0),z.getInt32(4*(e+8>>2),!0),z.getInt32(4*(e+12>>2),!0),a=[],f=0;32>f;f++)a.push(u[e+f+17]);return 0;case 21519:if(!d.cj)return-59;e=Ma();z.setInt32(4*(e>>2),0,!0);return 0;case 21520:return d.cj?-28:-59;case 21537:case 21531:return e=Ma(),l.Qk(d,b,e);case 21523:if(!d.cj)return-59;d.cj.Hj.gm&&(f=[24,80],e=Ma(),z.setInt16(2*(e>>1),f[0],!0),z.setInt16(2*(e+2>>1),f[1],!0));
return 0;case 21524:return d.cj?0:-59;case 21515:return d.cj?0:-59;default:return-28}}catch(g){if("undefined"==typeof l||"ErrnoError"!==g.name)throw g;return-g.ej}},Qg:function(a,b){try{return a=a?C(w,a):"",Tb(b,l.stat(a,!0))}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return-c.ej}},wf:function(a,b,c){try{return b=b?C(w,b):"",b=Sb(a,b),k(b,c),0}catch(d){if("undefined"==typeof l||"ErrnoError"!==d.name)throw d;return-d.ej}},$g:function(a,b,c,d){try{b=b?C(w,b):"";var e=d&256;b=Sb(a,
b,d&4096);return Tb(c,e?l.stat(b,!0):l.stat(b))}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;return-f.ej}},R:function(a,b,c,d){La=d;try{b=b?C(w,b):"";b=Sb(a,b);var e=d?Ma():0;return l.open(b,c,e).fd}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;return-f.ej}},kh:function(a,b){try{return a=a?C(w,a):"",Tb(b,l.stat(a))}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return-c.ej}},Pa:function(a,b,c){try{b=b?C(w,b):"";b=Sb(a,b);if(c)if(512===c)l.Cj(b);
else return-28;else l.Dj(b);return 0}catch(d){if("undefined"==typeof l||"ErrnoError"!==d.name)throw d;return-d.ej}},$c:()=>A(""),Bb:()=>{throw Infinity;},Pc:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);z.setInt32(4*(b>>2),a.getSeconds(),!0);z.setInt32(4*(b+4>>2),a.getMinutes(),!0);z.setInt32(4*(b+8>>2),a.getHours(),!0);z.setInt32(4*(b+12>>2),a.getDate(),!0);z.setInt32(4*(b+16>>2),a.getMonth(),!0);z.setInt32(4*(b+20>>2),a.getFullYear()-1900,!0);z.setInt32(4*
(b+24>>2),a.getDay(),!0);var c=a.getFullYear();z.setInt32(4*(b+28>>2),(0!==c%4||0===c%100&&0!==c%400?Vb:Ub)[a.getMonth()]+a.getDate()-1|0,!0);z.setInt32(4*(b+36>>2),-(60*a.getTimezoneOffset()),!0);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z.setInt32(4*(b+32>>2),(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0,!0)},Rc:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var m=L(d),n=l.Vj(m,a,e,b,c),q=
n.vl;z.setInt32(4*(f>>2),n.Ij,!0);z.setUint32(4*(g>>2),q,!0);return 0}catch(r){if("undefined"==typeof l||"ErrnoError"!==r.name)throw r;return-r.ej}},Sc:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=L(e);if(c&2){c=f;if(!l.isFile(g.node.mode))throw new l.Wi(43);d&2||l.bk(g,w.slice(a,a+b),c,b,d)}}catch(m){if("undefined"==typeof l||"ErrnoError"!==m.name)throw m;return-m.ej}},Qc:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();z.setUint32(4*(a>>2),60*Math.max(f,e),!0);z.setInt32(4*(b>>2),Number(f!=e),!0);b=g=>{var m=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(D(a,w,c,17),D(b,w,d,17)):(D(a,w,d,17),D(b,w,c,17))},bd:function(a,b,c){if(!(0<=a&&3>=a))return 28;z.setBigInt64(8*(c>>3),BigInt(Math.round(1E6*(0===a?Date.now():performance.now()))),!0);return 0},ma:Zb,l:(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},
b:Zb,jd:(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},qa:()=>{xc();bc=null},$:()=>Date.now(),cd:()=>{if(!M.fullscreenEnabled())return-1;Dc(Tc);var a=Ic[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},id:()=>{Dc(Uc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},Db:function(a){if(bg.has(a)){var b=bg.get(a),c=bg;c.Ij[a]=void 0;c.aj.push(a);0<b.readyState&&4>
b.readyState&&b.abort()}},Tc:(a,b)=>{if(!ma)if(0===Yc){Yc=1;var c=a+20;qd(c);S=c;sd(c);c=O();z.setUint32(4*(a+8>>2),c,!0);bd=b}else Yc=0,td(),S=null},s:()=>devicePixelRatio,i:(a,b,c)=>{a=N(a);if(!a)return-4;a=Sc(a);z.setFloat64(8*(b>>3),a.width,!0);z.setFloat64(8*(c>>3),a.height,!0);return 0},ed:a=>{if(!M.fullscreenEnabled())return-1;wd(a);return 0},Z:(a,b)=>{if(0>a||a>=M.yk.length)return-5;if(!M.yk[a])return-7;xd(b,M.yk[a]);return 0},af:()=>2147483648,nd:(a,b)=>{a&&z.setInt32(4*(a>>2),$b,!0);b&&
z.setInt32(4*(b>>2),ac,!0)},ra:()=>performance.now(),Xc:()=>M.yk.length,kd:(a,b)=>{z.setInt32(4*(a>>2),screen.width,!0);z.setInt32(4*(b>>2),screen.height,!0)},Cb:Xd,Ab:Yd,jf:(a,b)=>{T.beginQuery(a,W[b])},Sd:(a,b)=>{T.Lj.beginQueryEXT(a,W[b])},Qe:a=>T.beginTransformFeedback(a),yb:(a,b,c)=>{T.bindAttribLocation(U[a],b,c?C(w,c):"")},xb:Zd,Ne:(a,b,c)=>{T.bindBufferBase(a,b,Fd[c])},Oe:(a,b,c,d,e)=>{T.bindBufferRange(a,b,Fd[c],d,e)},wb:$d,vb:(a,b)=>{T.bindRenderbuffer(a,Hd[b])},Rd:(a,b)=>{T.bindSampler(a,
Ld[b])},ub:ae,Jd:(a,b)=>{T.bindTransformFeedback(a,Md[b])},Ve:be,Oc:be,tb:(a,b,c,d)=>T.blendColor(a,b,c,d),sb:a=>T.blendEquation(a),rb:ce,qb:(a,b)=>T.blendFunc(a,b),pb:de,Ye:ee,ob:fe,nb:ge,mb:a=>T.checkFramebufferStatus(a),lb:he,pe:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),qe:(a,b,c)=>{T.clearBufferfv(a,b,y,c>>2)},se:(a,b,c)=>{T.clearBufferiv(a,b,ta,c>>2)},re:(a,b,c)=>{T.clearBufferuiv(a,b,ua,c>>2)},kb:ie,ib:je,hb:a=>T.clearStencil(a),$d:(a,b,c)=>{c=Number(c);return T.clientWaitSync(Nd[a],b,c)},Af:(a,b)=>
{T.Rm.clipControlEXT(a,b)},gb:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},fb:ke,eb:(a,b,c,d,e,f,g,m)=>{T.zj||!g?T.compressedTexImage2D(a,b,c,d,e,f,g,m):T.compressedTexImage2D(a,b,c,d,e,f,w,m,g)},of:(a,b,c,d,e,f,g,m,n)=>{T.zj?T.compressedTexImage3D(a,b,c,d,e,f,g,m,n):T.compressedTexImage3D(a,b,c,d,e,f,g,w,n,m)},db:le,nf:(a,b,c,d,e,f,g,m,n,q,r)=>{T.zj?T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,q,r):T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,w,r,q)},ne:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),cb:(a,
b,c,d,e,f,g,m)=>T.copyTexImage2D(a,b,c,d,e,f,g,m),bb:(a,b,c,d,e,f,g,m)=>T.copyTexSubImage2D(a,b,c,d,e,f,g,m),pf:(a,b,c,d,e,f,g,m,n)=>T.copyTexSubImage3D(a,b,c,d,e,f,g,m,n),ab:me,$a:ne,Za:oe,Ya:pe,Xa:qe,Wa:re,lf:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=W[d];e&&(T.deleteQuery(e),W[d]=null)}},me:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=W[d];e&&(T.Lj.deleteQueryEXT(e),W[d]=null)}},Va:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Hd[d];
e&&(T.deleteRenderbuffer(e),e.name=0,Hd[d]=null)}},Ud:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Ld[d];e&&(T.deleteSampler(e),e.name=0,Ld[d]=null)}},Ua:se,ae:a=>{if(a){var b=Nd[a];b&&(T.deleteSync(b),b.name=0,Nd[a]=null)}},Ta:te,Id:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Md[d];e&&(T.deleteTransformFeedback(e),e.name=0,Md[d]=null)}},Ue:ue,Kc:ue,Sa:ve,Ra:we,Qa:(a,b)=>T.depthRange(a,b),Oa:(a,b)=>{T.detachShader(U[a],V[b])},Na:xe,Ma:ye,La:ze,fe:Ae,cc:Ae,
qd:Ae,xf:Ae,rd:Ae,ef:Ce,uf:Ce,mc:Ce,Ka:De,ee:Ee,Ub:Ee,od:Ee,pd:Ee,vf:Ee,sf:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},Ja:Fe,Ia:Ge,hf:a=>T.endQuery(a),Hd:a=>{T.Lj.endQueryEXT(a)},Pe:()=>T.endTransformFeedback(),de:(a,b)=>(a=T.fenceSync(a,b))?(b=Sd(Nd),a.name=b,Nd[b]=a,b):0,Ha:()=>T.finish(),Ga:()=>T.flush(),Fa:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,Hd[d])},Da:He,We:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,Id[c],d,e)},Ca:Ie,Ba:Je,za:Ke,mf:(a,b)=>{Td(a,b,"createQuery",W)},xe:(a,b)=>{for(var c=
0;c<a;c++){var d=T.Lj.createQueryEXT();if(!d){for(;c<a;)d=4*(b+4*c++>>2),z.setInt32(d,0,!0);break}var e=Sd(W);d.name=e;W[e]=d;z.setInt32(4*(b+4*c>>2),e,!0)}},ya:(a,b)=>{Td(a,b,"createRenderbuffer",Hd)},Vd:(a,b)=>{Td(a,b,"createSampler",Ld)},xa:Le,Gd:(a,b)=>{Td(a,b,"createTransformFeedback",Md)},Te:Me,Ec:Me,Aa:Ne,wa:(a,b,c,d,e,f,g)=>Oe("getActiveAttrib",a,b,c,d,e,f,g),va:Pe,he:(a,b,c,d,e)=>{a=U[a];if(a=T.getActiveUniformBlockName(a,b))e&&0<c?(c=D(a,w,e,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*
(d>>2),0,!0)},ie:(a,b,c,d)=>{a=U[a];if(35393==c)z.setInt32(4*(d>>2),T.getActiveUniformBlockName(a,b).length+1,!0);else if(a=T.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)z.setInt32(4*(d+4*c>>2),a[c],!0);else z.setInt32(4*(d>>2),a,!0)},ke:(a,b,c,d,e)=>{a=U[a];for(var f=[],g=0;g<b;g++)f.push(z.getInt32(4*(c+4*g>>2),!0));if(a=T.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)z.setInt32(4*(e+4*g>>2),a[g],!0)},ua:(a,b,c,d)=>{a=T.getAttachedShaders(U[a]);var e=
a.length;e>b&&(e=b);z.setInt32(4*(c>>2),e,!0);for(b=0;b<e;++b)z.setInt32(4*(d+4*b>>2),V.indexOf(a[b]),!0)},jh:(a,b)=>T.getAttribLocation(U[a],b?C(w,b):""),ih:(a,b)=>Te(a,b,4),Wd:(a,b,c)=>{Qe(c,T.getBufferParameter(a,b))},hh:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getBufferParameter(a,b),!0)},gh:()=>T.getError(),fh:(a,b)=>Te(a,b,2),Ce:(a,b)=>T.getFragDataLocation(U[a],b?C(w,b):""),eh:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=
a.name|0;z.setInt32(4*(d>>2),a,!0)},Xd:(a,b,c)=>Ue(a,b,c,1),Zd:(a,b)=>{Te(a,b,1)},Re:(a,b,c)=>Ue(a,b,c,0),dh:Ve,ud:(a,b,c,d,e)=>{a=T.getInternalformatParameter(a,b,c);if(null!==a)for(b=0;b<a.length&&b<d;++b)z.setInt32(4*(e+4*b>>2),a[b],!0)},Cd:()=>{},bh:We,ch:Xe,ad:Ye,hd:Ze,Wc:Ye,ff:(a,b,c)=>{a=T.getQueryParameter(W[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)},gd:Ze,gf:(a,b,c)=>{z.setInt32(4*(c>>2),T.getQuery(a,b),!0)},md:(a,b,c)=>{c&&(c=4*(c>>2),a=T.Lj.getQueryEXT(a,b),
z.setInt32(c,a,!0))},ah:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getRenderbufferParameter(a,b),!0)},Ld:(a,b,c)=>{z.setFloat32(4*(c>>2),T.getSamplerParameter(Ld[a],b),!0)},Md:(a,b,c)=>{z.setInt32(4*(c>>2),T.getSamplerParameter(Ld[a],b),!0)},Zg:$e,Yg:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);z.setInt32(4*(c>>2),a.rangeMin,!0);z.setInt32(4*(c+4>>2),a.rangeMax,!0);z.setInt32(4*(d>>2),a.precision,!0)},Xg:(a,b,c,d)=>{if(a=T.getShaderSource(V[a]))b=0<b&&d?D(a,w,d,b):0,c&&z.setInt32(4*(c>>2),b,!0)},_g:af,Wg:cf,
oe:df,Yd:(a,b,c,d,e)=>{a=T.getSyncParameter(Nd[a],b);null!==a&&(z.setInt32(4*(e>>2),a,!0),d&&z.setInt32(4*(d>>2),1,!0))},Vg:(a,b,c)=>{c&&z.setFloat32(4*(c>>2),T.getTexParameter(a,b),!0)},Ug:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getTexParameter(a,b),!0)},Le:(a,b,c,d,e,f,g)=>{a=U[a];if(a=T.getTransformFeedbackVarying(a,b))g&&0<c?(c=D(a.name,w,g,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0),e&&z.setInt32(4*(e>>2),a.size,!0),f&&z.setInt32(4*(f>>2),a.type,!0)},je:(a,b)=>T.getUniformBlockIndex(U[a],
b?C(w,b):""),le:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Rb(z.getUint32(4*(c+4*f>>2),!0)));if(a=T.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)z.setInt32(4*(d+4*f>>2),a[f],!0)},Rg:gf,Tg:jf,Sg:kf,De:(a,b,c)=>hf(a,b,c,0),Je:mf,Ie:mf,Ng:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getVertexAttribOffset(a,b),!0)},Pg:(a,b,c)=>{lf(a,b,c,2)},Og:(a,b,c)=>{lf(a,b,c,5)},Mg:(a,b)=>T.hint(a,b),zd:(a,b,c)=>{for(var d=Be[b],e=0;e<b;e++)d[e]=z.getInt32(4*(c+4*e>>2),!0);T.invalidateFramebuffer(a,d)},yd:(a,b,
c,d,e,f,g)=>{for(var m=Be[b],n=0;n<b;n++)m[n]=z.getInt32(4*(c+4*n>>2),!0);T.invalidateSubFramebuffer(a,m,d,e,f,g)},Lg:a=>(a=Fd[a])?T.isBuffer(a):0,Kg:a=>T.isEnabled(a),Jg:a=>(a=Gd[a])?T.isFramebuffer(a):0,Ig:a=>(a=U[a])?T.isProgram(a):0,kf:a=>(a=W[a])?T.isQuery(a):0,be:a=>(a=W[a])?T.Lj.isQueryEXT(a):0,Hg:a=>(a=Hd[a])?T.isRenderbuffer(a):0,Td:a=>(a=Ld[a])?T.isSampler(a):0,Gg:a=>(a=V[a])?T.isShader(a):0,ce:a=>T.isSync(Nd[a]),Fg:a=>(a=Id[a])?T.isTexture(a):0,Fd:a=>T.isTransformFeedback(Md[a]),Se:nf,
vc:nf,Eg:a=>T.lineWidth(a),Dg:of,Ed:()=>T.pauseTransformFeedback(),Cg:pf,zf:(a,b)=>{T.tn.polygonModeWEBGL(a,b)},Bg:(a,b)=>T.polygonOffset(a,b),Bf:(a,b,c)=>{T.Sm.polygonOffsetClampEXT(a,b,c)},Bd:()=>{},Ad:()=>{},wd:(a,b)=>{T.Lj.queryCounterEXT(W[a],b)},tf:qf,Ag:sf,zg:()=>{},yg:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),Xe:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Dd:()=>T.resumeTransformFeedback(),xg:(a,b)=>{T.sampleCoverage(a,!!b)},Od:(a,b,c)=>{T.samplerParameterf(Ld[a],b,c)},Nd:(a,
b,c)=>{c=z.getFloat32(4*(c>>2),!0);T.samplerParameterf(Ld[a],b,c)},Qd:(a,b,c)=>{T.samplerParameteri(Ld[a],b,c)},Pd:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);T.samplerParameteri(Ld[a],b,c)},wg:tf,ug:()=>{},tg:uf,sg:(a,b,c)=>T.stencilFunc(a,b,c),rg:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),qg:a=>T.stencilMask(a),pg:(a,b)=>T.stencilMaskSeparate(a,b),og:(a,b,c)=>T.stencilOp(a,b,c),ng:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),mg:wf,rf:(a,b,c,d,e,f,g,m,n,q)=>{if(T.zj)T.texImage3D(a,b,c,d,e,f,g,m,n,q);else if(q){var r=
rf(n);T.texImage3D(a,b,c,d,e,f,g,m,n,r,q>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,g,m,n,null)},lg:(a,b,c)=>T.texParameterf(a,b,c),jg:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);T.texParameterf(a,b,c)},ig:xf,hg:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);T.texParameteri(a,b,c)},xd:yf,vd:(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),gg:zf,qf:(a,b,c,d,e,f,g,m,n,q,r)=>{if(T.zj)T.texSubImage3D(a,b,c,d,e,f,g,m,n,q,r);else if(r){var t=rf(q);T.texSubImage3D(a,b,c,d,e,f,g,m,n,q,t,r>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,
b,c,d,e,f,g,m,n,q,null)},Me:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Rb(z.getUint32(4*(c+4*f>>2),!0)));T.transformFeedbackVaryings(a,e,d)},fg:(a,b)=>{T.uniform1f(X(a),b)},eg:Af,dg:(a,b)=>{T.uniform1i(X(a),b)},cg:Bf,Be:(a,b)=>{T.uniform1ui(X(a),b)},we:(a,b,c)=>{b&&T.uniform1uiv(X(a),ua,c>>2,b)},bg:(a,b,c)=>{T.uniform2f(X(a),b,c)},ag:Cf,$f:(a,b,c)=>{T.uniform2i(X(a),b,c)},_f:Df,Ae:(a,b,c)=>{T.uniform2ui(X(a),b,c)},ve:(a,b,c)=>{b&&T.uniform2uiv(X(a),ua,c>>2,2*b)},Zf:(a,b,c,d)=>{T.uniform3f(X(a),
b,c,d)},Yf:Ef,Xf:(a,b,c,d)=>{T.uniform3i(X(a),b,c,d)},Wf:Ff,ze:(a,b,c,d)=>{T.uniform3ui(X(a),b,c,d)},ue:(a,b,c)=>{b&&T.uniform3uiv(X(a),ua,c>>2,3*b)},Vf:(a,b,c,d,e)=>{T.uniform4f(X(a),b,c,d,e)},Uf:Gf,Tf:(a,b,c,d,e)=>{T.uniform4i(X(a),b,c,d,e)},Sf:Hf,ye:(a,b,c,d,e)=>{T.uniform4ui(X(a),b,c,d,e)},te:(a,b,c)=>{b&&T.uniform4uiv(X(a),ua,c>>2,4*b)},ge:(a,b,c)=>{a=U[a];T.uniformBlockBinding(a,b,c)},Rf:(a,b,c,d)=>{b&&T.uniformMatrix2fv(X(a),!!c,y,d>>2,4*b)},df:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(X(a),!!c,
y,d>>2,6*b)},bf:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(X(a),!!c,y,d>>2,8*b)},Qf:If,cf:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(X(a),!!c,y,d>>2,6*b)},_e:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(X(a),!!c,y,d>>2,12*b)},Pf:Jf,$e:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(X(a),!!c,y,d>>2,8*b)},Ze:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(X(a),!!c,y,d>>2,12*b)},Of:Kf,Nf:a=>{T.validateProgram(U[a])},Mf:(a,b)=>T.vertexAttrib1f(a,b),Lf:(a,b)=>{T.vertexAttrib1f(a,z.getFloat32(4*(b>>2),!0))},Kf:(a,b,c)=>T.vertexAttrib2f(a,b,c),Jf:(a,
b)=>{T.vertexAttrib2f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0))},If:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),Gf:(a,b)=>{T.vertexAttrib3f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0))},Ff:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),Ef:(a,b)=>{T.vertexAttrib4f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0),z.getFloat32(4*(b+12>>2),!0))},Kd:Lf,Mb:Lf,sd:Lf,yf:Lf,td:Lf,He:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),Fe:(a,
b)=>{T.vertexAttribI4i(a,z.getInt32(4*(b>>2),!0),z.getInt32(4*(b+4>>2),!0),z.getInt32(4*(b+8>>2),!0),z.getInt32(4*(b+12>>2),!0))},Ge:(a,b,c,d,e)=>T.vertexAttribI4ui(a,b,c,d,e),Ee:(a,b)=>{T.vertexAttribI4ui(a,z.getUint32(4*(b>>2),!0),z.getUint32(4*(b+4>>2),!0),z.getUint32(4*(b+8>>2),!0),z.getUint32(4*(b+12>>2),!0))},Ke:Mf,Df:Nf,Cf:Of,_d:(a,b,c)=>{c=Number(c);T.waitSync(Nd[a],b,c)},F:()=>1,Fb:()=>!0,dd:(a,b,c)=>{b={$k:z.getInt32(4*(c>>2),!0),Ek:z.getInt32(4*(c+4>>2),!0),Vl:z.getInt32(4*(c+8>>2),!0),
Pl:b,rk:z.getInt32(4*(c+12>>2),!0),jl:z.getInt32(4*(c+16>>2),!0)};return Pf(a,b)},na:(a,b)=>{a=N(a);return a?a.requestPointerLock?Ec()?Uc(a):b?(Cc(Uc,2,[a]),1):-2:-1:-4},lh:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-xa.buffer.byteLength+65535)/65536|0;try{xa.grow(d);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},_:Qf,aa:(a,b,c)=>"undefined"==typeof onbeforeunload?
-1:1!==c?-5:Rf(a,b),ka:(a,b,c,d)=>Sf(a,b,c,d,12,"blur"),n:Mc,r:(a,b,c)=>{a=N(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},la:(a,b,c,d)=>Sf(a,b,c,d,13,"focus"),ia:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;Tf(a,b,c,d,"webkitfullscreenchange");return Tf(a,b,c,d,"fullscreenchange")},D:(a,b,c)=>Qf()?-1:Uf(a,b,c,26,"gamepadconnected"),C:(a,b,c)=>Qf()?-1:Uf(a,b,c,27,"gamepaddisconnected"),ea:(a,b,c,d)=>Vf(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>Vf(a,b,c,d,
1,"keypress"),da:(a,b,c,d)=>Vf(a,b,c,d,3,"keyup"),M:(a,b,c)=>{wc(()=>dynCall_v(a),b,c)},E:ic,fa:(a,b,c)=>window.screen&&screen.orientation?Wf(a,b,c):-1,ja:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?Xf(a,b,c,d):-4:-1,ha:(a,b,c,d)=>Yf(a,b,c,d),ba:(a,b,c)=>Zf(a,b,c),ga:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?$f(a,b,c,d):-1:-4,fd:a=>document.title=a?C(w,a):"",t:function(a){return vd(()=>new Promise(b=>setTimeout(b,a)))},Eb:function(a,b,c,d,e){function f(v){t?v():uc(v)}var g=a+108,
m=z.getUint32(4*(g+36>>2),!0),n=z.getUint32(4*(g+40>>2),!0),q=z.getUint32(4*(g+44>>2),!0),r=z.getUint32(4*(g+48>>2),!0),t=!!(z.getUint32(4*(g+52>>2),!0)&64);dg(a,v=>{f(()=>{m?dynCall_vi(m,v):b?.(v)})},v=>{f(()=>{n?dynCall_vi(n,v):c?.(v)})},v=>{f(()=>{q?dynCall_vi(q,v):d?.(v)})},v=>{f(()=>{r?dynCall_vi(r,v):e?.(v)})});return a},ld:(a,b)=>{var c=b>>2,d=z.getInt32(4*(c+2),!0);b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+
5],powerPreference:fg[d],failIfMajorPerformanceCaveat:!!u[b+12],sl:z.getInt32(4*(c+4),!0),en:z.getInt32(4*(c+5),!0),Pm:u[b+24],Tl:u[b+25],jn:z.getInt32(4*(c+7),!0),nn:u[b+32]};a=N(a);return!a||b.Tl?0:Vd(a,b)},oa:a=>{Wd==a&&(Wd=0);Wd===Kd[a]&&(Wd=null);"object"==typeof M&&M.qm(Kd[a].Zj.canvas);Kd[a]?.Zj.canvas&&(Kd[a].Zj.canvas.ek=void 0);Kd[a]=null},pa:a=>{Wd=Kd[a];h.ctx=T=Wd?.Zj;return!a||T?0:-5},Uc:(a,b)=>{var c=0,d=0,e;for(e of ig()){var f=b+c;z.setUint32(4*(a+d>>2),f,!0);c+=D(e,w,f,Infinity)+
1;d+=4}return 0},Vc:(a,b)=>{var c=ig();z.setUint32(4*(a>>2),c.length,!0);a=0;for(var d of c)a+=Za(d)+1;z.setUint32(4*(b>>2),a,!0);return 0},u:a=>{na=a;kc(a)},v:function(a){try{var b=L(a);l.close(b);return 0}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return c.ej}},_a:function(a,b){try{var c=L(a);u[b]=c.cj?2:H(c.mode)?3:40960===(c.mode&61440)?7:4;z.setInt16(2*(b+2>>1),0,!0);z.setBigInt64(8*(b+8>>3),BigInt(0),!0);z.setBigInt64(8*(b+16>>3),BigInt(0),!0);return 0}catch(d){if("undefined"==
typeof l||"ErrnoError"!==d.name)throw d;return d.ej}},sa:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var q=l.read(e,u,m,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof f&&(f+=q)}r=b}z.setUint32(4*(d>>2),r,!0);return 0}catch(t){if("undefined"==typeof l||"ErrnoError"!==t.name)throw t;return t.ej}},kg:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=L(a);l.ij(e,b,c);z.setBigInt64(8*(d>>3),BigInt(e.position),!0);e.Rj&&0===b&&0===c&&(e.Rj=null);return 0}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;return f.ej}},ta:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var q=l.write(e,u,m,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof f&&(f+=q)}r=b}z.setUint32(4*(d>>2),r,!0);return 0}catch(t){if("undefined"==typeof l||"ErrnoError"!==
t.name)throw t;return t.ej}},Ob:Xd,tc:Yd,H:Zd,A:$d,O:ae,Ic:be,xc:ce,wc:de,zc:ee,B:fe,Q:ge,Ac:he,Xb:ie,Wb:je,Sb:ke,X:le,uc:me,Vb:ne,Hc:oe,U:pe,Cc:qe,S:re,G:se,V:te,bc:ue,Gc:ve,Pb:we,q:xe,Yb:ye,Lb:ze,Nb:Ae,Bc:Ce,Jb:De,Kb:Ee,p:Fe,ac:Ge,Dc:He,Ib:Ie,Y:Je,Fc:Ke,Mc:Le,dc:Me,Jc:Ne,fc:Pe,k:Ve,gc:We,z:Xe,Rb:$e,P:af,j:cf,I:df,ec:gf,m:jf,y:kf,sc:of,N:pf,T:qf,Qb:sf,Nc:tf,Tb:uf,e:wf,g:xf,Lc:yf,W:zf,rc:Af,nc:Bf,qc:Cf,lc:Df,pc:Ef,kc:Ff,oc:Gf,jc:Hf,ic:If,hc:Jf,yc:Kf,Zb:Lf,_b:Mf,$b:Nf,Hb:Of,K:Hg,f:Ig,x:Jg,w:Kg,L:Lg,
h:Mg,a:Ng,c:Og,d:Pg,o:Qg,zb:Rg,Gb:function(a,b){h.setStatus(a>=b?"":"Prefetching resources… ("+a+"/"+b+")",!0)}};function Jg(a,b,c){var d=O();try{return dynCall_iii(a,b,c)}catch(e){P(d);if(e!==e+0)throw e;zg(1,0)}}function Lg(a,b,c,d,e){var f=O();try{return Gg(a,b,c,d,e)}catch(g){P(f);if(g!==g+0)throw g;zg(1,0)}}function Kg(a,b,c,d){var e=O();try{return Q(a,b,c,d)}catch(f){P(e);if(f!==f+0)throw f;zg(1,0)}}function Hg(a){var b=O();try{return Eg(a)}catch(c){P(b);if(c!==c+0)throw c;zg(1,0)}}
function Og(a,b,c,d){var e=O();try{Bg(a,b,c,d)}catch(f){P(e);if(f!==f+0)throw f;zg(1,0)}}function Ig(a,b){var c=O();try{return Ag(a,b)}catch(d){P(c);if(d!==d+0)throw d;zg(1,0)}}function Qg(a,b,c,d,e,f,g){var m=O();try{Fg(a,b,c,d,e,f,g)}catch(n){P(m);if(n!==n+0)throw n;zg(1,0)}}function Ng(a,b,c){var d=O();try{dynCall_vii(a,b,c)}catch(e){P(d);if(e!==e+0)throw e;zg(1,0)}}function Mg(a,b){var c=O();try{dynCall_vi(a,b)}catch(d){P(c);if(d!==d+0)throw d;zg(1,0)}}
function Pg(a,b,c,d,e){var f=O();try{Cg(a,b,c,d,e)}catch(g){P(f);if(g!==g+0)throw g;zg(1,0)}}function Rg(a,b,c,d,e,f,g,m,n,q){var r=O();try{Dg(a,b,c,d,e,f,g,m,n,q)}catch(t){P(r);if(t!==t+0)throw t;zg(1,0)}}function jg(a=[]){var b=yg;a.unshift(fa);var c=a.length,d=Jc(4*(c+1)),e=d,f;for(f of a){a=4*(e>>2);var g=Kc(f);z.setUint32(a,g,!0);e+=4}z.setUint32(4*(e>>2),0,!0);try{var m=b(c,d);na=m;kc(m);return m}catch(n){return lc(n)}}
function Tg(){function a(){h.calledRun=!0;if(!ma){va=!0;if(!h.noFSInit&&!l.Pk){var b,c;l.Pk=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?l.Jj("/dev","stdin",b):l.wj("/dev/tty","/dev/stdin");c?l.Jj("/dev","stdout",null,c):l.wj("/dev/tty","/dev/stdout");d?l.Jj("/dev","stderr",null,d):l.wj("/dev/tty1","/dev/stderr");l.open("/dev/stdin",0);l.open("/dev/stdout",1);l.open("/dev/stderr",1)}Ug.nh();l.ql=!1;oa?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var d=
h.postRun.shift();Fa.push(d)}Ea(Fa)}}if(0<pb)qb=Tg;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ha();Ea(Ga);0<pb?qb=Tg:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}var Ug;
Ug=await (async function(){function a(c){var d=Ug=c.exports;c={};for(let [e,f]of Object.entries(d))"function"==typeof f?(d=Wc(f),c[e]=d):c[e]=f;c=Ug=c;vg=h._Emscripten_force_free=c.oh;mg=h._SDL_malloc=c.ph;h._SDL_calloc=c.qh;h._SDL_realloc=c.rh;pg=h._SDL_free=c.sh;h._SDLEmscriptenCameraPermissionOutcome=c.th;h._SDLEmscriptenThreadIterate=c.uh;qg=h._Emscripten_HandlePointerEnter=c.vh;rg=h._Emscripten_HandlePointerLeave=c.wh;sg=h._Emscripten_HandlePointerGeneric=c.xh;og=h._Emscripten_HandleMouseButtonUpGlobal=
c.yh;tg=h._Emscripten_SendDragEvent=c.zh;xg=h._Emscripten_SendDragCompleteEvent=c.Ah;ug=h._Emscripten_SendDragTextEvent=c.Bh;wg=h._Emscripten_SendDragFileEvent=c.Ch;ng=h._Emscripten_HandleLockKeysCheck=c.Dh;lg=h._Emscripten_SendSystemThemeChangedEvent=c.Eh;kg=h._requestFullscreenThroughSDL=c.Fh;h._vfs_sync_callback=c.Gh;yg=h._main=c.Hh;h._SDL_main=c.Ih;gb=c.Jh;pd=c.Kh;ud=c.Lh;eg=c.Mh;zg=c.Nh;cd=c.Oh;P=c.Ph;Jc=c.Qh;O=c.Rh;Q=B.iiii=c.Th;B.iidiiii=c.Uh;dynCall_vii=B.vii=c.Vh;B.jiji=c.Wh;Ag=B.ii=c.Xh;
dynCall_vi=B.vi=c.Yh;Bg=B.viii=c.Zh;B.vffff=c._h;Cg=B.viiii=c.$h;B.vf=c.ai;B.viiiiiiii=c.bi;Dg=B.viiiiiiiii=c.ci;Eg=B.i=c.di;B.vff=c.ei;dynCall_v=B.v=c.fi;B.viiiii=c.gi;B.viiiiiii=c.hi;dynCall_iii=B.iii=c.ii;B.vfi=c.ji;B.viif=c.ki;B.vif=c.li;B.viff=c.mi;B.vifff=c.ni;B.viffff=c.oi;Fg=B.viiiiii=c.pi;B.vfff=c.qi;B.viiiiiiiiii=c.ri;B.viiiiiiiiiii=c.si;B.viifi=c.ti;B.iiij=c.ui;B.viij=c.vi;Gg=B.iiiii=c.wi;B.viiifi=c.xi;B.ji=c.yi;B.iiiiii=c.zi;B.iiiiiiiiiiii=c.Ai;B.iiiiiii=c.Bi;B.vd=c.Ci;B.iiji=c.Di;B.viidi=
c.Ei;B.ff=c.Fi;B.iiif=c.Gi;B.iiiiiiiii=c.Hi;B.viiif=c.Ii;B.iiiiiiii=c.Ji;B.iiiiiiiiii=c.Ki;B.iiidd=c.Li;B.id=c.Mi;B.dd=c.Ni;B.d=c.Oi;B.iid=c.Pi;B.di=c.Qi;B.dii=c.Ri;sd=c.Si;Zc=c.Ti;dd=c.Ui;td=c.Vi;xa=c.mh;ea=c.Sh;wa();return Ug}var b={a:Sg};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});za??=h.locateFile?h.locateFile("taisei-dev.wasm",ha):ha+"taisei-dev.wasm";return a((await Ca(b)).instance)}());Tg();gg.TAISEI_NOASYNC="1";gg.TAISEI_NOUNLOAD="1";
gg.TAISEI_PREFER_SDL_VIDEODRIVERS="emscripten";gg.TAISEI_RENDERER="gles30";va?moduleRtn=h:moduleRtn=new Promise((a,b)=>{oa=a;pa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createTaisei;module.exports.default=createTaisei}else if(typeof define==="function"&&define["amd"])define([],()=>createTaisei);
