var createTaisei=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg;h.totalDependencies=0;h.monitorRunDependencies=function(a){h.totalDependencies=Math.max(h.totalDependencies,a);h.setStatus(a?"Preparing… ("+(h.totalDependencies-a)+"/"+h.totalDependencies+")":"All downloads complete.")};h.initFilesystem=function(){k("/persistent");l.aj(p,{},"/persistent")};var ba=h.preinitializedWebGLContext;ba.getSupportedExtensions().forEach(function(a){ba.getExtension(a)});
function ca(a,b){l.nk(a,function(c){h.ccall("vfs_sync_callback",null,["boolean","string","number"],[a,c,b],{async:!0})})}"undefined"===typeof da&&(da=h.dynCall=function(a,b,c){return ea.get(b).apply(this,c)});var fa="./this.program",ha="",ia;try{ha=(new URL(".",_scriptName)).href}catch{}ia=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var ja=console.log.bind(console),ka=console.error.bind(console),la,ma=!1,na,oa,pa,u,w,qa,sa,ta,ua,y,z,va=!1;function wa(){var a=xa.buffer;u=new Int8Array(a);qa=new Int16Array(a);w=new Uint8Array(a);sa=new Uint16Array(a);ta=new Int32Array(a);ua=new Uint32Array(a);y=new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a);z=new DataView(a);ya()}
function A(a){h.onAbort?.(a);a="Aborted("+a+")";ka(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");pa?.(a);throw a;}var za;async function Aa(a){if(!la)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==za&&la)a=new Uint8Array(la);else throw"both async and sync fetching of the wasm failed";return a}async function Ba(a,b){try{var c=await Aa(a);return await WebAssembly.instantiate(c,b)}catch(d){ka(`failed to asynchronously prepare wasm: ${d}`),A(d)}}
async function Ca(a){var b=za;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){ka(`wasm streaming compile failed: ${d}`),ka("falling back to ArrayBuffer instantiation")}return Ba(b,a)}class Da{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ea=a=>{for(;0<a.length;)a.shift()(h)},Fa=[],Ga=[],Ha=()=>{var a=h.preRun.shift();Ga.push(a)},Ia=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},B={},da=(a,b,c=[])=>{a=a.replace(/p/g,"i");return(0,B[a])(b,...c)},Ja=!0;
function Ka(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":u[a]=b;break;case "i8":u[a]=b;break;case "i16":z.setInt16(2*(a>>1),b,!0);break;case "i32":z.setInt32(4*(a>>2),b,!0);break;case "i64":z.setBigInt64(8*(a>>3),BigInt(b),!0);break;case "float":z.setFloat32(4*(a>>2),b,!0);break;case "double":z.setFloat64(8*(a>>3),b,!0);break;case "*":z.setUint32(4*(a>>2),b,!0);break;default:A(`invalid type for setValue: ${c}`)}}
var Ma=()=>{var a=z.getInt32(4*(+La>>2),!0);La+=4;return a},Oa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Pa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Oa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Qa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Ra=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Sa=(a,b)=>Pa(a+"/"+b),Ta=()=>a=>crypto.getRandomValues(a),Ua=a=>{(Ua=Ta())(a)},Va=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:l.sk();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Oa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Wa=(a,b)=>{function c(g){for(var m=0;m<g.length&&""===g[m];m++);for(var n=
g.length-1;0<=n&&""===g[n];n--);return m>n?[]:g.slice(m,n-m+1)}a=Va(a).slice(1);b=Va(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Xa=globalThis.TextDecoder&&new TextDecoder,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;
if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Ya=[],Za=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);
if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},$a=a=>{var b=Array(Za(a)+1);a=D(a,b,0,b.length);b.length=a;return b},ab=[];function bb(a,b){ab[a]={input:[],output:[],Gj:b};cb(a,db)}
var db={open(a){var b=ab[a.node.mk];if(!b)throw new l.Vi(43);a.bj=b;a.seekable=!1},close(a){a.bj.Gj.wk(a.bj)},wk(a){a.bj.Gj.wk(a.bj)},read(a,b,c,d){if(!a.bj||!a.bj.Gj.ol)throw new l.Vi(60);for(var e=0,f=0;f<d;f++){try{var g=a.bj.Gj.ol(a.bj)}catch(m){throw new l.Vi(29);}if(void 0===g&&0===e)throw new l.Vi(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.Ej=Date.now());return e},write(a,b,c,d){if(!a.bj||!a.bj.Gj.Yk)throw new l.Vi(60);try{for(var e=0;e<d;e++)a.bj.Gj.Yk(a.bj,b[c+e])}catch(f){throw new l.Vi(29);
}d&&(a.node.fj=a.node.kj=Date.now());return e}},eb={ol(){a:{if(!Ya.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ya=$a(a)}a=Ya.shift()}return a},Yk(a,b){null===b||10===b?(ja(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},wk(a){0<a.output?.length&&(ja(C(a.output)),a.output=[])},dm(){return{Em:25856,Gm:5,Dm:191,Fm:35387,Cm:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},em(){return 0},fm(){return[24,
80]}},fb={Yk(a,b){null===b||10===b?(ka(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},wk(a){0<a.output?.length&&(ka(C(a.output)),a.output=[])}},hb=a=>{a=65536*Math.ceil(a/65536);var b=gb(65536,a);b&&w.fill(0,b,b+a);return b},F={Aj:null,aj(){return F.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=24576===(c&61440))||(e=4096===(c&61440));if(e)throw new l.Vi(63);F.Aj||(F.Aj={dir:{node:{pj:F.Wi.pj,tj:F.Wi.tj,Sj:F.Wi.Sj,qj:F.Wi.qj,Wj:F.Wi.Wj,Cj:F.Wi.Cj,Bj:F.Wi.Bj,Mj:F.Wi.Mj,vj:F.Wi.vj},
stream:{hj:F.Xi.hj}},file:{node:{pj:F.Wi.pj,tj:F.Wi.tj},stream:{hj:F.Xi.hj,read:F.Xi.read,write:F.Xi.write,Uj:F.Xi.Uj,ak:F.Xi.ak}},link:{node:{pj:F.Wi.pj,tj:F.Wi.tj,Nj:F.Wi.Nj},stream:{}},jl:{node:{pj:F.Wi.pj,tj:F.Wi.tj},stream:l.Il}});c=l.createNode(a,b,c,d);H(c.mode)?(c.Wi=F.Aj.dir.node,c.Xi=F.Aj.dir.stream,c.Zi={}):l.isFile(c.mode)?(c.Wi=F.Aj.file.node,c.Xi=F.Aj.file.stream,c.ij=0,c.Zi=F.Ql??(F.Ql=new Uint8Array(0))):40960===(c.mode&61440)?(c.Wi=F.Aj.link.node,c.Xi=F.Aj.link.stream):8192===(c.mode&
61440)&&(c.Wi=F.Aj.jl.node,c.Xi=F.Aj.jl.stream);c.Ej=c.fj=c.kj=Date.now();a&&(a.Zi[b]=c,a.Ej=a.fj=a.kj=c.Ej);return c},Wi:{pj(a){var b={};b.Pl=8192===(a.mode&61440)?a.id:1;b.cm=a.id;b.mode=a.mode;b.km=1;b.uid=0;b.$l=0;b.mk=a.mk;H(a.mode)?b.size=4096:l.isFile(a.mode)?b.size=a.ij:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ej=new Date(a.Ej);b.fj=new Date(a.fj);b.kj=new Date(a.kj);b.Gl=4096;b.hl=Math.ceil(b.size/b.Gl);return b},tj(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&
(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ij!=b&&(c=a.Zi,a.Zi=new Uint8Array(b),a.Zi.set(c.subarray(0,Math.min(b,a.ij))),a.ij=b))},Sj(){F.Gk||(F.Gk=new l.Vi(44),F.Gk.stack="<generic error, no stack>");throw F.Gk;},qj(a,b,c,d){return F.createNode(a,b,c,d)},Wj(a,b,c){try{var d=ib(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Zi)throw new l.Vi(55);jb(d)}delete a.parent.Zi[a.name];b.Zi[c]=a;a.name=c;b.kj=b.fj=a.parent.kj=a.parent.fj=Date.now()},Cj(a,b){delete a.Zi[b];a.kj=a.fj=Date.now()},Bj(a,b){var c=
ib(a,b),d;for(d in c.Zi)throw new l.Vi(55);delete a.Zi[b];a.kj=a.fj=Date.now()},Mj(a){return[".","..",...Object.keys(a.Zi)]},vj(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},Nj(a){if(40960!==(a.mode&61440))throw new l.Vi(28);return a.link}},Xi:{read(a,b,c,d,e){if(e>=a.node.ij)return 0;d=Math.min(a.node.ij-e,d);b.set(a.node.Zi.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.fj=a.kj=Date.now();if(f)a.Zi=b.subarray(c,c+d),a.ij=d;else if(0===
a.ij&&0===e)a.Zi=b.slice(c,c+d),a.ij=d;else{f=e+d;var g=a.Zi.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.Zi.subarray(0,a.ij),a.Zi=new Uint8Array(f),a.Zi.set(g));a.Zi.set(b.subarray(c,c+d),e);a.ij=Math.max(a.ij,e+d)}return d},hj(a,b,c){1===c?b+=a.position:2===c&&l.isFile(a.node.mode)&&(b+=a.node.ij);if(0>b)throw new l.Vi(28);return b},Uj(a,b,c,d,e){if(!l.isFile(a.node.mode))throw new l.Vi(43);a=a.node.Zi;if(e&2||a.buffer!==u.buffer){d=!0;e=hb(b);if(!e)throw new l.Vi(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{ul:e,Hj:d}},ak(a,b,c,d){F.Xi.write(a,b,0,d,c,!1);return 0}}},kb=a=>{"string"==typeof a&&(a=$a(a));a.subarray||(a=new Uint8Array(a));return a},lb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},p={tk:{},indexedDB:()=>indexedDB,yl:21,Pj:"FILE_DATA",bk:a=>{function b(){"again"===a.Rj?c():a.Rj=0}function c(){a.Rj="idb";p.nk(a,!1,b)}a.Rj?"idb"===a.Rj&&(a.Rj="again"):
a.Rj=setTimeout(c,0)},aj:a=>{var b=F.aj(a);if(a?.sl?.xm){a.Rj=0;var c=b.Wi;b.Wi={...b.Wi};b.Wi.qj=(d,e,f,g)=>{var m=c.qj(d,e,f,g);m.Wi=b.Wi;m.am=b.aj;m.Uk=m.Xi;m.Xi={...m.Xi};m.Xi.write=(n,q,r,t,v,E)=>{n.node.ql=!0;return m.Uk.write(n,q,r,t,v,E)};m.Xi.close=n=>{var q=n.node;q.ql&&(p.bk(q.am),q.ql=!1);if(q.Uk.close)return q.Uk.close(n)};p.bk(b.aj);return m};b.Wi.Bj=(...d)=>(p.bk(b.aj),c.Bj(...d));b.Wi.vj=(...d)=>(p.bk(b.aj),c.vj(...d));b.Wi.Cj=(...d)=>(p.bk(b.aj),c.Cj(...d));b.Wi.Wj=(...d)=>(p.bk(b.aj),
c.Wj(...d))}return b},nk:(a,b,c)=>{p.Xl(a,(d,e)=>{if(d)return c(d);p.Yl(a,(f,g)=>{if(f)return c(f);p.om(b?g:e,b?e:g,c)})})},nm:()=>{for(var a of Object.values(p.tk))a.close();p.tk={}},Vl:(a,b)=>{var c=p.tk[a];if(c)return b(null,c);try{var d=p.indexedDB().open(a,p.yl)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(p.Pj)?g=e.objectStore(p.Pj):g=f.createObjectStore(p.Pj);g.indexNames.contains("timestamp")||
g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;p.tk[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},Xl:(a,b)=>{function c(m){return"."!==m&&".."!==m}function d(m){return n=>Pa(m+"/"+n)}var e={};for(a=l.Mj(a.kk).filter(c).map(d(a.kk));a.length;){var f=a.pop();try{var g=l.stat(f,!0)}catch(m){return b(m)}H(g.mode)&&a.push(...l.Mj(f).filter(c).map(d(f)));e[f]={timestamp:g.fj}}return b(null,{type:"local",entries:e})},Yl:(a,b)=>{var c={};p.Vl(a.kk,(d,
e)=>{if(d)return b(d);try{var f=e.transaction([p.Pj],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(p.Pj).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},im:(a,b)=>{try{var c=I(a).node;var d=l.stat(a,!0)}catch(e){return b(e)}return H(d.mode)?b(null,{timestamp:d.fj,mode:d.mode}):40960===(d.mode&61440)?b(null,{timestamp:d.fj,mode:d.mode,
link:c.link}):l.isFile(d.mode)?(c.Zi=c.Zi.subarray(0,c.ij),b(null,{timestamp:d.fj,mode:d.mode,contents:c.Zi})):b(Error("node type not supported"))},tm:(a,b,c)=>{try{if(H(b.mode)){var d=b.mode,e=a.split("/"),f="",g;for(g of e)if(g){if(f||"/"===a.charAt(0))f+="/";f+=g;try{k(f,d)}catch(t){if(20!=t.dj)throw t;}}}else if(40960===(b.mode&61440))l.vj(b.link,a);else if(l.isFile(b.mode)){f=b.contents;d={Hl:!0};d.flags=d.flags||577;var m=l.open(a,d.flags,d.mode);f=kb(f);l.write(m,f,0,f.byteLength,void 0,d.Hl);
l.close(m)}else return c(Error("node type not supported"));mb(a,b.mode);var n=b.timestamp,q=b.timestamp,r=I(a,{oj:!0}).node;nb(r.Wi.tj,63)(r,{Ej:n,fj:q})}catch(t){return c(t)}c(null)},qm:(a,b)=>{try{var c=l.stat(a,!0);H(c.mode)?l.Bj(a):l.Cj(a)}catch(d){return b(d)}b(null)},jm:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},um:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},
rm:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},om:(a,b,c)=>{function d(v){if(v&&!q)return q=!0,c(v)}var e=0,f=[],g;for([g,n]of Object.entries(a.entries)){var m=b.entries[g];m&&n.timestamp.getTime()==m.timestamp.getTime()||(f.push(g),e++)}var n=[];for(g of Object.keys(b.entries))a.entries[g]||(n.push(g),e++);if(!e)return c(null);var q=!1;a=("remote"===a.type?a.db:b.db).transaction([p.Pj],"readwrite");var r=a.objectStore(p.Pj);a.onerror=a.onabort=
v=>{d(v.target.error);v.preventDefault()};a.oncomplete=()=>{q||c(null)};for(const v of f.sort())"local"===b.type?p.jm(r,v,(E,G)=>{if(E)return d(E);p.tm(v,G,d)}):p.im(v,(E,G)=>{if(E)return d(E);p.um(r,v,G,d)});for(var t of n.sort().reverse())"local"===b.type?p.qm(t,d):p.rm(r,t,d)}},ob=async a=>{a=await ia(a);return new Uint8Array(a)},pb=0,qb=null,rb=()=>{pb--;h.monitorRunDependencies?.(pb);if(0==pb&&qb){var a=qb;qb=null;a()}},sb=()=>{pb++;h.monitorRunDependencies?.(pb)},tb=[],wb=async(a,b)=>{"undefined"!=
typeof ub&&vb();for(var c of tb)if(c.canHandle(b))return c.handle(a,b);return a},yb=async(a,b,c,d,e,f,g,m)=>{var n=b?Va(Pa(a+"/"+b)):a,q=`cp ${n}`;sb(q);try{var r=c;"string"==typeof c&&(r=await ob(c));r=await wb(r,n);m?.();f||xb(a,b,r,d,e,g)}finally{rb(q)}};function k(a,b=511){return l.qj(a,b&1023|16384,0)}function cb(a,b){l.ll[a]={Xi:b}}function H(a){return 16384===(a&61440)}
function ib(a,b){var c=H(a.mode)?(c=zb(a,"x"))?c:a.Wi.Sj?0:2:54;if(c)throw new l.Vi(c);for(c=l.Fj[Ab(a.id,b)];c;c=c.Vj){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return l.Sj(a,b)}function jb(a){var b=Ab(a.parent.id,a.name);if(l.Fj[b]===a)l.Fj[b]=a.Vj;else for(b=l.Fj[b];b;){if(b.Vj===a){b.Vj=a.Vj;break}b=b.Vj}}
function I(a,b={}){if(!a)throw new l.Vi(44);b.vk??(b.vk=!0);"/"===a.charAt(0)||(a=l.sk()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=l.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Qa(e),l.Qk(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Pa(e+"/"+a[f]);try{d=ib(d,a[f])}catch(m){if(44===m?.dj&&g&&b.lm)return{path:e};throw m;}!d.rj||g&&!b.vk||(d=d.rj.root);if(40960===(d.mode&61440)&&(!g||
b.oj)){if(!d.Wi.Nj)throw new l.Vi(52);d=d.Wi.Nj(d);"/"===d.charAt(0)||(d=Qa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new l.Vi(32);}function mb(a,b,c){a="string"==typeof a?I(a,{oj:!c}).node:a;Bb(null,a,b,c)}function xb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Cb(a),g=b?Pa(a+"/"+b):a);a=lb(d,e);g=l.create(g,a);c&&(c=kb(c),mb(g,a|146),b=l.open(g,577),l.write(b,c,0,c.length,0,f),l.close(b),mb(g,a))}
function Cb(a){for(var b;;){if(l.Qk(a))return a=a.aj.kk,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%l.Fj.length}function Db(a){var b=Ab(a.parent.id,a.name);a.Vj=l.Fj[b];l.Fj[b]=a}function zb(a,b){return l.pl?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}
function Eb(a,b){if(!H(a.mode))return 54;try{return ib(a,b),20}catch(c){}return zb(a,"wx")}function Fb(a,b,c){try{var d=ib(a,b)}catch(e){return e.dj}if(a=zb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(l.Qk(d)||Cb(d)===l.sk())return 10}else if(H(d.mode))return 31;return 0}function nb(a,b){if(!a)throw new l.Vi(b);return a}function L(a){a=l.Zl(a);if(!a)throw new l.Vi(8);return a}
function Gb(a,b=-1){a=Object.assign(new l.Al,a);if(-1==b)a:{for(b=0;b<=l.Bl;b++)if(!l.streams[b])break a;throw new l.Vi(33);}a.fd=b;return l.streams[b]=a}function Hb(a,b=-1){a=Gb(a,b);a.Xi?.Nm?.(a);return a}function Ib(a,b,c){var d=a?.Xi.tj;a=d?a:b;d??=b.Wi.tj;nb(d,63);d(a,c)}function Jb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.lk)}return b}
function Kb(a){var b={Bm:4096,Wm:4096,hl:1E6,Am:5E5,zm:5E5,files:l.Vk,Um:l.Vk-1,Xm:42,flags:2,fn:255};a.Wi.vl&&Object.assign(b,a.Wi.vl(a.aj.sl.root));return b}function Lb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return l.qj(a,b|8192,c)}function Bb(a,b,c,d){Ib(a,b,{mode:c&4095|b.mode&-4096,kj:Date.now(),ml:d})}function Mb(a,b,c){if(H(b.mode))throw new l.Vi(31);if(!l.isFile(b.mode))throw new l.Vi(28);var d=zb(b,"w");if(d)throw new l.Vi(d);Ib(a,b,{size:c,timestamp:Date.now()})}
function Nb(a,b){a="string"==typeof a?a:Cb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Pa(a+"/"+c);try{k(d)}catch(e){if(20!=e.dj)throw e;}a=d}}return d}function Ob(a,b,c,d){a="string"==typeof a?a:Cb(a);b=Pa(a+"/"+b);return l.create(b,lb(c,d))}
function Pb(a){if(!(a.gm||a.hm||a.link||a.Zi))if(globalThis.XMLHttpRequest)A("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Zi=(void 0)(a.url)}catch(b){throw new l.Vi(29);}}
function Qb(a,b,c,d,e){function f(r,t,v,E,G){r=r.node.Zi;if(G>=r.length)return 0;E=Math.min(r.length-G,E);if(r.slice)for(var J=0;J<E;J++)t[v+J]=r[G+J];else for(J=0;J<E;J++)t[v+J]=r.get(G+J);return E}class g{Dj=!1;$i=[];gj=void 0;ek=0;$j=0;get(r){if(!(r>this.length-1||0>r)){var t=r%this.fk;return this.gj(r/this.fk|0)[t]}}Fl(r){this.gj=r}ck(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);200<=r.status&&300>r.status||304===r.status||A("Couldn't load "+c+". Status: "+r.status);var t=Number(r.getResponseHeader("Content-length")),
v,E=(v=r.getResponseHeader("Accept-Ranges"))&&"bytes"===v;r=(v=r.getResponseHeader("Content-Encoding"))&&"gzip"===v;var G=1048576;E||(G=t);var J=this;J.Fl(P=>{var Z=P*G,aa=(P+1)*G-1;aa=Math.min(aa,t-1);if("undefined"==typeof J.$i[P]){var ra=J.$i;Z>aa&&A("invalid range ("+Z+", "+aa+") or no bytes requested!");aa>t-1&&A("only "+t+" bytes available! programmer error!");var x=new XMLHttpRequest;x.open("GET",c,!1);t!==G&&x.setRequestHeader("Range","bytes="+Z+"-"+aa);x.responseType="arraybuffer";x.overrideMimeType&&
x.overrideMimeType("text/plain; charset=x-user-defined");x.send(null);200<=x.status&&300>x.status||304===x.status||A("Couldn't load "+c+". Status: "+x.status);Z=void 0!==x.response?new Uint8Array(x.response||[]):$a(x.responseText||"");ra[P]=Z}"undefined"==typeof J.$i[P]&&A("doXHR failed!");return J.$i[P]});if(r||!t)G=t=1,G=t=this.gj(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.ek=t;this.$j=G;this.Dj=!0}get length(){this.Dj||this.ck();return this.ek}get fk(){this.Dj||
this.ck();return this.$j}}if(globalThis.XMLHttpRequest){A("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var m=new g;var n=void 0}else n=c,m=void 0;var q=Ob(a,b,d,e);m?q.Zi=m:n&&(q.Zi=null,q.url=n);Object.defineProperties(q,{ij:{get:function(){return this.Zi.length}}});a={};for(const [r,t]of Object.entries(q.Xi))a[r]=(...v)=>{Pb(q);return t(...v)};a.read=(r,t,v,E,G)=>{Pb(q);return f(r,t,v,E,G)};a.Uj=(r,t,v)=>{Pb(q);var E=hb(t);
if(!E)throw new l.Vi(48);f(r,u,E,t,v);return{ul:E,Hj:!0}};q.Xi=a;return q}
var l={root:null,lk:[],ll:{},streams:[],Vk:1,Fj:null,kl:"/",Ok:!1,pl:!0,Tl:null,Bk:0,Vi:class{name="ErrnoError";constructor(a){this.dj=a}},Al:class{$i={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.$i.flags}set flags(a){this.$i.flags=a}get position(){return this.$i.position}set position(a){this.$i.position=a}},zl:class{Wi={};Xi={};rj=null;constructor(a,b,c,d){a||=this;this.parent=a;this.aj=a.aj;this.id=l.Vk++;this.name=b;this.mode=c;this.mk=d;this.Ej=
this.fj=this.kj=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get hm(){return H(this.mode)}get gm(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new l.zl(a,b,c,d);Db(a);return a},Qk(a){return a===a.parent},isFile(a){return 32768===(a&61440)},$m(a){return 49152===(a&49152)},Bl:4096,Zl:a=>l.streams[a],Il:{open(a){a.Xi=l.Wl(a.node.mk).Xi;a.Xi.open?.(a)},
hj(){throw new l.Vi(70);}},Sk:a=>a>>8,cn:a=>a&255,Tj:(a,b)=>a<<8|b,Wl:a=>l.ll[a],nk(a,b){function c(m){l.Bk--;return b(m)}function d(m){if(m){if(!d.Rl)return d.Rl=!0,c(m)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);l.Bk++;1<l.Bk&&ka(`warning: ${l.Bk} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Jb(l.root.aj),f=0,g;for(g of e)g.type.nk?g.type.nk(g,a,d):d(null)},aj(a,b,c){var d="/"===c;if(d&&l.root)throw new l.Vi(10);if(!d&&c){var e=I(c,{vk:!1});c=e.path;
e=e.node;if(e.rj)throw new l.Vi(10);if(!H(e.mode))throw new l.Vi(54);}b={type:a,sl:b,kk:c,lk:[]};a=a.aj(b);a.aj=b;b.root=a;d?l.root=a:e&&(e.rj=b,e.aj&&e.aj.lk.push(b));return a},rn(a){a=I(a,{vk:!1});if(!a.node.rj)throw new l.Vi(28);a=a.node;var b=a.rj,c=Jb(b);for([,e]of Object.entries(l.Fj))for(;e;){var d=e.Vj;c.includes(e.aj)&&jb(e);var e=d}a.rj=null;a.aj.lk.splice(a.aj.lk.indexOf(b),1)},Sj(a,b){return a.Wi.Sj(a,b)},qj(a,b,c){var d=I(a,{parent:!0}).node;a=Ra(a);if(!a)throw new l.Vi(28);if("."===
a||".."===a)throw new l.Vi(20);var e=Eb(d,a);if(e)throw new l.Vi(e);if(!d.Wi.qj)throw new l.Vi(63);return d.Wi.qj(d,a,b,c)},vl(a){return Kb(I(a,{oj:!0}).node)},nn(a){return Kb(a.node)},create(a,b=438){return l.qj(a,b&4095|32768,0)},vj(a,b){if(!Va(a))throw new l.Vi(44);var c=I(b,{parent:!0}).node;if(!c)throw new l.Vi(44);b=Ra(b);var d=Eb(c,b);if(d)throw new l.Vi(d);if(!c.Wi.vj)throw new l.Vi(63);return c.Wi.vj(c,b,a)},Wj(a,b){var c=Qa(a),d=Qa(b),e=Ra(a),f=Ra(b);var g=I(a,{parent:!0});var m=g.node;
g=I(b,{parent:!0});g=g.node;if(!m||!g)throw new l.Vi(44);if(m.aj!==g.aj)throw new l.Vi(75);var n=ib(m,e);a=Wa(a,d);if("."!==a.charAt(0))throw new l.Vi(28);a=Wa(b,c);if("."!==a.charAt(0))throw new l.Vi(55);try{var q=ib(g,f)}catch(r){}if(n!==q){b=H(n.mode);if(e=Fb(m,e,b))throw new l.Vi(e);if(e=q?Fb(g,f,b):Eb(g,f))throw new l.Vi(e);if(!m.Wi.Wj)throw new l.Vi(63);if(n.rj||q&&q.rj)throw new l.Vi(10);if(g!==m&&(e=zb(m,"w")))throw new l.Vi(e);jb(n);try{m.Wi.Wj(n,g,f),n.parent=g}catch(r){throw r;}finally{Db(n)}}},
Bj(a){var b=I(a,{parent:!0}).node;a=Ra(a);var c=ib(b,a),d=Fb(b,a,!0);if(d)throw new l.Vi(d);if(!b.Wi.Bj)throw new l.Vi(63);if(c.rj)throw new l.Vi(10);b.Wi.Bj(b,a);jb(c)},Mj(a){a=I(a,{oj:!0}).node;return nb(a.Wi.Mj,54)(a)},Cj(a){var b=I(a,{parent:!0}).node;if(!b)throw new l.Vi(44);a=Ra(a);var c=ib(b,a),d=Fb(b,a,!1);if(d)throw new l.Vi(d);if(!b.Wi.Cj)throw new l.Vi(63);if(c.rj)throw new l.Vi(10);b.Wi.Cj(b,a);jb(c)},Nj(a){a=I(a).node;if(!a)throw new l.Vi(44);if(!a.Wi.Nj)throw new l.Vi(28);return a.Wi.Nj(a)},
stat(a,b){a=I(a,{oj:!b}).node;return nb(a.Wi.pj,63)(a)},an(a,b){mb(a,b,!0)},Sm(a,b){a=L(a);Bb(a,a.node,b,!1)},bn(a){a="string"==typeof a?I(a,{oj:!1}).node:a;Ib(null,a,{timestamp:Date.now(),ml:!0})},Tm(a){a=L(a);Ib(a,a.node,{timestamp:Date.now(),ml:!1})},truncate(a,b){if(0>b)throw new l.Vi(28);a="string"==typeof a?I(a,{oj:!0}).node:a;Mb(null,a,b)},Ym(a,b){a=L(a);if(0>b||0===(a.flags&2097155))throw new l.Vi(28);Mb(a,a.node,b)},open(a,b,c=438){if(""===a)throw new l.Vi(44);if("string"==typeof b){var d=
{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=I(a,{oj:!(b&131072),lm:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new l.Vi(20);}else{if(e)throw new l.Vi(31);d=l.qj(a,c|511,0);f=!0}if(!d)throw new l.Vi(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new l.Vi(54);if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&
3],b&512&&(e+="w"),e=H(d.mode)&&("r"!==e||b&576)?31:zb(d,e)):e=44,e))throw new l.Vi(e);b&512&&!f&&l.truncate(d,0);b&=-131713;b=Gb({node:d,path:Cb(d),flags:b,seekable:!0,position:0,Xi:d.Xi,vm:[],error:!1});b.Xi.open&&b.Xi.open(b);f&&mb(d,c&511);return b},close(a){if(null===a.fd)throw new l.Vi(8);a.Qj&&(a.Qj=null);try{a.Xi.close&&a.Xi.close(a)}catch(b){throw b;}finally{l.streams[a.fd]=null}a.fd=null},hj(a,b,c){if(null===a.fd)throw new l.Vi(8);if(!a.seekable||!a.Xi.hj)throw new l.Vi(70);if(0!=c&&1!=
c&&2!=c)throw new l.Vi(28);a.position=a.Xi.hj(a,b,c);a.vm=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new l.Vi(28);if(null===a.fd)throw new l.Vi(8);if(1===(a.flags&2097155))throw new l.Vi(8);if(H(a.node.mode))throw new l.Vi(31);if(!a.Xi.read)throw new l.Vi(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new l.Vi(70);b=a.Xi.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new l.Vi(28);if(null===a.fd)throw new l.Vi(8);if(0===
(a.flags&2097155))throw new l.Vi(8);if(H(a.node.mode))throw new l.Vi(31);if(!a.Xi.write)throw new l.Vi(28);a.seekable&&a.flags&1024&&l.hj(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new l.Vi(70);b=a.Xi.write(a,b,c,d,e,f);g||(a.position+=b);return b},Uj(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new l.Vi(2);if(1===(a.flags&2097155))throw new l.Vi(2);if(!a.Xi.Uj)throw new l.Vi(43);if(!b)throw new l.Vi(28);return a.Xi.Uj(a,b,c,d,e)},ak(a,b,c,d,
e){return a.Xi.ak?a.Xi.ak(a,b,c,d,e):0},Pk(a,b,c){if(!a.Xi.Pk)throw new l.Vi(59);return a.Xi.Pk(a,b,c)},jn(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&A(`Invalid encoding type "${b.encoding}"`);var c=l.open(a,b.flags);a=l.stat(a).size;var d=new Uint8Array(a);l.read(c,d,0,a,0);"utf8"===b.encoding&&(d=C(d));l.close(c);return d},sk:()=>l.kl,Hm(a){a=I(a,{oj:!0});if(null===a.node)throw new l.Vi(44);if(!H(a.node.mode))throw new l.Vi(54);var b=zb(a.node,
"x");if(b)throw new l.Vi(b);l.kl=a.path},nm(){l.Ok=!1;for(var a of l.streams)a&&l.close(a)},Vm(a,b){try{var c=I(a,{oj:!b});a=c.path}catch(f){}var d=!1,e=null;try{c=I(a,{parent:!0}),Ra(a),c=I(a,{oj:!b}),d=!0,e=c.node}catch(f){}return d?e:null},Ij(a,b,c,d){a=Sa("string"==typeof a?a:Cb(a),b);b=lb(!!c,!!d);var e;(e=l.Ij).Sk??(e.Sk=64);e=l.Tj(l.Ij.Sk++,0);cb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var q=0,r=0;r<n;r++){try{var t=c()}catch(v){throw new l.Vi(29);}if(void 0===
t&&0===q)throw new l.Vi(6);if(null===t||void 0===t)break;q++;g[m+r]=t}q&&(f.node.Ej=Date.now());return q},write(f,g,m,n){for(var q=0;q<n;q++)try{d(g[m+q])}catch(r){throw new l.Vi(29);}n&&(f.node.fj=f.node.kj=Date.now());return q}});return Lb(a,b,e)}},Rb=(a,b)=>a?C(w,a,b):"";function Sb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?l.sk():L(a).path;if(0==b.length){if(!c)throw new l.Vi(44);return a}return a+"/"+b}
function Tb(a,b){z.setUint32(4*(a>>2),b.Pl,!0);z.setUint32(4*(a+4>>2),b.mode,!0);z.setUint32(4*(a+8>>2),b.km,!0);z.setUint32(4*(a+12>>2),b.uid,!0);z.setUint32(4*(a+16>>2),b.$l,!0);z.setUint32(4*(a+20>>2),b.mk,!0);z.setBigInt64(8*(a+24>>3),BigInt(b.size),!0);z.setInt32(4*(a+32>>2),4096,!0);z.setInt32(4*(a+36>>2),b.hl,!0);var c=b.Ej.getTime(),d=b.fj.getTime(),e=b.kj.getTime();z.setBigInt64(8*(a+40>>3),BigInt(Math.floor(c/1E3)),!0);z.setUint32(4*(a+48>>2),c%1E3*1E6,!0);z.setBigInt64(8*(a+56>>3),BigInt(Math.floor(d/
1E3)),!0);z.setUint32(4*(a+64>>2),d%1E3*1E6,!0);z.setBigInt64(8*(a+72>>3),BigInt(Math.floor(e/1E3)),!0);z.setUint32(4*(a+80>>2),e%1E3*1E6,!0);z.setBigInt64(8*(a+88>>3),BigInt(b.cm),!0);return 0}
var La=void 0,Ub=[0,31,60,91,121,152,182,213,244,274,305,335],Vb=[0,31,59,90,120,151,181,212,243,273,304,334],Wb=[],Xb=(a,b)=>{Wb.length=0;for(var c;c=w[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Wb.push(112==c?z.getUint32(4*(b>>2),!0):106==c?z.getBigInt64(8*(b>>3),!0):105==c?z.getInt32(4*(b>>2),!0):z.getFloat64(8*(b>>3),!0));b+=d?8:4}return Wb},Zb=(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},ic=(a,b)=>{$b=a;ac=b;if(!bc)return 1;cc||=!0;if(0==a)dc=function(){setTimeout(ec,Math.max(0,fc+b-performance.now())|
0)};else if(1==a)dc=function(){gc(ec)};else{if(!hc)if(globalThis.setImmediate)hc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);hc=d=>{c.push(d);postMessage("setimmediate","*")}}dc=function(){hc(ec)}}return 0},jc=0,kc=a=>{na=a;Ja||0<jc||(h.onExit?.(a),ma=!0);throw new Da(a);},lc=a=>{if(a instanceof Da||"unwind"==a)return na;throw a;},mc=()=>{if(!(Ja||0<jc))try{var a=na;na=a;kc(a)}catch(b){lc(b)}},
wc=(a,b,c,d,e)=>{function f(){return g<nc?(mc(),!1):!0}bc=a;oc=d;var g=nc;cc=!1;ec=function(){if(!ma)if(0<pc.length){var m=pc.shift();m.Zm(m.wm);if(qc){var n=qc,q=0==n%1?n-1:Math.floor(n);qc=m.Jm?q:(8*n+(q+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=qc??0,q=rc.Pm??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(ec,0)}else if(f())if(sc=sc+1|0,1==$b&&1<ac&&0!=sc%ac)dc();else{0==$b&&(fc=performance.now());a:if(!ma){for(m of tc)if(!1===
m())break a;uc(a);for(n of vc)n()}f()&&dc()}};e||(0<b?ic(0,1E3/b):ic(1,1),dc());if(c)throw"unwind";},uc=a=>{if(!ma)try{return a()}catch(b){lc(b)}finally{mc()}},cc=!1,dc=null,nc=0,bc=null,oc=0,$b=0,ac=0,sc=0,pc=[],tc=[],vc=[];function xc(){dc=null;nc++}function yc(){nc++;var a=$b,b=ac,c=bc;bc=null;wc(c,0,!1,oc,!0);ic(a,b);dc()}var zc=0;
function gc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===zc)zc=b+1E3/60;else for(;b+2>=zc;)zc+=1E3/60;setTimeout(a,Math.max(zc-b,0))}}var rc={},fc,ec,hc,qc;function Ac(a){var b=M.lj[a];b.target.removeEventListener(b.jj,b.nl,b.wj);M.lj.splice(a,1)}
function Cc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of M.Jj)if(e.$k==a&&d(e.gl,c))return;M.Jj.push({$k:a,tl:b,gl:c});M.Jj.sort((f,g)=>f.tl<g.tl)}function Dc(a){M.Jj=M.Jj.filter(b=>b.$k!=a)}function Ec(){return navigator.userActivation?navigator.userActivation.isActive:M.Nk&&M.Kl.fl}function Fc(){if(Ec()){var a=M.Jj;M.Jj=[];for(var b of a)b.$k(...b.gl)}}
function Gc(a){if(!a.target)return-4;if(a.mj)a.nl=function(c){++M.Nk;M.Kl=a;Fc();a.zj(c);Fc();--M.Nk},a.target.addEventListener(a.jj,a.nl,a.wj),M.lj.push(a);else for(var b=0;b<M.lj.length;++b)M.lj[b].target==a.target&&M.lj[b].jj==a.jj&&Ac(b--);return 0}function Hc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={ym:0,Mk:0,Rk:0,en:0,el:0,bl:0,Kk:0,Mm:0,Wk:0,Lm:0,Lk:0,Xk:0,dl:0,pn:0,kn(){for(;M.lj.length;)Ac(M.lj.length-1);M.Jj=[]},Nk:0,Jj:[],lj:[],pm:(a,b)=>{for(var c=0;c<M.lj.length;++c)M.lj[c].target!=a||b&&b!=M.lj[c].jj||Ac(c--)},ln(a){let b=!1;for(let c=0;c<M.lj.length;++c){const d=M.lj[c];d.target===a.target&&d.nj===a.nj&&d.mj===a.mj&&d.xj===a.xj&&(Ac(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ic=[0,document,window],N=a=>
{a=2<a?a?C(w,a):"":a;return Ic[a]||document.querySelector(a)},Kc=a=>{var b=Za(a)+1,c=Jc(b);D(a,w,c,b);return c},Lc=a=>{var b=O(),c=Jc(8),d=c+4;a=Kc(a.id);if(a=N(a))z.setInt32(4*(c>>2),a.width,!0),z.setInt32(4*(d>>2),a.height,!0);c=[z.getInt32(4*(c>>2),!0),z.getInt32(4*(d>>2),!0)];Q(b);return c},Mc=(a,b,c)=>{a=N(a);if(!a)return-4;a.width=b;a.height=c;return 0},Nc=(a,b,c)=>{if(a.Im){var d=O();a=Kc(a.id);Mc(a,b,c);Q(d)}else a.width=b,a.height=c},Oc={},Qc=a=>{function b(){Pc()||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),Nc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=t,a.style.paddingBottom=v,a.style.marginLeft=E,a.style.marginRight=G,a.style.marginTop=J,a.style.marginBottom=P,document.body.style.margin=Z,document.documentElement.style.overflow=aa,document.body.scroll=ra,a.style.Lj=x,
a.dk&&a.dk.Yj.viewport(0,0,d,e),Oc.qk&&R(Oc.qk,37,0,Oc.il))}var c=Lc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,t=a.style.paddingTop,v=a.style.paddingBottom,E=a.style.marginLeft,G=a.style.marginRight,J=a.style.marginTop,P=a.style.marginBottom,Z=document.body.style.margin,aa=document.documentElement.style.overflow,ra=document.body.scroll,x=a.style.Lj;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Rc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Sc=a=>0>Ic.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Tc=(a,b)=>{if(0!=b.Zk||0!=b.Dk){Qc(a);var c=b.sm?innerWidth:screen.width,d=b.sm?innerHeight:screen.height,e=Sc(a),f=e.width;e=e.height;var g=Lc(a),m=g[0];g=g[1];3==b.Zk?(Rc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Zk&&(c*g<m*d?(f=g*c/m,Rc(a,(d-f)/2,0),d=f):(f=m*d/g,Rc(a,0,(c-f)/
2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ul&&(a.style.Lj="optimizeSpeed",a.style.Lj="-moz-crisp-edges",a.style.Lj="-o-crisp-edges",a.style.Lj="-webkit-optimize-contrast",a.style.Lj="optimize-contrast",a.style.Lj="crisp-edges",a.style.Lj="pixelated");n=2==b.Dk?devicePixelRatio:1;0!=b.Dk&&(c=c*n|0,d=d*n|0,Nc(a,c,d),a.dk&&a.dk.Yj.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();
else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return M.fullscreenEnabled()?-3:-1;Oc=b;b.qk&&R(b.qk,37,0,b.il);return 0},Uc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Vc=a=>{try{a()}catch(b){A(b)}};
function Wc(a){var b=(...c)=>{Xc.push(a);try{return a(...c)}finally{if(!ma&&(Xc.pop(),S&&1===Yc&&0===Xc.length&&(Yc=0,Vc(Zc),"undefined"!=typeof $c&&!ad&&bd))){ad=!0;do{c=bd;bd=0;var d=z.getUint32(4*(c>>2),!0),e=z.getUint32(4*(c+4>>2),!0);cd(d,e);Q(z.getUint32(4*(c+8>>2),!0));d=z.getUint32(4*(c+12>>2),!0);0!==d?(S=null,z.setUint32(4*(c+12>>2),0,!0),dynCall_vi(d,z.getUint32(4*(c+16>>2),!0))):(S=c+=20,Yc=2,dd(c),ed(c))}while(bd);ad=!1}}};fd.set(a,b);return b}
var Yc=0,S=null,gd=0,Xc=[],hd=new Map,jd=new Map,fd=new Map,kd=0,ld=null,md=[];function nd(){return new Promise((a,b)=>{ld={resolve:a,reject:b}})}function od(){var a=pd(4108),b=a+12;z.setUint32(4*(a>>2),b,!0);z.setUint32(4*(a+4>>2),b+4096,!0);qd(a);return a}function qd(a){var b=Xc[0];if(!hd.has(b)){var c=kd++;hd.set(b,c);jd.set(c,b)}b=hd.get(b);z.setInt32(4*(a+8>>2),b,!0)}function ed(a){a=z.getInt32(4*(a+8>>2),!0);a=jd.get(a);a=fd.get(a);return uc(a)}
function rd(a){if(!ma){if(0===Yc){var b=!1,c=!1;a((d=0)=>{if(!ma&&(gd=d,b=!0,c)){Yc=2;Vc(()=>dd(S));"undefined"!=typeof rc&&bc&&yc();d=!1;try{var e=ed(S)}catch(m){e=m,d=!0}var f=!1;if(!S){var g=ld;g&&(ld=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Yc=1,S=od(),"undefined"!=typeof rc&&bc&&xc(),Vc(()=>sd(S)))}else 2===Yc?(Yc=0,Vc(td),ud(S),S=null,md.forEach(uc)):A(`invalid state: ${Yc}`);return gd}}var vd=a=>rd(async b=>{b(await a())}),bd=0,ad=!1,$c={};
function Pc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var wd=a=>{var b=Pc(),c=!!b;u[a]=c;u[a+1]=M.fullscreenEnabled();var d=c?b:M.mm,e=d?.id||"";D(Hc(d),w,a+2,128);D(e,w,a+130,128);z.setInt32(4*(a+260>>2),d?d.clientWidth:0,!0);z.setInt32(4*(a+264>>2),d?d.clientHeight:0,!0);z.setInt32(4*(a+268>>2),screen.width,!0);z.setInt32(4*(a+272>>2),screen.height,!0);c&&(M.mm=b)},xd=(a,b)=>{z.setFloat64(8*(a>>3),b.timestamp,!0);for(var c=0;c<b.axes.length;++c)z.setFloat64(8*(a+8*c+16>>3),b.axes[c],!0);for(c=0;c<b.buttons.length;++c)"object"==typeof b.buttons[c]?
z.setFloat64(8*(a+8*c+528>>3),b.buttons[c].value,!0):z.setFloat64(8*(a+8*c+528>>3),b.buttons[c],!0);for(c=0;c<b.buttons.length;++c)u[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];u[a+1104]=b.connected;z.setInt32(4*(a+1108>>2),b.index,!0);z.setInt32(4*(a+8>>2),b.axes.length,!0);z.setInt32(4*(a+12>>2),b.buttons.length,!0);D(b.id,w,a+1112,64);D(b.mapping,w,a+1176,64)},yd=a=>{setTimeout(()=>{uc(a)},1E4)},zd=!1,Ad=[];
function vb(){function a(){zd=document.pointerLockElement===h.canvas}if(!Bd){Bd=!0;tb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Cd(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Cd(d)}));var f=URL.createObjectURL(e);return new Promise((g,m)=>{var n=new Image;n.onload=()=>{var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{ka(`Image ${f} could not be decoded`);m()};n.src=f})}});tb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Cd(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=()=>{if(!g){ka(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var q="",r=0,t=0,v=0;v<c.length;v++)for(r=r<<
8|c[v],t+=8;6<=t;){var E=r>>t-6&63;t-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[E]}2==t?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],q+="=="):4==t&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],q+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+q;f(n)}};n.src=m;yd(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!zd&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Dd(a){a=a.getContext("2d");if(!a)return null;h.ctx=a;Ad.forEach(b=>b());vb();return a}function Cd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var ub={},Bd,T,Ed=1,Fd=[],U=[],Gd=[],Hd=[],Id=[],V=[],Jd=[],Kd=[],W=[],Ld=[],Md=[],Nd=[],Od={},Pd={},Qd=4,Rd=0,Sd=a=>{for(var b=Ed++,c=a.length;c<b;c++)a[c]=null;return b},Td=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&Sd(d);f&&(f.name=g,d[g]=f);z.setInt32(4*(b+4*e>>2),g,!0)}},Vd=(a,b)=>{if(h.preinitializedWebGLContext){var c=h.preinitializedWebGLContext;b.rl=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else a.fk||(a.fk=a.getContext,a.getContext=function(d,e){e=a.fk(d,e);
return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=a.getContext("webgl2",b);return c?Ud(c,b):0},Ud=(a,b)=>{var c=Sd(Kd);b={handle:c,attributes:b,version:b.rl,Yj:a};a.canvas&&(a.canvas.dk=b);Kd[c]=b;return c},Wd,Xd=a=>T.activeTexture(a),Yd=(a,b)=>{T.attachShader(U[a],V[b])},Zd=(a,b)=>{35051==a?T.Ek=b:35052==a&&(T.yj=b);T.bindBuffer(a,Fd[b])},$d=(a,b)=>{T.bindFramebuffer(a,Gd[b])},ae=(a,b)=>{T.bindTexture(a,Id[b])},be=a=>{T.bindVertexArray(Jd[a])},ce=(a,b)=>T.blendEquationSeparate(a,b),
de=(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),ee=(a,b,c,d,e,f,g,m,n,q)=>T.blitFramebuffer(a,b,c,d,e,f,g,m,n,q),fe=(a,b,c,d)=>{c&&b?T.bufferData(a,w,d,c,b):T.bufferData(a,b,d)},ge=(a,b,c,d)=>{c&&T.bufferSubData(a,b,w,d,c)},he=a=>T.clear(a),ie=(a,b,c,d)=>T.clearColor(a,b,c,d),je=a=>T.clearDepth(a),ke=a=>{T.compileShader(V[a])},le=(a,b,c,d,e,f,g,m,n)=>{T.yj||!m?T.compressedTexSubImage2D(a,b,c,d,e,f,g,m,n):T.compressedTexSubImage2D(a,b,c,d,e,f,g,w,n,m)},me=()=>{var a=Sd(U),b=T.createProgram();b.name=a;b.Ak=
b.yk=b.zk=0;b.cl=1;U[a]=b;return a},ne=a=>{var b=Sd(V);V[b]=T.createShader(a);return b},oe=a=>T.cullFace(a),pe=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Fd[d];e&&(T.deleteBuffer(e),e.name=0,Fd[d]=null,d==T.Ek&&(T.Ek=0),d==T.yj&&(T.yj=0))}},qe=(a,b)=>{for(var c=0;c<a;++c){var d=z.getInt32(4*(b+4*c>>2),!0),e=Gd[d];e&&(T.deleteFramebuffer(e),e.name=0,Gd[d]=null)}},re=a=>{if(a){var b=U[a];b&&(T.deleteProgram(b),b.name=0,U[a]=null)}},se=a=>{if(a){var b=V[a];b&&(T.deleteShader(b),
V[a]=null)}},te=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Id[d];e&&(T.deleteTexture(e),e.name=0,Id[d]=null)}},ue=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0);T.deleteVertexArray(Jd[d]);Jd[d]=null}},ve=a=>T.depthFunc(a),we=a=>{T.depthMask(!!a)},xe=a=>T.disable(a),ye=a=>{T.disableVertexAttribArray(a)},ze=(a,b,c)=>{T.drawArrays(a,b,c)},Ae=(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},Be=[],Ce=(a,b)=>{for(var c=Be[a],d=0;d<a;d++)c[d]=z.getInt32(4*(b+4*d>>2),!0);
T.drawBuffers(c)},De=(a,b,c,d)=>{T.drawElements(a,b,c,d)},Ee=(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},Fe=a=>T.enable(a),Ge=a=>{T.enableVertexAttribArray(a)},He=(a,b,c,d,e)=>{T.framebufferTexture2D(a,b,c,Id[d],e)},Ie=a=>T.frontFace(a),Je=(a,b)=>{Td(a,b,"createBuffer",Fd)},Ke=(a,b)=>{Td(a,b,"createFramebuffer",Gd)},Le=(a,b)=>{Td(a,b,"createTexture",Id)},Me=(a,b)=>{Td(a,b,"createVertexArray",Jd)},Ne=a=>T.generateMipmap(a),Oe=(a,b,c,d,e,f,g,m)=>{b=U[b];if(a=T[a](b,c))d=m&&D(a.name,w,m,d),e&&
z.setInt32(4*(e>>2),d,!0),f&&z.setInt32(4*(f>>2),a.size,!0),g&&z.setInt32(4*(g>>2),a.type,!0)},Pe=(a,b,c,d,e,f,g)=>Oe("getActiveUniform",a,b,c,d,e,f,g),Qe=(a,b)=>{z.setUint32(4*(a>>2),b,!0);var c=z.getUint32(4*(a>>2),!0);z.setUint32(4*(a+4>>2),(b-c)/4294967296,!0)},Re=()=>{var a="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(T.getSupportedExtensions()||[]).filter(b=>a.includes(b))},Se=()=>{var a=Re();return a=a.concat(a.map(b=>"GL_"+b))},Te=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:d=Se().length;break;case 33307:case 33308:d=33307==a?3:0}if(void 0===d)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z.setInt32(4*(b+4*a>>2),e[a],!0);break;case 2:z.setFloat32(4*(b+4*a>>2),e[a],!0);break;case 4:u[b+a]=e[a]?1:0}return}d=
e.name|0}}switch(c){case 1:Qe(b,d);break;case 0:z.setInt32(4*(b>>2),d,!0);break;case 2:z.setFloat32(4*(b>>2),d,!0);break;case 4:u[b]=d?1:0}}},Ue=(a,b,c,d)=>{b=T.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:return}else if(b instanceof WebGLBuffer)a=b.name|0;else return;break;default:return}switch(d){case 1:Qe(c,a);break;case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*
(c>>2),a,!0);break;case 4:u[c]=a?1:0;break;default:A("internal emscriptenWebGLGetIndexed() error, bad type: "+d)}},Ve=(a,b)=>Te(a,b,0),We=(a,b,c,d)=>{a=T.getProgramInfoLog(U[a]);b=0<b&&d?D(a,w,d,b):0;c&&z.setInt32(4*(c>>2),b,!0)},Xe=(a,b,c)=>{if(c&&!(a>=Ed))if(a=U[a],35716==b)z.setInt32(4*(c>>2),T.getProgramInfoLog(a).length+1,!0);else if(35719==b){if(!a.Ak){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ak=Math.max(a.Ak,T.getActiveUniform(a,b).name.length+1)}z.setInt32(4*(c>>2),a.Ak,!0)}else if(35722==
b){if(!a.yk)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.yk=Math.max(a.yk,T.getActiveAttrib(a,b).name.length+1);z.setInt32(4*(c>>2),a.yk,!0)}else if(35381==b){if(!a.zk)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.zk=Math.max(a.zk,T.getActiveUniformBlockName(a,b).length+1);z.setInt32(4*(c>>2),a.zk,!0)}else z.setInt32(4*(c>>2),T.getProgramParameter(a,b),!0)},Ye=(a,b,c)=>{if(c){a=W[a];b=2>Wd.version?T.Kj.getQueryObjectEXT(a,b):T.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=
b;Qe(c,d)}},Ze=(a,b,c)=>{if(c){a=T.Kj.getQueryObjectEXT(W[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)}},$e=(a,b,c,d)=>{a=T.getShaderInfoLog(V[a]);b=0<b&&d?D(a,w,d,b):0;c&&z.setInt32(4*(c>>2),b,!0)},af=(a,b,c)=>{c&&(35716==b?(a=T.getShaderInfoLog(V[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):35720==b?(a=T.getShaderSource(V[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):z.setInt32(4*(c>>2),T.getShaderParameter(V[a],b),!0))},bf=a=>{var b=Za(a)+1,c=pd(b);c&&D(a,w,c,b);return c},
cf=a=>{var b=Od[a];if(!b){switch(a){case 7939:b=bf(Se().join(" "));break;case 7936:case 7937:case 37445:case 37446:b=(b=T.getParameter(a))?bf(b):0;break;case 7938:b=bf(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=bf(b)}Od[a]=b}return b},df=(a,b)=>{if(2>Wd.version)return 0;var c=Pd[a];if(c)return 0>b||b>=c.length?0:c[b];
switch(a){case 7939:return c=Se().map(bf),c=Pd[a]=c,0>b||b>=c.length?0:c[b];default:return 0}},ef=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ff=a=>{var b=a.pk,c=a.xl,d;if(!b){a.pk=b={};a.wl={};var e=T.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=T.getActiveUniform(a,d);var g=f.name;f=f.size;var m=ef(g);m=0<m?g.slice(0,m):g;var n=a.cl;a.cl+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=g,a.wl[n++]=m}}},gf=(a,b)=>{b=b?C(w,b):"";if(a=U[a]){ff(a);var c=a.pk,d=0,e=b,f=ef(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,
e=b.slice(0,f));if((e=a.xl[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}return-1},X=a=>{var b=T.Ll,c=b.pk[a];"number"==typeof c&&(b.pk[a]=c=T.getUniformLocation(b,b.wl[a]+(0<c?`[${c}]`:"")));return c},hf=(a,b,c,d)=>{if(c)if(a=U[a],ff(a),a=T.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*
(c+4*b>>2),a[b],!0)}},jf=(a,b,c)=>{hf(a,b,c,2)},kf=(a,b,c)=>{hf(a,b,c,0)},lf=(a,b,c,d)=>{if(c)if(a=T.getVertexAttrib(a,b),34975==b)z.setInt32(4*(c>>2),a&&a.name,!0);else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;case 5:c=4*(c>>2),d=Math.fround(a),z.setInt32(c,d,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0);break;case 5:var e=
4*(c+4*b>>2),f=Math.fround(a[b]);z.setInt32(e,f,!0)}},mf=(a,b,c)=>{lf(a,b,c,0)},nf=a=>(a=Jd[a])?T.isVertexArray(a):0,of=a=>{a=U[a];T.linkProgram(a);a.pk=0;a.xl={}},pf=(a,b)=>{3317==a?Qd=b:3314==a&&(Rd=b);T.pixelStorei(a,b)},qf=a=>T.readBuffer(a),rf=a=>{a-=5120;return 0==a?u:1==a?w:2==a?qa:4==a?ta:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?ua:sa},sf=(a,b,c,d,e,f,g)=>{if(T.Ek)T.readPixels(a,b,c,d,e,f,g);else{var m=rf(f);g>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);T.readPixels(a,b,c,d,e,f,m,g)}},
tf=(a,b,c,d)=>T.scissor(a,b,c,d),uf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?z.getUint32(4*(d+4*f>>2),!0):void 0;e+=Rb(z.getUint32(4*(c+4*f>>2),!0),g)}T.shaderSource(V[a],e)},vf=(a,b,c,d,e)=>{a=rf(a);b=d*((Rd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Qd-1&-Qd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},wf=(a,b,c,d,e,f,g,m,n)=>{if(T.yj)T.texImage2D(a,b,c,d,e,f,g,m,n);else if(n){var q=
rf(m);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);T.texImage2D(a,b,c,d,e,f,g,m,q,n)}else q=n?vf(m,g,d,e,n):null,T.texImage2D(a,b,c,d,e,f,g,m,q)},xf=(a,b,c)=>T.texParameteri(a,b,c),yf=(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),zf=(a,b,c,d,e,f,g,m,n)=>{if(T.yj)T.texSubImage2D(a,b,c,d,e,f,g,m,n);else if(n){var q=rf(m);T.texSubImage2D(a,b,c,d,e,f,g,m,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=n?vf(m,g,e,f,n):null,T.texSubImage2D(a,b,c,d,e,f,g,m,n)},Af=(a,b,c)=>{b&&T.uniform1fv(X(a),y,c>>2,b)},Bf=(a,b,c)=>
{b&&T.uniform1iv(X(a),ta,c>>2,b)},Cf=(a,b,c)=>{b&&T.uniform2fv(X(a),y,c>>2,2*b)},Df=(a,b,c)=>{b&&T.uniform2iv(X(a),ta,c>>2,2*b)},Ef=(a,b,c)=>{b&&T.uniform3fv(X(a),y,c>>2,3*b)},Ff=(a,b,c)=>{b&&T.uniform3iv(X(a),ta,c>>2,3*b)},Gf=(a,b,c)=>{b&&T.uniform4fv(X(a),y,c>>2,4*b)},Hf=(a,b,c)=>{b&&T.uniform4iv(X(a),ta,c>>2,4*b)},If=(a,b,c,d)=>{b&&T.uniformMatrix3fv(X(a),!!c,y,d>>2,9*b)},Jf=(a,b,c,d)=>{b&&T.uniformMatrix4fv(X(a),!!c,y,d>>2,16*b)},Kf=a=>{a=U[a];T.useProgram(a);T.Ll=a},Lf=(a,b)=>{T.vertexAttribDivisor(a,
b)},Mf=(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},Nf=(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},Of=(a,b,c,d)=>T.viewport(a,b,c,d),Pf=(a,b)=>{if(!M.fullscreenEnabled())return-1;a=N(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ec()?Tc(a,b):b.Ol?(Cc(Tc,1,[a,b]),1):-2:-3:-4},Qf=()=>{try{if(navigator.getGamepads)return(M.xk=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Rf=(a,b)=>{var c={target:N(2),jj:"beforeunload",nj:28,xj:a,mj:b,zj:d=>{var e=
R(b,28,0,a);e&&=e?C(w,e):"";if(e)return d.preventDefault(),d.returnValue=e},wj:!0};return Gc(c)},Sf=(a,b,c,d,e,f)=>{M.Kk||(M.Kk=pd(256));a={target:N(a),jj:f,nj:e,xj:b,mj:d,zj:g=>{var m=g.target.id?g.target.id:"",n=M.Kk;D(Hc(g.target),w,n+0,128);D(m,w,n+128,128);R(d,e,n,b)&&g.preventDefault()},wj:c};return Gc(a)},Tf=(a,b,c,d,e)=>{M.Lk||(M.Lk=pd(276));return Gc({target:a,jj:e,nj:19,xj:b,mj:d,zj:f=>{var g=M.Lk;wd(g);R(d,19,g,b)&&f.preventDefault()},wj:c})},Uf=(a,b,c,d,e)=>{M.Mk||(M.Mk=pd(1240));b={target:N(2),
fl:!0,jj:e,nj:d,xj:a,mj:c,zj:f=>{var g=M.Mk;xd(g,f.gamepad);R(c,d,g,a)&&f.preventDefault()},wj:b};return Gc(b)},Vf=(a,b,c,d,e,f)=>{M.Rk||(M.Rk=pd(160));a={target:N(a),jj:f,nj:e,xj:b,mj:d,zj:g=>{var m=M.Rk;z.setFloat64(8*(m>>3),g.timeStamp,!0);var n=m>>2;z.setInt32(4*(n+2),g.location,!0);u[m+12]=g.ctrlKey;u[m+13]=g.shiftKey;u[m+14]=g.altKey;u[m+15]=g.metaKey;u[m+16]=g.repeat;z.setInt32(4*(n+5),g.charCode,!0);z.setInt32(4*(n+6),g.keyCode,!0);z.setInt32(4*(n+7),g.which,!0);D(g.key||"",w,m+32,32);D(g.code||
"",w,m+64,32);D(g.char||"",w,m+96,32);D(g.locale||"",w,m+128,32);R(d,e,m,b)&&g.preventDefault()},wj:c};return Gc(a)},Wf=(a,b,c)=>{var d=screen.orientation;M.Wk||(M.Wk=pd(8));return Gc({target:d,jj:"change",nj:18,xj:a,mj:c,zj:e=>{var f=M.Wk,g=["portrait-primary","portrait-secondary","landscape-primary","landscape-secondary"],m=["portrait","portrait","landscape","landscape"],n=0;var q=window.screen?screen.orientation||screen.mozOrientation||screen.webkitOrientation:void 0;"object"===typeof q?(n=g.indexOf(q.type),
0>n&&(n=m.indexOf(q.type)),0<=n&&(n=1<<n),g=q.angle):g=window.orientation;z.setInt32(4*(f>>2),n,!0);z.setInt32(4*(f+4>>2),g,!0);R(c,18,f,a)&&e.preventDefault()},wj:b})},Xf=(a,b,c,d)=>{M.Xk||(M.Xk=pd(257));return Gc({target:a,jj:"pointerlockchange",nj:20,xj:b,mj:d,zj:e=>{var f=M.Xk,g=document.pointerLockElement;u[f]=!!g;var m=g?.id||"";D(Hc(g),w,f+1,128);D(m,w,f+129,128);R(d,20,f,b)&&e.preventDefault()},wj:c})},Yf=(a,b,c,d)=>{M.bl||(M.bl=pd(36));a=N(a);return Gc({target:a,jj:"resize",nj:10,xj:b,mj:d,
zj:e=>{if(e.target==a){var f=document.body;if(f){var g=M.bl;z.setInt32(4*(g>>2),0,!0);z.setInt32(4*(g+4>>2),f.clientWidth,!0);z.setInt32(4*(g+8>>2),f.clientHeight,!0);z.setInt32(4*(g+12>>2),innerWidth,!0);z.setInt32(4*(g+16>>2),innerHeight,!0);z.setInt32(4*(g+20>>2),outerWidth,!0);z.setInt32(4*(g+24>>2),outerHeight,!0);z.setInt32(4*(g+28>>2),pageXOffset|0,!0);z.setInt32(4*(g+32>>2),pageYOffset|0,!0);R(d,10,g,b)&&e.preventDefault()}}},wj:c})},Zf=(a,b,c)=>{var d=Ic[1];M.dl||(M.dl=pd(8));return Gc({target:d,
jj:"visibilitychange",nj:21,xj:a,mj:c,zj:e=>{var f=M.dl,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);u[f]=document.hidden;z.setInt32(4*(f+4>>2),g,!0);R(c,21,f,a)&&e.preventDefault()},wj:b})},$f=(a,b,c,d)=>{M.el||(M.el=pd(96));return Gc({target:a,fl:!0,jj:"wheel",nj:9,xj:b,mj:d,zj:e=>{var f=M.el;z.setFloat64(8*(f>>3),e.timeStamp,!0);var g=f>>2;z.setInt32(4*(g+2),e.screenX,!0);z.setInt32(4*(g+3),e.screenY,!0);z.setInt32(4*(g+4),e.clientX,!0);z.setInt32(4*(g+5),e.clientY,
!0);u[f+24]=e.ctrlKey;u[f+25]=e.shiftKey;u[f+26]=e.altKey;u[f+27]=e.metaKey;z.setInt16(2*(2*g+14),e.button,!0);z.setInt16(2*(2*g+15),e.buttons,!0);z.setInt32(4*(g+8),e.movementX,!0);z.setInt32(4*(g+9),e.movementY,!0);var m=Sc(a);z.setInt32(4*(g+10),e.clientX-(m.left|0),!0);z.setInt32(4*(g+11),e.clientY-(m.top|0),!0);z.setFloat64(8*(f+64>>3),e.deltaX,!0);z.setFloat64(8*(f+72>>3),e.deltaY,!0);z.setFloat64(8*(f+80>>3),e.deltaZ,!0);z.setInt32(4*(f+88>>2),e.deltaMode,!0);R(d,9,f,b)&&e.preventDefault()},
wj:c})};function ag(a){var b=bg,c=b.$i.pop()||b.Hj.length;b.Hj[c]=a;return c}class cg{Hj=[void 0];$i=[];get(a){return this.Hj[a]}has(a){return void 0!==this.Hj[a]}}var bg;
function dg(a,b,c,d,e){function f(){var K=0,Y=0;x.response&&Z&&0===z.getUint32(4*(a+12>>2),!0)&&(Y=x.response.byteLength);0<Y&&(K=eg(z.getUint32(4*(a+12>>2),!0),Y),w.set(new Uint8Array(x.response),K));z.setUint32(4*(a+12>>2),K,!0);Qe(a+16,Y);Qe(a+24,0);(K=x.response?x.response.byteLength:0)&&Qe(a+32,K);z.setInt16(2*(a+40>>1),x.readyState,!0);z.setInt16(2*(a+42>>1),x.status,!0);x.statusText&&D(x.statusText,w,a+44,64);ra&&(K=bf(x.responseURL),z.setUint32(4*(a+200>>2),K,!0))}var g=z.getUint32(4*(a+8>>
2),!0);if(g){var m=g?C(w,g):"",n=a+108,q=Rb(n+0);q||="GET";var r=z.getUint32(4*(n+56>>2),!0),t=z.getUint32(4*(n+68>>2),!0),v=z.getUint32(4*(n+72>>2),!0);g=z.getUint32(4*(n+76>>2),!0);var E=z.getUint32(4*(n+80>>2),!0),G=z.getUint32(4*(n+84>>2),!0),J=z.getUint32(4*(n+88>>2),!0),P=z.getUint32(4*(n+52>>2),!0),Z=!!(P&1),aa=!!(P&2),ra=!!(P&64);t=t?t?C(w,t):"":void 0;v=v?v?C(w,v):"":void 0;var x=new XMLHttpRequest;x.withCredentials=!!w[n+60];x.$i=aa;x.open(q,m,!ra,t,v);ra||(x.timeout=r);x.gj=m;x.responseType=
"arraybuffer";E&&(m=E?C(w,E):"",x.overrideMimeType(m));if(g)for(;;){n=z.getUint32(4*(g>>2),!0);if(!n)break;m=z.getUint32(4*(g+4>>2),!0);if(!m)break;g+=8;n=n?C(w,n):"";m=m?C(w,m):"";x.setRequestHeader(n,m)}var Na=ag(x);z.setUint32(4*(a>>2),Na,!0);g=G&&J?w.slice(G,G+J):null;x.onload=K=>{bg.has(Na)&&(f(),200<=x.status&&300>x.status?b(a,x,K):c(a,K))};x.onerror=K=>{bg.has(Na)&&(f(),c(a,K))};x.ontimeout=K=>{bg.has(Na)&&c(a,K)};x.onprogress=K=>{if(bg.has(Na)){var Y=Z&&aa&&x.response?x.response.byteLength:
0,Bc=0;0<Y&&Z&&aa&&(Bc=eg(z.getUint32(4*(a+12>>2),!0),Y),w.set(new Uint8Array(x.response),Bc));z.setUint32(4*(a+12>>2),Bc,!0);Qe(a+16,Y);Qe(a+24,K.loaded-Y);Qe(a+32,K.total);z.setInt16(2*(a+40>>1),x.readyState,!0);Y=x.status;3<=x.readyState&&0===x.status&&0<K.loaded&&(Y=200);z.setInt16(2*(a+42>>1),Y,!0);x.statusText&&D(x.statusText,w,a+44,64);d(a,K)}};x.onreadystatechange=K=>{if(bg.has(Na)){z.setInt16(2*(a+40>>1),x.readyState,!0);2<=x.readyState&&z.setInt16(2*(a+42>>1),x.status,!0);if(!ra&&2===x.readyState&&
0<x.responseURL.length){var Y=bf(x.responseURL);z.setUint32(4*(a+200>>2),Y,!0)}e(a,K)}};try{x.send(g)}catch(K){c(a,K)}}else c(a,"no url specified!")}
var fg=["default","low-power","high-performance"],gg={},ig=()=>{if(!hg){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in gg)void 0===gg[b]?delete a[b]:a[b]=gg[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);hg=c}return hg},hg;new Int8Array((new Int16Array([1])).buffer);function ya(){sa.$i=a=>a&65535;ua.$i=a=>a>>>0}l.Km=(a,b,c,d,e,f,g,m,n,q)=>{yb(a,b,c,d,e,m,n,q).then(f).catch(g)};
l.gn=yb;l.Fj=Array(4096);l.aj(F,{},"/");k("/tmp");k("/home");k("/home/web_user");(function(){k("/dev");cb(l.Tj(1,3),{read:()=>0,write:(d,e,f,g)=>g,hj:()=>0});Lb("/dev/null",l.Tj(1,3));bb(l.Tj(5,0),eb);bb(l.Tj(6,0),fb);Lb("/dev/tty",l.Tj(5,0));Lb("/dev/tty1",l.Tj(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ua(a),b=a.byteLength);return a[--b]};l.Ij("/dev","random",c);l.Ij("/dev","urandom",c);k("/dev/shm");k("/dev/shm/tmp")})();
(function(){k("/proc");var a=k("/proc/self");k("/proc/self/fd");l.aj({aj(){var b=l.createNode(a,"fd",16895,73);b.Xi={hj:F.Xi.hj};b.Wi={Sj(c,d){c=+d;var e=L(c);c={parent:null,aj:{kk:"fake"},Wi:{Nj:()=>e.path},id:c+1};return c.parent=c},Mj(){return Array.from(l.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();l.Tl={MEMFS:F,IDBFS:p};h.requestAnimationFrame=gc;h.pauseMainLoop=xc;h.resumeMainLoop=yc;h.preMainLoop&&tc.push(h.preMainLoop);
h.postMainLoop&&vc.push(h.postMainLoop);for(let a=0;32>a;++a)Be.push(Array(a));(async function(){bg=new cg})();h.noExitRuntime&&(Ja=h.noExitRuntime);h.preloadPlugins&&(tb=h.preloadPlugins);h.print&&(ja=h.print);h.printErr&&(ka=h.printErr);h.wasmBinary&&(la=h.wasmBinary);h.thisProgram&&(fa=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.callMain=jg;h.ENV=gg;h.addRunDependency=sb;h.removeRunDependency=rb;
h.ccall=(a,b,c,d,e)=>{function f(t){--jc;0!==n&&Q(n);return"string"===b?t?C(w,t):"":"boolean"===b?!!t:t}var g={string:t=>{var v=0;null!==t&&void 0!==t&&0!==t&&(v=Kc(t));return v},array:t=>{var v=Jc(t.length);u.set(t,v);return v}};a=h["_"+a];var m=[],n=0;if(d)for(var q=0;q<d.length;q++){var r=g[c[q]];r?(0===n&&(n=O()),m[q]=r(d[q])):m[q]=d[q]}c=S;d=a(...m);e=e?.async;jc+=1;if(S!=c)return nd().then(f);d=f(d);return e?Promise.resolve(d):d};h.FS_preloadFile=yb;h.FS_unlink=(...a)=>l.Cj(...a);
h.FS_createPath=(...a)=>Nb(...a);h.FS_createDevice=(...a)=>l.Ij(...a);h.FS=l;h.FS_createDataFile=(...a)=>xb(...a);h.FS_createLazyFile=(...a)=>Qb(...a);
var Yb={994168:(a,b)=>{ca(a,b)},994188:()=>{"undefined"===typeof h.SDL3&&(h.SDL3={});var a=h.SDL3;"undefined"===typeof a.Zj&&(a.Zj=function(b){return b});"undefined"===typeof a.Ck&&(a.Ck=function(b){return b>>>2})},994502:()=>window.matchMedia?window.matchMedia("(prefers-color-scheme: light)").matches?0:window.matchMedia("(prefers-color-scheme: dark)").matches?1:-1:-1,994711:()=>{if("undefined"!==typeof h.SDL3){var a=h.SDL3;a.al.removeEventListener("change",a.Jk);a.al=void 0;a.Jk=void 0}},994964:()=>
window.innerWidth,994994:()=>window.innerHeight,995025:a=>{h.requestFullscreen=function(){kg(a)}},995134:(a,b)=>{a=URL.createObjectURL(new Blob([w.buffer instanceof ArrayBuffer?w.subarray(a,a+b):w.slice(a,a+b)],{type:"image/png"}));b=document.querySelector("link[rel~='icon']");b||(b=document.createElement("link"),b.rel="icon",b.type="image/png",document.head.appendChild(b));b.href&&b.href.startsWith("blob:")&&URL.revokeObjectURL(b.href);b.href=a},995627:()=>{h.requestFullscreen=function(){}},995701:()=>
window.innerWidth,995731:()=>window.innerHeight,995762:a=>{a=document.querySelector(a?C(w,a):"");a.Dl=a.style.position;a.El=a.style.top;a.Cl=a.style.left;var b=document.createElement("div");b.id="SDL3_fill_document_background_elements";b.$i=a;b.ck=a.parentNode;b.ek=a.nextSibling;var c=Array.from(document.body.children),d;for(d of c)b.appendChild(d);document.body.appendChild(b);b.style.display="none";document.body.appendChild(a);a.style.position="fixed";a.style.top="0";a.style.left="0"},996460:()=>
{var a=document.getElementById("SDL3_fill_document_background_elements");if(a){for(a.ek?a.ck.insertBefore(a.$i,a.ek):a.ck.appendChild(a.$i);a.firstChild;)document.body.insertBefore(a.firstChild,a);a.$i.style.position=a.$i.Dl;a.$i.style.top=a.$i.El;a.$i.style.left=a.$i.Cl;a.remove()}},997019:()=>{if(window.matchMedia){var a=h.SDL3;a.Jk=function(){lg()};a.al=window.matchMedia("(prefers-color-scheme: dark)");a.al.addEventListener("change",a.Jk)}},997341:(a,b,c,d,e)=>{a=a?C(w,a):"";b=b?C(w,b):"";c=c?
C(w,c):"";d=d?C(w,d):"";var f=e?C(w,e):"";e=document.createElement("dialog");e.classList.add("SDL3_messagebox");e.id=f;e.style.color=d;e.style.backgroundColor=c;document.body.append(e);d=document.createElement("h1");d.innerText=a;e.append(d);a=document.createElement("p");a.innerText=b;e.append(a);e.showModal()},997882:(a,b,c,d,e,f,g,m)=>{a=a?C(w,a):"";b=b?C(w,b):"";f=f?C(w,f):"";var n=g?C(w,g):"",q=m?C(w,m):"",r=document.getElementById(a);if(!r)return!1;var t=document.createElement("button");t.innerText=
b;t.style.borderColor=f;t.style.backgroundColor=n;r.addEventListener("keydown",function(v){d&&"Enter"===v.key?(v.preventDefault(),t.click()):e&&"Escape"===v.key&&(v.preventDefault(),t.click())});r.addEventListener("cancel",function(v){v.preventDefault()});t.onmouseenter=function(){t.style.backgroundColor=q};t.onmouseleave=function(){t.style.backgroundColor=n};t.onclick=function(){r.close(c)};r.append(t);return!0},998891:a=>{a=a?C(w,a):"";return(a=document.getElementById(a))?a.open:!1},999029:a=>{a=
a?C(w,a):"";a=document.getElementById(a);if(!a)return 0;try{return parseInt(a.returnValue)}catch(b){return 0}},999211:(a,b)=>{alert((a?C(w,a):"")+"\n\n"+(b?C(w,b):""))},999268:(a,b,c,d)=>{d=d?C(w,d):"";var e=document.querySelector(d);d=h.SDL3;if(d.Jl!==e){d.gk=Dd(e);if(!d.gk)return!1;d.Jl=e}if(d.w!==a||d.h!==b||d.bm!==d.gk)d.image=d.gk.createImageData(a,b),d.w=a,d.h=b,d.bm=d.gk;a=d.image.data;c/=4;d.Nl!==a&&(d.Ml=new Int32Array(a.buffer),d.Nl=a);a=d.Ml;a.set(ta.subarray(c,c+a.length));d.gk.putImageData(d.image,
0,0);return!0},1000017:()=>{var a=h.SDL3;a.mouse_x=0;a.mouse_y=0;a.mouse_buttons=[];for(var b=0;5>b;++b)a.mouse_buttons[b]=!1;document.addEventListener("mousemove",function(c){var d=h.SDL3;d.mouse_x=c.clientX;d.mouse_y=c.clientY});document.addEventListener("mousedown",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=!0)});document.addEventListener("mouseup",function(c){var d=h.SDL3;0<=c.button&&c.button<d.mouse_buttons.length&&(d.mouse_buttons[c.button]=
!1)})},1000705:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);e/=4;b=new Int32Array(a.data.buffer);b.set(ta.subarray(e,e+b.length));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=mg(c.length+1);D(c,w,d,c.length+1);return d},1001363:a=>{h.canvas&&(h.canvas.style.cursor=a?C(w,a):"")},1001446:()=>{h.canvas&&(h.canvas.style.cursor="none")},1001515:()=>h.SDL3.mouse_x,
1001553:()=>h.SDL3.mouse_y,1001591:a=>h.SDL3.mouse_buttons[a],1001639:a=>{document.gj=function(b){"CapsLock"!=b.key&&"NumLock"!=b.key&&"ScrollLock"!=b.key&&ng(h.SDL3.Zj(a),b.getModifierState("CapsLock"),b.getModifierState("NumLock"),b.getModifierState("ScrollLock"))};document.addEventListener("keydown",document.gj)},1002066:()=>{document.removeEventListener("keydown",document.gj)},1002150:a=>{var b=document;b&&(b.$i=function(c){var d=h.SDL3;c=d.jk(0,0,c);0!=c&&(og(d.Zj(a),c),pg(c))},b.addEventListener("pointerup",
b.$i))},1002511:a=>{var b=h.SDL3;void 0===b.jk&&(b.jk=function(c,d,e){if("mouse"==e.pointerType)var f=1;else if("touch"==e.pointerType)f=2;else if("pen"==e.pointerType)f=3;else return 0;var g=mg(a);if(0!=g){var m=b.Ck(g),n=4*m++;z.setInt32(n,f,!0);n=4*m++;z.setInt32(n,e.pointerId,!0);n=4*m++;z.setInt32(n,"undefined"!==typeof e.button?e.button:-1,!0);n=4*m++;z.setInt32(n,e.buttons,!0);n=4*m++;z.setInt32(n,"pointerdown"==e.type?1:0,!0);n=4*m++;z.setFloat32(n,e.movementX,!0);n=4*m++;z.setFloat32(n,e.movementY,
!0);n=4*m++;z.setFloat32(n,e.clientX-c,!0);c=4*m++;z.setFloat32(c,e.clientY-d,!0);3==f&&(d=4*m++,z.setFloat32(d,e.pressure,!0),d=4*m++,z.setFloat32(d,e.on,!0),d=4*m++,z.setFloat32(d,e.tiltX,!0),d=4*m++,z.setFloat32(d,e.tiltY,!0),m=4*m++,z.setFloat32(m,e.qn,!0))}return g})},1003503:a=>{a=a?C(w,a):"";try{var b=document.querySelector(a);if(b)return b===document.activeElement}catch(c){}return!1},1003669:()=>document.hasFocus(),1003701:()=>{var a=document;a&&(a.removeEventListener("pointerup",a.$i),a.$i=
void 0)},1003883:()=>document.body.clientWidth,1003921:()=>document.body.clientHeight,1003960:()=>window.innerWidth,1003990:()=>window.innerHeight,1004021:()=>window.outerWidth,1004051:()=>window.outerHeight,1004082:()=>window.pageXOffset,1004113:()=>window.pageYOffset,1004144:(a,b)=>{var c=document.querySelector(b?C(w,b):"");if(c){var d=h.SDL3;c.$j=function(e){var f=c.getBoundingClientRect();e=d.jk(f.left,f.top,e);0!=e&&(qg(d.Zj(a),e),pg(e))};c.Dj=function(e){var f=c.getBoundingClientRect();e=d.jk(f.left,
f.top,e);0!=e&&(rg(d.Zj(a),e),pg(e))};c.gj=function(e){var f=c.getBoundingClientRect();e=d.jk(f.left,f.top,e);0!=e&&(sg(d.Zj(a),e),pg(e))};c.style.touchAction="none";c.addEventListener("pointerenter",c.$j);c.addEventListener("pointerleave",c.Dj);c.addEventListener("pointercancel",c.Dj);c.addEventListener("pointerdown",c.gj);c.addEventListener("pointermove",c.gj);c.addEventListener("pointerup",c.gj)}},1005532:(a,b,c)=>{var d=document.querySelector(b?C(w,b):"");if(d){var e=h.SDL3,f=function(g){var m=
mg(c);if(0!=m){var n=m>>2,q=d.getBoundingClientRect(),r=4*n++;z.setInt32(r,g.clientX-q.left,!0);n=4*n++;z.setInt32(n,g.clientY-q.top,!0)}return m};e.Hk=function(g){g.preventDefault();g=f(g);0!=g&&(tg(a,g),pg(g))};d.addEventListener("dragover",e.Hk);e.uk=0;try{k("/tmp/filedrop")}catch(g){}e.Ik=function(g){g.preventDefault();if(g.dataTransfer.types.includes("text/plain"))g=bf(g.dataTransfer.getData("text/plain")),ug(a,g),vg(g);else if(g.dataTransfer.types.includes("Files")){let m=0;const n=g.dataTransfer.files.length;
for(let q=0;q<n;q++){const r=g.dataTransfer.files.item(q),t=new FileReader;t.readAsArrayBuffer(r);t.onload=function(v){const E=`/tmp/filedrop/${e.uk}`;e.uk+=1;const G=`${E}/${r.name}`,J=bf(G);v=new Uint8Array(v.target.result);try{k(E);var P=l.open(G,"w");l.write(P,v,0,v.length,0);l.close(P);wg(a,J)}catch(Z){}vg(J);++m;m===n&&xg(a)};t.onerror=function(){++m;m===n&&xg(a)}}}xg(a)};d.addEventListener("drop",e.Ik);e.ik=function(g){g.preventDefault();xg(a)};d.addEventListener("dragend",e.ik);d.addEventListener("dragleave",
e.ik)}},1007899:a=>{if(a=document.querySelector(a?C(w,a):"")){var b=h.SDL3;a.removeEventListener("dragleave",b.ik);a.removeEventListener("dragend",b.ik);a.removeEventListener("drop",b.Ik);b.uk=void 0;"/tmp/filedrop";l.Bj("/tmp/filedrop");a.removeEventListener("dragover",b.Hk);b.Hk=void 0;b.Ik=void 0;b.ik=void 0}},1008729:a=>{if(a=document.querySelector(a?C(w,a):""))a.removeEventListener("pointerenter",a.$j),a.removeEventListener("pointerleave",a.Dj),a.removeEventListener("pointercancel",a.Dj),a.removeEventListener("pointerdown",
a.gj),a.removeEventListener("pointermove",a.gj),a.removeEventListener("pointerup",a.gj),a.style.touchAction="",a.$j=void 0,a.Dj=void 0,a.gj=void 0},1009463:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1009610:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1009844:()=>{var a=h.SDL3;"undefined"===typeof a.cj&&(a.cj={});"undefined"===typeof a.Yi&&
(a.Yi={});a.ej||("undefined"!==typeof AudioContext?a.ej=new AudioContext:"undefined"!==typeof webkitAudioContext&&(a.ej=new webkitAudioContext),a.ej&&"undefined"===typeof navigator.userActivation&&Ia(a.ej));return void 0!==a.ej},1010423:()=>h.SDL3.ej.sampleRate,1010474:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.Yi.uj&&(clearInterval(g.Yi.uj),g.Yi.uj=void 0,g.Yi.Xj=void 0);g.Yi.Tk=g.ej.createMediaStreamSource(m);g.Yi.sj=g.ej.createScriptProcessor(b,a,1);g.Yi.sj.onaudioprocess=function(n){void 0!==
g&&void 0!==g.Yi&&(n.outputBuffer.getChannelData(0).fill(0),g.Yi.Fk=n.inputBuffer,da("ip",c,[d]))};g.Yi.Tk.connect(g.Yi.sj);g.Yi.sj.connect(g.ej.destination);g.Yi.stream=m}var g=h.SDL3;g.Yi.Xj=g.ej.createBuffer(a,b,g.ej.sampleRate);g.Yi.Xj.getChannelData(0).fill(0);g.Yi.uj=setInterval(function(){g.Yi.Fk=g.Yi.Xj;da("ip",c,[d])},b/g.ej.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):
void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},1012315:(a,b,c,d)=>{var e=h.SDL3;e.cj.sj=e.ej.createScriptProcessor(b,0,a);e.cj.sj.onaudioprocess=function(f){void 0!==e&&void 0!==e.cj&&(void 0!==e.cj.uj&&(clearInterval(e.cj.uj),e.cj.uj=void 0,e.cj.Xj=void 0),e.cj.rk=f.outputBuffer,da("ip",c,[d]))};e.cj.sj.connect(e.ej.destination);"suspended"===e.ej.state&&(e.cj.Xj=e.ej.createBuffer(a,b,e.ej.sampleRate),e.cj.Xj.getChannelData(0).fill(0),e.cj.uj=setInterval(function(){"undefined"!==
typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.ej.resume();e.cj.rk=e.cj.Xj;da("ip",c,[d]);e.cj.rk=void 0},b/e.ej.sampleRate*1E3))},1013631:a=>{var b=h.SDL3;if(a){void 0!==b.Yi.uj&&clearInterval(b.Yi.uj);if(void 0!==b.Yi.stream){a=b.Yi.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.Yi.stream.removeTrack(a[c])}void 0!==b.Yi.sj&&(b.Yi.sj.onaudioprocess=function(){},b.Yi.sj.disconnect());void 0!==b.Yi.Tk&&b.Yi.Tk.disconnect();b.Yi=void 0}else void 0!=b.cj.sj&&b.cj.sj.disconnect(),
void 0!==b.cj.uj&&clearInterval(b.cj.uj),b.cj=void 0;void 0!==b.ej&&void 0===b.cj&&void 0===b.Yi&&(b.ej.close(),b.ej=void 0)},1014787:(a,b)=>{var c=h.SDL3;a=c.Ck(a);for(var d=c.cj.rk.numberOfChannels,e=0;e<d;++e){var f=c.cj.rk.getChannelData(e);if(f.length!=b)throw"Web Audio playback buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=z.getFloat32(4*(a+(g*d+e)),!0)}},1015320:(a,b)=>{for(var c=h.SDL3,d=c.Yi.Fk.numberOfChannels,e=0;e<d;++e){var f=
c.Yi.Fk.getChannelData(e);if(f.length!=b)throw"Web Audio recording buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ka(a+4*g,f[g],"float");else for(g=0;g<b;++g)Ka(a+4*(g*d+e),f[g],"float")}},1015947:()=>{h.SDL3.hk={};h.SDL3.hk.Oj=[];h.SDL3.hk.Oj[0]=void 0;h.SDL3.hk.Oj[1]=void 0},1016124:(a,b,c,d,e)=>{var f=h.SDL3.hk;void 0!==f.Oj[a]&&clearInterval(f.Oj[a]);f.Oj[a]=setInterval(function(){da("vi",d,[e])},b/c*1E3)},1016316:a=>{var b=
h.SDL3.hk;void 0!==b.Oj[a]&&clearInterval(b.Oj[a]);b.Oj[a]=void 0},1016447:a=>{let b=navigator.getGamepads();return b?(a=b[a])&&a.vibrationActuator?1:0:0},1016622:(a,b,c)=>{let d=navigator.getGamepads();if(!d)return 0;a=d[a];if(!a||!a.vibrationActuator)return 0;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:c/65535,strongMagnitude:b/65535});return 1},1016958:(a,b)=>{var c=void 0;if(navigator.languages&&navigator.languages.length)c=navigator.languages;else{var d=
navigator.$i||navigator.language||navigator.browserLanguage||navigator.systemLanguage;void 0!==d&&(c=[d])}if(void 0!==c){d="";for(var e=0;e<c.length;e++){var f=c[e];if(d.length+f.length+1>b)break;0<d.length&&(d+=",");d+=f}d=d.replace(/-/g,"_");b>d.length&&(b=d.length);for(e=0;e<b;e++)Ka(a+e,d.charCodeAt(e),"i8")}},1017666:a=>{var b=new URLSearchParams(window.location.search);for(const [d,e]of b)if(d.startsWith("SDL_")){b=bf(d);var c=bf(e);0!=b&&0!=c&&da("iiii",a,[b,c,1]);vg(b);vg(c)}},1018007:()=>
{h.onFirstFrame()}},vg,mg,pg,qg,rg,sg,og,tg,xg,ug,wg,ng,lg,kg,yg,gb,pd,ud,eg,zg,cd,Q,Jc,O,dynCall_vii,R,Ag,dynCall_vi,Bg,Cg,Dg,dynCall_v,dynCall_iii,Eg,Fg,sd,Zc,dd,td,xa,ea,Qg={Zc:function(a){a=navigator.getGamepads()[a];if(0<a.id.indexOf("Product: ")){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},_c:function(a){a=navigator.getGamepads()[a];if(0<a.id.indexOf("Vendor: ")){let b=a.id.indexOf("Vendor: ")+
8;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},Yc:function(a){return 0<=navigator.getGamepads()[a].id.toLowerCase().indexOf("xinput")},J:function(a,b,c){La=c;try{var d=L(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;l.streams[e];)e++;return Hb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),z.setInt16(2*(e+0>>1),2,!0),0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==
typeof l||"ErrnoError"!==f.name)throw f;return-f.dj}},Sf:function(a){try{return L(a),0}catch(b){if("undefined"==typeof l||"ErrnoError"!==b.name)throw b;return-b.dj}},_a:function(a,b){try{var c=L(a),d=c.node,e=c.Xi.pj;a=e?c:d;e??=d.Wi.pj;nb(e,63);var f=e(a);return Tb(b,f)}catch(g){if("undefined"==typeof l||"ErrnoError"!==g.name)throw g;return-g.dj}},xf:function(a,b,c){try{var d=L(a);d.Qj||(d.Qj=l.Mj(d.path));a=0;var e=l.hj(d,0,1),f=Math.floor(e/280),g=Math.min(d.Qj.length,f+Math.floor(c/280));for(c=
f;c<g;c++){var m=d.Qj[c];if("."===m){var n=d.node.id;var q=4}else if(".."===m)n=I(d.path,{parent:!0}).node.id,q=4;else{try{var r=ib(d.node,m)}catch(t){if(28===t?.dj)continue;throw t;}n=r.id;q=8192===(r.mode&61440)?2:H(r.mode)?4:40960===(r.mode&61440)?10:8}z.setBigInt64(8*(b+a>>3),BigInt(n),!0);z.setBigInt64(8*(b+a+8>>3),BigInt(280*(c+1)),!0);z.setInt16(2*(b+a+16>>1),280,!0);u[b+a+18]=q;D(m,w,b+a+19,256);a+=280}l.hj(d,280*c,0);return a}catch(t){if("undefined"==typeof l||"ErrnoError"!==t.name)throw t;
return-t.dj}},Gg:function(a,b,c){La=c;try{var d=L(a);switch(b){case 21509:return d.bj?0:-59;case 21505:if(!d.bj)return-59;if(d.bj.Gj.dm){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();z.setInt32(4*(e>>2),25856,!0);z.setInt32(4*(e+4>>2),5,!0);z.setInt32(4*(e+8>>2),191,!0);z.setInt32(4*(e+12>>2),35387,!0);for(var f=0;32>f;f++)u[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.bj?0:-59;case 21506:case 21507:case 21508:if(!d.bj)return-59;if(d.bj.Gj.em)for(e=
Ma(),z.getInt32(4*(e>>2),!0),z.getInt32(4*(e+4>>2),!0),z.getInt32(4*(e+8>>2),!0),z.getInt32(4*(e+12>>2),!0),a=[],f=0;32>f;f++)a.push(u[e+f+17]);return 0;case 21519:if(!d.bj)return-59;e=Ma();z.setInt32(4*(e>>2),0,!0);return 0;case 21520:return d.bj?-28:-59;case 21537:case 21531:return e=Ma(),l.Pk(d,b,e);case 21523:if(!d.bj)return-59;d.bj.Gj.fm&&(f=[24,80],e=Ma(),z.setInt16(2*(e>>1),f[0],!0),z.setInt16(2*(e+2>>1),f[1],!0));return 0;case 21524:return d.bj?0:-59;case 21515:return d.bj?0:-59;default:return-28}}catch(g){if("undefined"==
typeof l||"ErrnoError"!==g.name)throw g;return-g.dj}},jh:function(a,b){try{return a=a?C(w,a):"",Tb(b,l.stat(a,!0))}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return-c.dj}},af:function(a,b,c){try{return b=b?C(w,b):"",b=Sb(a,b),k(b,c),0}catch(d){if("undefined"==typeof l||"ErrnoError"!==d.name)throw d;return-d.dj}},Ea:function(a,b,c,d){try{b=b?C(w,b):"";var e=d&256;b=Sb(a,b,d&4096);return Tb(c,e?l.stat(b,!0):l.stat(b))}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;
return-f.dj}},ta:function(a,b,c,d){La=d;try{b=b?C(w,b):"";b=Sb(a,b);var e=d?Ma():0;return l.open(b,c,e).fd}catch(f){if("undefined"==typeof l||"ErrnoError"!==f.name)throw f;return-f.dj}},Pa:function(a,b){try{return a=a?C(w,a):"",Tb(b,l.stat(a))}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return-c.dj}},mf:function(a,b,c){try{b=b?C(w,b):"";b=Sb(a,b);if(c)if(512===c)l.Bj(b);else return-28;else l.Cj(b);return 0}catch(d){if("undefined"==typeof l||"ErrnoError"!==d.name)throw d;return-d.dj}},
nd:()=>A(""),Bb:()=>{throw Infinity;},Sc:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);z.setInt32(4*(b>>2),a.getSeconds(),!0);z.setInt32(4*(b+4>>2),a.getMinutes(),!0);z.setInt32(4*(b+8>>2),a.getHours(),!0);z.setInt32(4*(b+12>>2),a.getDate(),!0);z.setInt32(4*(b+16>>2),a.getMonth(),!0);z.setInt32(4*(b+20>>2),a.getFullYear()-1900,!0);z.setInt32(4*(b+24>>2),a.getDay(),!0);var c=a.getFullYear();z.setInt32(4*(b+28>>2),(0!==c%4||0===c%100&&0!==c%400?Vb:Ub)[a.getMonth()]+
a.getDate()-1|0,!0);z.setInt32(4*(b+36>>2),-(60*a.getTimezoneOffset()),!0);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z.setInt32(4*(b+32>>2),(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0,!0)},Pc:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var m=L(d),n=l.Uj(m,a,e,b,c),q=n.ul;z.setInt32(4*(f>>2),n.Hj,!0);z.setUint32(4*(g>>2),q,!0);return 0}catch(r){if("undefined"==typeof l||"ErrnoError"!==r.name)throw r;
return-r.dj}},Qc:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=L(e);if(c&2){c=f;if(!l.isFile(g.node.mode))throw new l.Vi(43);d&2||l.ak(g,w.slice(a,a+b),c,b,d)}}catch(m){if("undefined"==typeof l||"ErrnoError"!==m.name)throw m;return-m.dj}},Tc:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z.setUint32(4*(a>>2),60*Math.max(f,e),!0);z.setInt32(4*(b>>2),Number(f!=e),!0);b=g=>{var m=Math.abs(g);
return`UTC${0<=g?"-":"+"}${String(Math.floor(m/60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(D(a,w,c,17),D(b,w,d,17)):(D(a,w,d,17),D(b,w,c,17))},$c:function(a,b,c){if(!(0<=a&&3>=a))return 28;z.setBigInt64(8*(c>>3),BigInt(Math.round(1E6*(0===a?Date.now():performance.now()))),!0);return 0},la:Zb,m:(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},b:Zb,id:(a,b,c)=>{b=Xb(b,c);return Yb[a](...b)},qa:()=>{xc();bc=null},_:()=>Date.now(),bd:()=>{if(!M.fullscreenEnabled())return-1;Dc(Tc);
var a=Ic[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},hd:()=>{Dc(Uc);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},Db:function(a){if(bg.has(a)){var b=bg.get(a),c=bg;c.Hj[a]=void 0;c.$i.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},Rc:(a,b)=>{if(!ma)if(0===Yc){Yc=1;var c=a+20;qd(c);S=c;sd(c);c=O();z.setUint32(4*(a+8>>2),c,!0);bd=b}else Yc=0,
td(),S=null},t:()=>devicePixelRatio,i:(a,b,c)=>{a=N(a);if(!a)return-4;a=Sc(a);z.setFloat64(8*(b>>3),a.width,!0);z.setFloat64(8*(c>>3),a.height,!0);return 0},dd:a=>{if(!M.fullscreenEnabled())return-1;wd(a);return 0},Y:(a,b)=>{if(0>a||a>=M.xk.length)return-5;if(!M.xk[a])return-7;xd(b,M.xk[a]);return 0},cc:()=>2147483648,ld:(a,b)=>{a&&z.setInt32(4*(a>>2),$b,!0);b&&z.setInt32(4*(b>>2),ac,!0)},pa:()=>performance.now(),Xc:()=>M.xk.length,jd:(a,b)=>{z.setInt32(4*(a>>2),screen.width,!0);z.setInt32(4*(b>>
2),screen.height,!0)},zb:Xd,yb:Yd,hf:(a,b)=>{T.beginQuery(a,W[b])},Id:(a,b)=>{T.Kj.beginQueryEXT(a,W[b])},Pe:a=>T.beginTransformFeedback(a),xb:(a,b,c)=>{T.bindAttribLocation(U[a],b,c?C(w,c):"")},wb:Zd,Me:(a,b,c)=>{T.bindBufferBase(a,b,Fd[c])},Ne:(a,b,c,d,e)=>{T.bindBufferRange(a,b,Fd[c],d,e)},vb:$d,ub:(a,b)=>{T.bindRenderbuffer(a,Hd[b])},Rd:(a,b)=>{T.bindSampler(a,Ld[b])},tb:ae,Jd:(a,b)=>{T.bindTransformFeedback(a,Md[b])},Ue:be,Kc:be,sb:(a,b,c,d)=>T.blendColor(a,b,c,d),rb:a=>T.blendEquation(a),qb:ce,
pb:(a,b)=>T.blendFunc(a,b),ob:de,Xe:ee,nb:fe,mb:ge,lb:a=>T.checkFramebufferStatus(a),kb:he,pe:(a,b,c,d)=>T.clearBufferfi(a,b,c,d),qe:(a,b,c)=>{T.clearBufferfv(a,b,y,c>>2)},se:(a,b,c)=>{T.clearBufferiv(a,b,ta,c>>2)},re:(a,b,c)=>{T.clearBufferuiv(a,b,ua,c>>2)},ib:ie,hb:je,gb:a=>T.clearStencil(a),$d:(a,b,c)=>{c=Number(c);return T.clientWaitSync(Nd[a],b,c)},Af:(a,b)=>{T.Qm.clipControlEXT(a,b)},fb:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},eb:ke,db:(a,b,c,d,e,f,g,m)=>{T.yj||!g?T.compressedTexImage2D(a,
b,c,d,e,f,g,m):T.compressedTexImage2D(a,b,c,d,e,f,w,m,g)},of:(a,b,c,d,e,f,g,m,n)=>{T.yj?T.compressedTexImage3D(a,b,c,d,e,f,g,m,n):T.compressedTexImage3D(a,b,c,d,e,f,g,w,n,m)},cb:le,nf:(a,b,c,d,e,f,g,m,n,q,r)=>{T.yj?T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,q,r):T.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,w,r,q)},me:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),bb:(a,b,c,d,e,f,g,m)=>T.copyTexImage2D(a,b,c,d,e,f,g,m),ab:(a,b,c,d,e,f,g,m)=>T.copyTexSubImage2D(a,b,c,d,e,f,g,m),pf:(a,b,c,d,e,f,g,m,n)=>
T.copyTexSubImage3D(a,b,c,d,e,f,g,m,n),$a:me,Za:ne,Ya:oe,Xa:pe,Wa:qe,Va:re,kf:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=W[d];e&&(T.deleteQuery(e),W[d]=null)}},ce:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=W[d];e&&(T.Kj.deleteQueryEXT(e),W[d]=null)}},Ua:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Hd[d];e&&(T.deleteRenderbuffer(e),e.name=0,Hd[d]=null)}},Ud:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Ld[d];e&&(T.deleteSampler(e),
e.name=0,Ld[d]=null)}},Ta:se,ae:a=>{if(a){var b=Nd[a];b&&(T.deleteSync(b),b.name=0,Nd[a]=null)}},Sa:te,Hd:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Md[d];e&&(T.deleteTransformFeedback(e),e.name=0,Md[d]=null)}},Te:ue,Ec:ue,Ra:ve,Qa:we,Oa:(a,b)=>T.depthRange(a,b),Na:(a,b)=>{T.detachShader(U[a],V[b])},Ma:xe,La:ye,Ka:ze,fe:Ae,Tb:Ae,qd:Ae,wf:Ae,rd:Ae,df:Ce,uf:Ce,bc:Ce,Ja:De,ee:Ee,Mb:Ee,od:Ee,pd:Ee,vf:Ee,sf:(a,b,c,d,e,f)=>{T.drawElements(a,d,e,f)},Ia:Fe,Ha:Ge,gf:a=>T.endQuery(a),
xd:a=>{T.Kj.endQueryEXT(a)},Oe:()=>T.endTransformFeedback(),de:(a,b)=>(a=T.fenceSync(a,b))?(b=Sd(Nd),a.name=b,Nd[b]=a,b):0,Ga:()=>T.finish(),Fa:()=>T.flush(),Da:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,Hd[d])},Ca:He,Ve:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,Id[c],d,e)},Ba:Ie,Aa:Je,ya:Ke,lf:(a,b)=>{Td(a,b,"createQuery",W)},ne:(a,b)=>{for(var c=0;c<a;c++){var d=T.Kj.createQueryEXT();if(!d){for(;c<a;)d=4*(b+4*c++>>2),z.setInt32(d,0,!0);break}var e=Sd(W);d.name=e;W[e]=d;z.setInt32(4*(b+4*c>>2),
e,!0)}},xa:(a,b)=>{Td(a,b,"createRenderbuffer",Hd)},Vd:(a,b)=>{Td(a,b,"createSampler",Ld)},wa:Le,Gd:(a,b)=>{Td(a,b,"createTransformFeedback",Md)},Se:Me,vc:Me,za:Ne,va:(a,b,c,d,e,f,g)=>Oe("getActiveAttrib",a,b,c,d,e,f,g),ua:Pe,he:(a,b,c,d,e)=>{a=U[a];if(a=T.getActiveUniformBlockName(a,b))e&&0<c?(c=D(a,w,e,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0)},ie:(a,b,c,d)=>{a=U[a];if(35393==c)z.setInt32(4*(d>>2),T.getActiveUniformBlockName(a,b).length+1,!0);else if(a=T.getActiveUniformBlockParameter(a,
b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)z.setInt32(4*(d+4*c>>2),a[c],!0);else z.setInt32(4*(d>>2),a,!0)},ke:(a,b,c,d,e)=>{a=U[a];for(var f=[],g=0;g<b;g++)f.push(z.getInt32(4*(c+4*g>>2),!0));if(a=T.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)z.setInt32(4*(e+4*g>>2),a[g],!0)},ih:(a,b,c,d)=>{a=T.getAttachedShaders(U[a]);var e=a.length;e>b&&(e=b);z.setInt32(4*(c>>2),e,!0);for(b=0;b<e;++b)z.setInt32(4*(d+4*b>>2),V.indexOf(a[b]),!0)},hh:(a,b)=>T.getAttribLocation(U[a],b?C(w,b):""),gh:(a,
b)=>Te(a,b,4),Wd:(a,b,c)=>{Qe(c,T.getBufferParameter(a,b))},fh:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getBufferParameter(a,b),!0)},eh:()=>T.getError(),dh:(a,b)=>Te(a,b,2),Be:(a,b)=>T.getFragDataLocation(U[a],b?C(w,b):""),ch:(a,b,c,d)=>{a=T.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z.setInt32(4*(d>>2),a,!0)},Xd:(a,b,c)=>Ue(a,b,c,1),Zd:(a,b)=>{Te(a,b,1)},Qe:(a,b,c)=>Ue(a,b,c,0),bh:Ve,ud:(a,b,c,d,e)=>{a=T.getInternalformatParameter(a,
b,c);if(null!==a)for(b=0;b<a.length&&b<d;++b)z.setInt32(4*(e+4*b>>2),a[b],!0)},Cd:()=>{},$g:We,ah:Xe,Wc:Ye,fd:Ze,Oc:Ye,ef:(a,b,c)=>{a=T.getQueryParameter(W[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)},ad:Ze,ff:(a,b,c)=>{z.setInt32(4*(c>>2),T.getQuery(a,b),!0)},gd:(a,b,c)=>{c&&(c=4*(c>>2),a=T.Kj.getQueryEXT(a,b),z.setInt32(c,a,!0))},_g:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getRenderbufferParameter(a,b),!0)},Ld:(a,b,c)=>{z.setFloat32(4*(c>>2),T.getSamplerParameter(Ld[a],b),!0)},
Md:(a,b,c)=>{z.setInt32(4*(c>>2),T.getSamplerParameter(Ld[a],b),!0)},Yg:$e,Xg:(a,b,c,d)=>{a=T.getShaderPrecisionFormat(a,b);z.setInt32(4*(c>>2),a.rangeMin,!0);z.setInt32(4*(c+4>>2),a.rangeMax,!0);z.setInt32(4*(d>>2),a.precision,!0)},Wg:(a,b,c,d)=>{if(a=T.getShaderSource(V[a]))b=0<b&&d?D(a,w,d,b):0,c&&z.setInt32(4*(c>>2),b,!0)},Zg:af,Vg:cf,oe:df,Yd:(a,b,c,d,e)=>{a=T.getSyncParameter(Nd[a],b);null!==a&&(z.setInt32(4*(e>>2),a,!0),d&&z.setInt32(4*(d>>2),1,!0))},Ug:(a,b,c)=>{c&&z.setFloat32(4*(c>>2),T.getTexParameter(a,
b),!0)},Tg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getTexParameter(a,b),!0)},Ke:(a,b,c,d,e,f,g)=>{a=U[a];if(a=T.getTransformFeedbackVarying(a,b))g&&0<c?(c=D(a.name,w,g,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0),e&&z.setInt32(4*(e>>2),a.size,!0),f&&z.setInt32(4*(f>>2),a.type,!0)},je:(a,b)=>T.getUniformBlockIndex(U[a],b?C(w,b):""),le:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Rb(z.getUint32(4*(c+4*f>>2),!0)));if(a=T.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)z.setInt32(4*
(d+4*f>>2),a[f],!0)},Qg:gf,Sg:jf,Rg:kf,Ce:(a,b,c)=>hf(a,b,c,0),Ie:mf,He:mf,Ng:(a,b,c)=>{c&&z.setInt32(4*(c>>2),T.getVertexAttribOffset(a,b),!0)},Pg:(a,b,c)=>{lf(a,b,c,2)},Og:(a,b,c)=>{lf(a,b,c,5)},Mg:(a,b)=>T.hint(a,b),zd:(a,b,c)=>{for(var d=Be[b],e=0;e<b;e++)d[e]=z.getInt32(4*(c+4*e>>2),!0);T.invalidateFramebuffer(a,d)},yd:(a,b,c,d,e,f,g)=>{for(var m=Be[b],n=0;n<b;n++)m[n]=z.getInt32(4*(c+4*n>>2),!0);T.invalidateSubFramebuffer(a,m,d,e,f,g)},Lg:a=>(a=Fd[a])?T.isBuffer(a):0,Kg:a=>T.isEnabled(a),Jg:a=>
(a=Gd[a])?T.isFramebuffer(a):0,Ig:a=>(a=U[a])?T.isProgram(a):0,jf:a=>(a=W[a])?T.isQuery(a):0,Td:a=>(a=W[a])?T.Kj.isQueryEXT(a):0,Hg:a=>(a=Hd[a])?T.isRenderbuffer(a):0,Sd:a=>(a=Ld[a])?T.isSampler(a):0,Fg:a=>(a=V[a])?T.isShader(a):0,be:a=>T.isSync(Nd[a]),Eg:a=>(a=Id[a])?T.isTexture(a):0,Fd:a=>T.isTransformFeedback(Md[a]),Re:nf,mc:nf,Dg:a=>T.lineWidth(a),Cg:of,Ed:()=>T.pauseTransformFeedback(),Bg:pf,zf:(a,b)=>{T.sn.polygonModeWEBGL(a,b)},Ag:(a,b)=>T.polygonOffset(a,b),Bf:(a,b,c)=>{T.Rm.polygonOffsetClampEXT(a,
b,c)},Bd:()=>{},Ad:()=>{},md:(a,b)=>{T.Kj.queryCounterEXT(W[a],b)},tf:qf,zg:sf,yg:()=>{},xg:(a,b,c,d)=>T.renderbufferStorage(a,b,c,d),We:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Dd:()=>T.resumeTransformFeedback(),wg:(a,b)=>{T.sampleCoverage(a,!!b)},Od:(a,b,c)=>{T.samplerParameterf(Ld[a],b,c)},Nd:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);T.samplerParameterf(Ld[a],b,c)},Qd:(a,b,c)=>{T.samplerParameteri(Ld[a],b,c)},Pd:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);T.samplerParameteri(Ld[a],b,c)},ug:tf,
tg:()=>{},sg:uf,rg:(a,b,c)=>T.stencilFunc(a,b,c),qg:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),pg:a=>T.stencilMask(a),og:(a,b)=>T.stencilMaskSeparate(a,b),ng:(a,b,c)=>T.stencilOp(a,b,c),mg:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),lg:wf,rf:(a,b,c,d,e,f,g,m,n,q)=>{if(T.yj)T.texImage3D(a,b,c,d,e,f,g,m,n,q);else if(q){var r=rf(n);T.texImage3D(a,b,c,d,e,f,g,m,n,r,q>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else T.texImage3D(a,b,c,d,e,f,g,m,n,null)},kg:(a,b,c)=>T.texParameterf(a,b,c),jg:(a,b,c)=>{c=z.getFloat32(4*
(c>>2),!0);T.texParameterf(a,b,c)},ig:xf,hg:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);T.texParameteri(a,b,c)},wd:yf,vd:(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),gg:zf,qf:(a,b,c,d,e,f,g,m,n,q,r)=>{if(T.yj)T.texSubImage3D(a,b,c,d,e,f,g,m,n,q,r);else if(r){var t=rf(q);T.texSubImage3D(a,b,c,d,e,f,g,m,n,q,t,r>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,g,m,n,q,null)},Le:(a,b,c,d)=>{a=U[a];for(var e=[],f=0;f<b;f++)e.push(Rb(z.getUint32(4*(c+4*f>>2),!0)));T.transformFeedbackVaryings(a,
e,d)},fg:(a,b)=>{T.uniform1f(X(a),b)},eg:Af,dg:(a,b)=>{T.uniform1i(X(a),b)},cg:Bf,Ae:(a,b)=>{T.uniform1ui(X(a),b)},we:(a,b,c)=>{b&&T.uniform1uiv(X(a),ua,c>>2,b)},bg:(a,b,c)=>{T.uniform2f(X(a),b,c)},ag:Cf,$f:(a,b,c)=>{T.uniform2i(X(a),b,c)},_f:Df,ze:(a,b,c)=>{T.uniform2ui(X(a),b,c)},ve:(a,b,c)=>{b&&T.uniform2uiv(X(a),ua,c>>2,2*b)},Zf:(a,b,c,d)=>{T.uniform3f(X(a),b,c,d)},Yf:Ef,Xf:(a,b,c,d)=>{T.uniform3i(X(a),b,c,d)},Wf:Ff,ye:(a,b,c,d)=>{T.uniform3ui(X(a),b,c,d)},ue:(a,b,c)=>{b&&T.uniform3uiv(X(a),ua,
c>>2,3*b)},Vf:(a,b,c,d,e)=>{T.uniform4f(X(a),b,c,d,e)},Uf:Gf,Tf:(a,b,c,d,e)=>{T.uniform4i(X(a),b,c,d,e)},Rf:Hf,xe:(a,b,c,d,e)=>{T.uniform4ui(X(a),b,c,d,e)},te:(a,b,c)=>{b&&T.uniform4uiv(X(a),ua,c>>2,4*b)},ge:(a,b,c)=>{a=U[a];T.uniformBlockBinding(a,b,c)},Qf:(a,b,c,d)=>{b&&T.uniformMatrix2fv(X(a),!!c,y,d>>2,4*b)},cf:(a,b,c,d)=>{b&&T.uniformMatrix2x3fv(X(a),!!c,y,d>>2,6*b)},$e:(a,b,c,d)=>{b&&T.uniformMatrix2x4fv(X(a),!!c,y,d>>2,8*b)},Pf:If,bf:(a,b,c,d)=>{b&&T.uniformMatrix3x2fv(X(a),!!c,y,d>>2,6*b)},
Ze:(a,b,c,d)=>{b&&T.uniformMatrix3x4fv(X(a),!!c,y,d>>2,12*b)},Of:Jf,_e:(a,b,c,d)=>{b&&T.uniformMatrix4x2fv(X(a),!!c,y,d>>2,8*b)},Ye:(a,b,c,d)=>{b&&T.uniformMatrix4x3fv(X(a),!!c,y,d>>2,12*b)},Nf:Kf,Mf:a=>{T.validateProgram(U[a])},Lf:(a,b)=>T.vertexAttrib1f(a,b),Kf:(a,b)=>{T.vertexAttrib1f(a,z.getFloat32(4*(b>>2),!0))},Jf:(a,b,c)=>T.vertexAttrib2f(a,b,c),If:(a,b)=>{T.vertexAttrib2f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0))},Hf:(a,b,c,d)=>T.vertexAttrib3f(a,b,c,d),Gf:(a,b)=>{T.vertexAttrib3f(a,
z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0))},Ff:(a,b,c,d,e)=>T.vertexAttrib4f(a,b,c,d,e),Ef:(a,b)=>{T.vertexAttrib4f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0),z.getFloat32(4*(b+12>>2),!0))},Kd:Lf,Cb:Lf,sd:Lf,yf:Lf,td:Lf,Ge:(a,b,c,d,e)=>T.vertexAttribI4i(a,b,c,d,e),Ee:(a,b)=>{T.vertexAttribI4i(a,z.getInt32(4*(b>>2),!0),z.getInt32(4*(b+4>>2),!0),z.getInt32(4*(b+8>>2),!0),z.getInt32(4*(b+12>>2),!0))},Fe:(a,b,c,d,e)=>T.vertexAttribI4ui(a,
b,c,d,e),De:(a,b)=>{T.vertexAttribI4ui(a,z.getUint32(4*(b>>2),!0),z.getUint32(4*(b+4>>2),!0),z.getUint32(4*(b+8>>2),!0),z.getUint32(4*(b+12>>2),!0))},Je:Mf,Df:Nf,Cf:Of,_d:(a,b,c)=>{c=Number(c);T.waitSync(Nd[a],b,c)},F:()=>1,Fb:()=>!0,cd:(a,b,c)=>{b={Zk:z.getInt32(4*(c>>2),!0),Dk:z.getInt32(4*(c+4>>2),!0),Ul:z.getInt32(4*(c+8>>2),!0),Ol:b,qk:z.getInt32(4*(c+12>>2),!0),il:z.getInt32(4*(c+16>>2),!0)};return Pf(a,b)},ma:(a,b)=>{a=N(a);return a?a.requestPointerLock?Ec()?Uc(a):b?(Cc(Uc,2,[a]),1):-2:-1:
-4},kh:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-xa.buffer.byteLength+65535)/65536|0;try{xa.grow(d);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Z:Qf,$:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Rf(a,b),ja:(a,b,c,d)=>Sf(a,b,c,d,12,"blur"),o:Mc,s:(a,b,c)=>{a=N(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},
ka:(a,b,c,d)=>Sf(a,b,c,d,13,"focus"),ha:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=N(a);if(!a)return-4;Tf(a,b,c,d,"webkitfullscreenchange");return Tf(a,b,c,d,"fullscreenchange")},D:(a,b,c)=>Qf()?-1:Uf(a,b,c,26,"gamepadconnected"),C:(a,b,c)=>Qf()?-1:Uf(a,b,c,27,"gamepaddisconnected"),da:(a,b,c,d)=>Vf(a,b,c,d,2,"keydown"),ba:(a,b,c,d)=>Vf(a,b,c,d,1,"keypress"),ca:(a,b,c,d)=>Vf(a,b,c,d,3,"keyup"),L:(a,b,c)=>{wc(()=>dynCall_v(a),b,c)},E:ic,ea:(a,b,c)=>window.screen&&screen.orientation?Wf(a,b,c):
-1,ia:(a,b,c,d)=>document.body?.requestPointerLock?(a=N(a))?Xf(a,b,c,d):-4:-1,ga:(a,b,c,d)=>Yf(a,b,c,d),aa:(a,b,c)=>Zf(a,b,c),fa:(a,b,c,d)=>(a=N(a))?"undefined"!=typeof a.onwheel?$f(a,b,c,d):-1:-4,ed:a=>document.title=a?C(w,a):"",u:function(a){return vd(()=>new Promise(b=>setTimeout(b,a)))},Eb:function(a,b,c,d,e){function f(v){t?v():uc(v)}var g=a+108,m=z.getUint32(4*(g+36>>2),!0),n=z.getUint32(4*(g+40>>2),!0),q=z.getUint32(4*(g+44>>2),!0),r=z.getUint32(4*(g+48>>2),!0),t=!!(z.getUint32(4*(g+52>>2),
!0)&64);dg(a,v=>{f(()=>{m?dynCall_vi(m,v):b?.(v)})},v=>{f(()=>{n?dynCall_vi(n,v):c?.(v)})},v=>{f(()=>{q?dynCall_vi(q,v):d?.(v)})},v=>{f(()=>{r?dynCall_vi(r,v):e?.(v)})});return a},kd:(a,b)=>{var c=b>>2,d=z.getInt32(4*(c+2),!0);b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:fg[d],failIfMajorPerformanceCaveat:!!u[b+12],rl:z.getInt32(4*(c+4),!0),dn:z.getInt32(4*(c+5),!0),Om:u[b+24],Sl:u[b+25],hn:z.getInt32(4*
(c+7),!0),mn:u[b+32]};a=N(a);return!a||b.Sl?0:Vd(a,b)},na:a=>{Wd==a&&(Wd=0);Wd===Kd[a]&&(Wd=null);"object"==typeof M&&M.pm(Kd[a].Yj.canvas);Kd[a]?.Yj.canvas&&(Kd[a].Yj.canvas.dk=void 0);Kd[a]=null},oa:a=>{Wd=Kd[a];h.ctx=T=Wd?.Yj;return!a||T?0:-5},Uc:(a,b)=>{var c=0,d=0,e;for(e of ig()){var f=b+c;z.setUint32(4*(a+d>>2),f,!0);c+=D(e,w,f,Infinity)+1;d+=4}return 0},Vc:(a,b)=>{var c=ig();z.setUint32(4*(a>>2),c.length,!0);a=0;for(var d of c)a+=Za(d)+1;z.setUint32(4*(b>>2),a,!0);return 0},v:a=>{na=a;kc(a)},
w:function(a){try{var b=L(a);l.close(b);return 0}catch(c){if("undefined"==typeof l||"ErrnoError"!==c.name)throw c;return c.dj}},jb:function(a,b){try{var c=L(a);u[b]=c.bj?2:H(c.mode)?3:40960===(c.mode&61440)?7:4;z.setInt16(2*(b+2>>1),0,!0);z.setBigInt64(8*(b+8>>3),BigInt(0),!0);z.setBigInt64(8*(b+16>>3),BigInt(0),!0);return 0}catch(d){if("undefined"==typeof l||"ErrnoError"!==d.name)throw d;return d.dj}},ra:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),
!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var q=l.read(e,u,m,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof f&&(f+=q)}r=b}z.setUint32(4*(d>>2),r,!0);return 0}catch(t){if("undefined"==typeof l||"ErrnoError"!==t.name)throw t;return t.dj}},vg:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=L(a);l.hj(e,b,c);z.setBigInt64(8*(d>>3),BigInt(e.position),!0);e.Qj&&0===b&&0===c&&(e.Qj=null);return 0}catch(f){if("undefined"==typeof l||
"ErrnoError"!==f.name)throw f;return f.dj}},sa:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var q=l.write(e,u,m,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof f&&(f+=q)}r=b}z.setUint32(4*(d>>2),r,!0);return 0}catch(t){if("undefined"==typeof l||"ErrnoError"!==t.name)throw t;return t.dj}},Nb:Xd,tc:Yd,H:Zd,A:$d,O:ae,Ic:be,xc:ce,wc:de,zc:ee,B:fe,Q:ge,Ac:he,Wb:ie,Vb:je,Rb:ke,W:le,uc:me,Ub:ne,Hc:oe,
T:pe,Cc:qe,R:re,G:se,U:te,ac:ue,Gc:ve,Ob:we,r:xe,Xb:ye,Kb:ze,Lb:Ae,Bc:Ce,Ib:De,Jb:Ee,q:Fe,$b:Ge,Dc:He,N:Ie,X:Je,Fc:Ke,Mc:Le,dc:Me,Jc:Ne,fc:Pe,l:Ve,gc:We,z:Xe,Qb:$e,P:af,k:cf,I:df,ec:gf,n:jf,y:kf,sc:of,M:pf,S:qf,Pb:sf,Nc:tf,Sb:uf,g:wf,h:xf,Lc:yf,V:zf,rc:Af,nc:Bf,qc:Cf,lc:Df,pc:Ef,kc:Ff,oc:Gf,jc:Hf,ic:If,hc:Jf,yc:Kf,Yb:Lf,Zb:Mf,_b:Nf,Hb:Of,f:Gg,j:Hg,x:Ig,K:Jg,e:Kg,a:Lg,c:Mg,d:Ng,p:Og,Ab:Pg,Gb:function(a,b){h.setStatus(a>=b?"":"Prefetching resources… ("+a+"/"+b+")",!0)}};
function Gg(a,b){var c=O();try{return Ag(a,b)}catch(d){Q(c);if(d!==d+0)throw d;zg(1,0)}}function Mg(a,b,c,d){var e=O();try{Bg(a,b,c,d)}catch(f){Q(e);if(f!==f+0)throw f;zg(1,0)}}function Og(a,b,c,d,e,f,g){var m=O();try{Eg(a,b,c,d,e,f,g)}catch(n){Q(m);if(n!==n+0)throw n;zg(1,0)}}function Lg(a,b,c){var d=O();try{dynCall_vii(a,b,c)}catch(e){Q(d);if(e!==e+0)throw e;zg(1,0)}}function Kg(a,b){var c=O();try{dynCall_vi(a,b)}catch(d){Q(c);if(d!==d+0)throw d;zg(1,0)}}
function Hg(a,b,c){var d=O();try{return dynCall_iii(a,b,c)}catch(e){Q(d);if(e!==e+0)throw e;zg(1,0)}}function Ng(a,b,c,d,e){var f=O();try{Cg(a,b,c,d,e)}catch(g){Q(f);if(g!==g+0)throw g;zg(1,0)}}function Pg(a,b,c,d,e,f,g,m,n,q){var r=O();try{Dg(a,b,c,d,e,f,g,m,n,q)}catch(t){Q(r);if(t!==t+0)throw t;zg(1,0)}}function Ig(a,b,c,d){var e=O();try{return R(a,b,c,d)}catch(f){Q(e);if(f!==f+0)throw f;zg(1,0)}}
function Jg(a,b,c,d,e){var f=O();try{return Fg(a,b,c,d,e)}catch(g){Q(f);if(g!==g+0)throw g;zg(1,0)}}function jg(a=[]){var b=yg;a.unshift(fa);var c=a.length,d=Jc(4*(c+1)),e=d,f;for(f of a){a=4*(e>>2);var g=Kc(f);z.setUint32(a,g,!0);e+=4}z.setUint32(4*(e>>2),0,!0);try{var m=b(c,d);na=m;kc(m);return m}catch(n){return lc(n)}}
function Rg(){function a(){h.calledRun=!0;if(!ma){va=!0;if(!h.noFSInit&&!l.Ok){var b,c;l.Ok=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?l.Ij("/dev","stdin",b):l.vj("/dev/tty","/dev/stdin");c?l.Ij("/dev","stdout",null,c):l.vj("/dev/tty","/dev/stdout");d?l.Ij("/dev","stderr",null,d):l.vj("/dev/tty1","/dev/stderr");l.open("/dev/stdin",0);l.open("/dev/stdout",1);l.open("/dev/stderr",1)}Sg.mh();l.pl=!1;oa?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var d=
h.postRun.shift();Fa.push(d)}Ea(Fa)}}if(0<pb)qb=Rg;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ha();Ea(Ga);0<pb?qb=Rg:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}var Sg;
Sg=await (async function(){function a(c){var d=Sg=c.exports;c={};for(let [e,f]of Object.entries(d))"function"==typeof f?(d=Wc(f),c[e]=d):c[e]=f;c=Sg=c;vg=h._Emscripten_force_free=c.nh;mg=h._SDL_malloc=c.oh;h._SDL_calloc=c.ph;h._SDL_realloc=c.qh;pg=h._SDL_free=c.rh;h._SDLEmscriptenCameraPermissionOutcome=c.sh;h._SDLEmscriptenThreadIterate=c.th;qg=h._Emscripten_HandlePointerEnter=c.uh;rg=h._Emscripten_HandlePointerLeave=c.vh;sg=h._Emscripten_HandlePointerGeneric=c.wh;og=h._Emscripten_HandleMouseButtonUpGlobal=
c.xh;tg=h._Emscripten_SendDragEvent=c.yh;xg=h._Emscripten_SendDragCompleteEvent=c.zh;ug=h._Emscripten_SendDragTextEvent=c.Ah;wg=h._Emscripten_SendDragFileEvent=c.Bh;ng=h._Emscripten_HandleLockKeysCheck=c.Ch;lg=h._Emscripten_SendSystemThemeChangedEvent=c.Dh;kg=h._requestFullscreenThroughSDL=c.Eh;h._vfs_sync_callback=c.Fh;yg=h._main=c.Gh;h._SDL_main=c.Hh;gb=c.Ih;pd=c.Jh;ud=c.Kh;eg=c.Lh;zg=c.Mh;cd=c.Nh;Q=c.Oh;Jc=c.Ph;O=c.Qh;B.iidiiii=c.Sh;dynCall_vii=B.vii=c.Th;R=B.iiii=c.Uh;B.jiji=c.Vh;Ag=B.ii=c.Wh;
dynCall_vi=B.vi=c.Xh;Bg=B.viii=c.Yh;B.vffff=c.Zh;Cg=B.viiii=c._h;B.vf=c.$h;B.viiiiiiii=c.ai;Dg=B.viiiiiiiii=c.bi;B.i=c.ci;B.vff=c.di;dynCall_v=B.v=c.ei;B.viiiii=c.fi;B.viiiiiii=c.gi;dynCall_iii=B.iii=c.hi;B.vfi=c.ii;B.viif=c.ji;B.vif=c.ki;B.viff=c.li;B.vifff=c.mi;B.viffff=c.ni;Eg=B.viiiiii=c.oi;B.vfff=c.pi;B.viiiiiiiiii=c.qi;B.viiiiiiiiiii=c.ri;B.viifi=c.si;B.iiij=c.ti;B.viij=c.ui;Fg=B.iiiii=c.vi;B.iiiiii=c.wi;B.ji=c.xi;B.viiifi=c.yi;B.iiiiiiiiiiii=c.zi;B.vd=c.Ai;B.iiiiiii=c.Bi;B.iiji=c.Ci;B.viidi=
c.Di;B.ff=c.Ei;B.iiif=c.Fi;B.iiiiiiiii=c.Gi;B.viiif=c.Hi;B.iiiiiiii=c.Ii;B.iiiiiiiiii=c.Ji;B.iiidd=c.Ki;B.id=c.Li;B.dd=c.Mi;B.d=c.Ni;B.iid=c.Oi;B.di=c.Pi;B.dii=c.Qi;sd=c.Ri;Zc=c.Si;dd=c.Ti;td=c.Ui;xa=c.lh;ea=c.Rh;wa();return Sg}var b={a:Qg};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});za??=h.locateFile?h.locateFile("taisei.wasm",ha):ha+"taisei.wasm";return a((await Ca(b)).instance)}());Rg();gg.TAISEI_NOASYNC="1";gg.TAISEI_NOUNLOAD="1";
gg.TAISEI_PREFER_SDL_VIDEODRIVERS="emscripten";gg.TAISEI_RENDERER="gles30";va?moduleRtn=h:moduleRtn=new Promise((a,b)=>{oa=a;pa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createTaisei;module.exports.default=createTaisei}else if(typeof define==="function"&&define["amd"])define([],()=>createTaisei);
