var h;h||=typeof Module != 'undefined' ? Module : {};var ba=document.getElementById("status"),ca=document.getElementById("progress"),da=document.getElementById("spinner"),ea=document.getElementById("canvas"),fa=document.getElementById("canvasContainer"),ha=document.getElementById("logToggle"),ia=document.getElementById("logToggleContainer"),ja=document.getElementById("logContainer"),ka=document.getElementById("output"),la=ba.innerText;ha.checked=!1;
window.toggleLog=function(){ja.hidden=!ha.checked;ka.scrollTop=ka.scrollHeight};var ma=ea.getContext("webgl2",{alpha:!1,antialias:!1,depth:!1,powerPreference:"high-performance",premultipliedAlpha:!0,preserveDrawingBuffer:!1,stencil:!1});if(!ma)throw"Could not create a WebGL 2 context";ma.getSupportedExtensions().forEach(function(a){ma.getExtension(a)});ea.addEventListener("webglcontextlost",function(a){alert("WebGL context lost. You will need to reload the page.");a.preventDefault()},!1);
ka.value="";
h={preRun:[function(){na.TAISEI_NOASYNC="1";na.TAISEI_NOUNLOAD="1";na.TAISEI_PREFER_SDL_VIDEODRIVERS="emscripten";na.TAISEI_RENDERER="gles30";k("/persistent");oa(l,"/persistent")}],postRun:[],onFirstFrame:function(){fa.hidden=!1;ia.style.display="inline-block";h.setStatus("",!0)},print:function(a){1<arguments.length&&(a=Array.prototype.slice.call(arguments).join(" "));console.log(a);ka.value+=a+"\n";ka.scrollTop=ka.scrollHeight},printErr:function(a){1<arguments.length&&(a=Array.prototype.slice.call(arguments).join(" "));console.error(a)},
canvas:ea,preinitializedWebGLContext:ma,setStatus:function(a,b){var c=h.setStatus;if(a||b)if(c.Ej||(c.Ej={time:Date.now(),text:""}),a!==c.Ej.text){b=a.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);var d=Date.now();b&&30>d-c.Ej.time||(c.Ej.time=d,c.Ej.text=a,b?(a=b[1],ca.value=100*parseInt(b[2]),ca.max=100*parseInt(b[4]),ca.hidden=!1,da.hidden=!ea.hidden):(ca.value=null,ca.max=null,ca.hidden=!0,a||(da.hidden=!0)),ba.innerText=a.replace(/^Downloading(?: data)?\.\.\./,la).replace("...","\u2026"),console.log("[STATUS] "+
ba.innerText))}},totalDependencies:0,monitorRunDependencies:function(a){h.totalDependencies=Math.max(h.totalDependencies,a);h.setStatus(a?"Preparing\u2026 ("+(h.totalDependencies-a)+"/"+h.totalDependencies+")":"All downloads complete.")}};window.onerror=function(a){h.setStatus("Error: "+a)};function qa(a,b){sa(a,function(c){h.ccall("vfs_sync_callback",null,["boolean","string","number"],[a,c,b],{async:!0})})}
(function(){function a(){var b=h.SDL2;"undefined"!==typeof b&&("suspended"==b.Wi.state&&b.Wi.resume(),"running"==b.Wi.state&&(ea.removeEventListener("click",a),document.removeEventListener("keydown",a)))}ea.addEventListener("click",a);document.addEventListener("keydown",a)})();"undefined"===typeof ta&&(ta=window.dynCall=h.dynCall=function(a,b,c){return ua.get(b).apply(this,c)});var va=Object.assign({},h),wa=[],ya="./this.program",za="",Aa;
"undefined"!=typeof document&&document.currentScript&&(za=document.currentScript.src);za=za.startsWith("blob:")?"":za.substr(0,za.replace(/[?#].*/,"").lastIndexOf("/")+1);Aa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var Ba=h.print||console.log.bind(console),Ca=h.printErr||console.error.bind(console);Object.assign(h,va);va=null;h.arguments&&(wa=h.arguments);h.thisProgram&&(ya=h.thisProgram);
var Da=h.wasmBinary,Ea,Fa=!1,Ga,t,v,Ha,Ia,Ja,Ka,w,x,z;function La(){var a=Ea.buffer;h.HEAP_DATA_VIEW=z=new DataView(a);h.HEAP8=t=new Int8Array(a);h.HEAP16=Ha=new Int16Array(a);h.HEAPU8=v=new Uint8Array(a);h.HEAPU16=Ia=new Uint16Array(a);h.HEAP32=Ja=new Int32Array(a);h.HEAPU32=Ka=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=new Float64Array(a);h.HEAP64=x=new BigInt64Array(a);h.HEAPU64=new BigUint64Array(a)}var Ma=[],Na=[],Oa=[],Pa=[];
function Qa(){var a=h.preRun.shift();Ma.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;h.monitorRunDependencies?.(Ra)}function Va(){Ra--;h.monitorRunDependencies?.(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}function Wa(a){h.onAbort?.(a);a="Aborted("+a+")";Ca(a);Fa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Xa=a=>a.startsWith("data:application/octet-stream;base64,"),Ya;
function Za(a){if(a==Ya&&Da)return new Uint8Array(Da);throw"both async and sync fetching of the wasm failed";}function $a(a){return Da?Promise.resolve().then(()=>Za(a)):Aa(a).then(b=>new Uint8Array(b),()=>Za(a))}function ab(a,b,c){return $a(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{Ca(`failed to asynchronously prepare wasm: ${d}`);Wa(d)})}
function bb(a,b){var c=Ya;Da||"function"!=typeof WebAssembly.instantiateStreaming||Xa(c)||"function"!=typeof fetch?ab(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){Ca(`wasm streaming compile failed: ${e}`);Ca("falling back to ArrayBuffer instantiation");return ab(c,a,b)}))}
var eb={1136224:(a,b)=>{qa(a,b)},1136244:(a,b)=>{alert((a?A(v,a):"")+"\n\n"+(b?A(v,b):""))},1136301:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1136448:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1136682:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Wi||("undefined"!==typeof AudioContext?b.Wi=new AudioContext:
"undefined"!==typeof webkitAudioContext&&(b.Wi=new webkitAudioContext),b.Wi&&cb(b.Wi));return void 0===b.Wi?-1:0},1137175:()=>h.SDL2.Wi.sampleRate,1137243:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Kj&&(clearTimeout(g.capture.Kj),g.capture.Kj=void 0);g.capture.Wj=g.Wi.createMediaStreamSource(m);g.capture.bj=g.Wi.createScriptProcessor(b,a,1);g.capture.bj.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.dk=n.inputBuffer,ta("vi",
c,[d]))};g.capture.Wj.connect(g.capture.bj);g.capture.bj.connect(g.Wi.destination);g.capture.stream=m}var g=h.SDL2;g.capture.bk=g.Wi.createBuffer(a,b,g.Wi.sampleRate);g.capture.bk.getChannelData(0).fill(0);g.capture.Kj=setTimeout(function(){g.capture.dk=g.capture.bk;ta("vi",c,[d])},b/g.Wi.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},f,e)},1138895:(a,b,c,d)=>{var e=h.SDL2;e.audio.bj=e.Wi.createScriptProcessor(b,0,a);e.audio.bj.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Bk=f.outputBuffer,ta("vi",c,[d]))};e.audio.bj.connect(e.Wi.destination)},1139305:(a,b)=>{for(var c=h.SDL2,d=c.capture.dk.numberOfChannels,e=0;e<d;++e){var f=c.capture.dk.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=
0;g<b;++g)db(a+4*g,f[g]);else for(g=0;g<b;++g)db(a+4*(g*d+e),f[g])}},1139910:(a,b)=>{for(var c=h.SDL2,d=c.audio.Bk.numberOfChannels,e=0;e<d;++e){var f=c.audio.Bk.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=z.getFloat32(4*(a+(g*d+e<<2)>>2),!0)}},1140390:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Kj&&clearTimeout(b.capture.Kj);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.bj&&(b.capture.bj.onaudioprocess=function(){},b.capture.bj.disconnect(),b.capture.bj=void 0);void 0!==b.capture.Wj&&(b.capture.Wj.disconnect(),b.capture.Wj=void 0);void 0!==b.capture.bk&&(b.capture.bk=void 0);b.capture=void 0}else void 0!=b.audio.bj&&(b.audio.bj.disconnect(),b.audio.bj=void 0),b.audio=void 0;void 0!==b.Wi&&void 0===b.audio&&void 0===b.capture&&(b.Wi.close(),b.Wi=void 0)},1141562:()=>
window.innerWidth,1141592:()=>window.innerHeight,1141623:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Wk!==h.canvas&&(d.hj=h.createContext(h.canvas,!1,!0),d.Wk=h.canvas);if(d.w!==a||d.h!==b||d.ll!==d.hj)d.image=d.hj.createImageData(a,b),d.w=a,d.h=b,d.ll=d.hj;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=z.getInt32(4*b,!0);a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.$k!==a&&(d.Zk=new Int32Array(a.buffer),
d.al=new Uint8Array(a.buffer),d.$k=a),a=d.Zk,c=a.length,a.set(Ja.subarray(b,b+c)),a=d.al,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.hj.putImageData(d.image,0,0)},1143092:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=z.getInt32(4*e,!0);b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(Ja.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=B(c.length+1);C(c,v,d,c.length+1);return d},1144081:a=>{h.canvas&&(h.canvas.style.cursor=a?A(v,a):"")},1144164:()=>{h.canvas&&(h.canvas.style.cursor="none")},1144233:()=>{h.onFirstFrame()}};
function fb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var gb=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},cb=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&gb(d,c,()=>{"suspended"===a.state&&a.resume()})})})},hb=a=>{for(;0<a.length;)a.shift()(h)},ib=h.noExitRuntime||!0;
function db(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a]=b;break;case "i8":t[a]=b;break;case "i16":z.setInt16(2*(a>>1),b,!0);break;case "i32":z.setInt32(4*(a>>2),b,!0);break;case "i64":x[a>>3]=BigInt(b);break;case "float":z.setFloat32(4*(a>>2),b,!0);break;case "double":z.setFloat64(8*(a>>3),b,!0);break;case "*":z.setUint32(4*(a>>2),b,!0);break;default:Wa(`invalid type for setValue: ${c}`)}}function jb(){var a=z.getInt32(4*(+kb>>2),!0);kb+=4;return a}
var mb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},nb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=mb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},pb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},qb=a=>{if("/"===
a)return"/";a=nb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},rb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);Wa("initRandomDevice")},sb=a=>(sb=rb())(a),tb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=mb(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},ub="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ub)return ub.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
vb=[],wb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},xb=[];function yb(a,b){xb[a]={input:[],$i:[],lj:b};zb(a,Ab)}
var Ab={open(a){var b=xb[a.node.Ij];if(!b)throw new D(43);a.Ui=b;a.seekable=!1},close(a){a.Ui.lj.Rj(a.Ui)},Rj(a){a.Ui.lj.Rj(a.Ui)},read(a,b,c,d){if(!a.Ui||!a.Ui.lj.Ek)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.Ui.lj.Ek(a.Ui)}catch(m){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Ui||!a.Ui.lj.nk)throw new D(60);try{for(var e=0;e<d;e++)a.Ui.lj.nk(a.Ui,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.timestamp=Date.now());return e}},Bb={Ek(){a:{if(!vb.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(wb(a)+1);a=C(a,b,0,b.length);b.length=a;vb=b}b=vb.shift()}return b},nk(a,b){null===b||10===b?(Ba(A(a.$i,0)),a.$i=[]):0!=b&&a.$i.push(b)},Rj(a){a.$i&&0<a.$i.length&&(Ba(A(a.$i,0)),a.$i=[])},ol(){return{Ml:25856,Ol:5,Ll:191,Nl:35387,Kl:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},pl(){return 0},ql(){return[24,80]}},Cb={nk(a,b){null===b||10===b?(Ca(A(a.$i,0)),a.$i=[]):0!=b&&a.$i.push(b)},Rj(a){a.$i&&0<a.$i.length&&(Ca(A(a.$i,0)),a.$i=[])}},Eb=a=>{a=65536*Math.ceil(a/65536);var b=Db(65536,a);b?(v.fill(0,b,b+a),a=b):a=0;return a};function Fb(a,b){var c=a.Ti?a.Ti.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ti,a.Ti=new Uint8Array(b),0<a.Vi&&a.Ti.set(c.subarray(0,a.Vi),0))}
var E={kj:null,Yi(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.kj||(E.kj={dir:{node:{jj:E.Ri.jj,cj:E.Ri.cj,Fj:E.Ri.Fj,wj:E.Ri.wj,ak:E.Ri.ak,Cj:E.Ri.Cj,Aj:E.Ri.Aj,$j:E.Ri.$j,Bj:E.Ri.Bj},stream:{uj:E.Si.uj}},file:{node:{jj:E.Ri.jj,cj:E.Ri.cj},stream:{uj:E.Si.uj,read:E.Si.read,write:E.Si.write,Nj:E.Si.Nj,Gj:E.Si.Gj,Yj:E.Si.Yj}},link:{node:{jj:E.Ri.jj,cj:E.Ri.cj,Jj:E.Ri.Jj},stream:{}},Ak:{node:{jj:E.Ri.jj,cj:E.Ri.cj},stream:Gb}});
c=Hb(a,b,c,d);F(c.mode)?(c.Ri=E.kj.dir.node,c.Si=E.kj.dir.stream,c.Ti={}):32768===(c.mode&61440)?(c.Ri=E.kj.file.node,c.Si=E.kj.file.stream,c.Vi=0,c.Ti=null):40960===(c.mode&61440)?(c.Ri=E.kj.link.node,c.Si=E.kj.link.stream):8192===(c.mode&61440)&&(c.Ri=E.kj.Ak.node,c.Si=E.kj.Ak.stream);c.timestamp=Date.now();a&&(a.Ti[b]=c,a.timestamp=c.timestamp);return c},Ri:{jj(a){var b={};b.cl=8192===(a.mode&61440)?a.id:1;b.ml=a.id;b.mode=a.mode;b.vl=1;b.uid=0;b.il=0;b.Ij=a.Ij;F(a.mode)?b.size=4096:32768===(a.mode&
61440)?b.size=a.Vi:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Sk=new Date(a.timestamp);b.Zj=new Date(a.timestamp);b.Vk=new Date(a.timestamp);b.Tk=4096;b.Uk=Math.ceil(b.size/b.Tk);return b},cj(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Vi!=b))if(0==b)a.Ti=null,a.Vi=0;else{var c=a.Ti;a.Ti=new Uint8Array(b);c&&a.Ti.set(c.subarray(0,Math.min(b,a.Vi)));a.Vi=b}},Fj(){throw Ib[44];},wj(a,b,c,d){return E.createNode(a,b,
c,d)},ak(a,b,c){if(F(a.mode)){try{var d=Jb(b,c)}catch(f){}if(d)for(var e in d.Ti)throw new D(55);}delete a.parent.Ti[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ti[c]=a;b.timestamp=a.parent.timestamp},Cj(a,b){delete a.Ti[b];a.timestamp=Date.now()},Aj(a,b){var c=Jb(a,b),d;for(d in c.Ti)throw new D(55);delete a.Ti[b];a.timestamp=Date.now()},$j(a){var b=[".",".."],c;for(c of Object.keys(a.Ti))b.push(c);return b},Bj(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},Jj(a){if(40960!==(a.mode&61440))throw new D(28);
return a.link}},Si:{read(a,b,c,d,e){var f=a.node.Ti;if(e>=a.node.Vi)return 0;a=Math.min(a.node.Vi-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ti||a.Ti.subarray)){if(f)return a.Ti=b.subarray(c,c+d),a.Vi=d;if(0===a.Vi&&0===e)return a.Ti=b.slice(c,c+d),a.Vi=d;if(e+d<=a.Vi)return a.Ti.set(b.subarray(c,c+d),e),d}Fb(a,e+d);if(a.Ti.subarray&&
b.subarray)a.Ti.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ti[e+f]=b[c+f];a.Vi=Math.max(a.Vi,e+d);return d},uj(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Vi);if(0>b)throw new D(28);return b},Nj(a,b,c){Fb(a.node,b+c);a.node.Vi=Math.max(a.node.Vi,b+c)},Gj(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.Ti;if(e&2||!a||a.buffer!==t.buffer){d=!0;e=Eb(b);if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{Mk:e,mj:d}},Yj(a,b,c,d){E.Si.write(a,b,0,d,c,!1);return 0}}},Kb=(a,b,c)=>{var d=`al ${a}`;Aa(a).then(e=>{b(new Uint8Array(e));d&&Va(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ua(d)},Lb=h.preloadPlugins||[],Ob=(a,b,c,d)=>{"undefined"!=typeof Mb&&Nb();var e=!1;Lb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Qb=(a,b,c,d,e,f,g,m,n,p)=>{function q(H){function Z(pa){p?.();m||Pb(a,b,pa,d,e,n);f?.();Va(u)}
Ob(H,r,Z,()=>{g?.();Va(u)})||Z(H)}var r=b?tb(nb(a+"/"+b)):a,u=`cp ${r}`;Ua(u);"string"==typeof c?Kb(c,q,g):q(c)},Rb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},l={Qj:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);return a},Pk:21,qj:"FILE_DATA",zj:a=>{function b(){"again"===a.tj?c():a.tj=0}function c(){a.tj="idb";l.Lj(a,!1,b)}a.tj?"idb"===a.tj&&(a.tj=
"again"):a.tj=setTimeout(c,0)},Yi:a=>{var b=E.Yi(a);if(a?.wl?.Il){b.tj=0;var c=b.Ri;b.Ri=Object.assign({},b.Ri);b.Ri.wj=(d,e,f,g)=>{var m=c.wj(d,e,f,g);m.Ri=b.Ri;m.kl=b.Yi;m.lk=m.Si;m.Si=Object.assign({},m.Si);m.Si.write=(n,p,q,r,u,H)=>{n.node.Hk=!0;return m.lk.write(n,p,q,r,u,H)};m.Si.close=n=>{var p=n.node;p.Hk&&(l.zj(p.kl),p.Hk=!1);if(p.lk.close)return p.lk.close(n)};return m};b.Ri.ul=(...d)=>(l.zj(b.Yi),c.ul(...d));b.Ri.Aj=(...d)=>(l.zj(b.Yi),c.Aj(...d));b.Ri.Bj=(...d)=>(l.zj(b.Yi),c.Bj(...d));
b.Ri.Cj=(...d)=>(l.zj(b.Yi),c.Cj(...d));b.Ri.ak=(...d)=>(l.zj(b.Yi),c.ak(...d))}return b},Lj:(a,b,c)=>{l.gl(a,(d,e)=>{if(d)return c(d);l.hl(a,(f,g)=>{if(f)return c(f);l.yl(b?g:e,b?e:g,c)})})},am:()=>{Object.values(l.Qj).forEach(a=>a.close());l.Qj={}},fl:(a,b)=>{var c=l.Qj[a];if(c)return b(null,c);try{var d=l.indexedDB().open(a,l.Pk)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(l.qj)?
g=e.objectStore(l.qj):g=f.createObjectStore(l.qj);g.indexNames.contains("timestamp")||g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;l.Qj[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},gl:(a,b)=>{function c(m){return"."!==m&&".."!==m}function d(m){return n=>nb(m+"/"+n)}var e={};for(a=Sb(a.Hj).filter(c).map(d(a.Hj));a.length;){var f=a.pop();try{var g=Tb(f)}catch(m){return b(m)}F(g.mode)&&a.push(...Sb(f).filter(c).map(d(f)));e[f]={timestamp:g.Zj}}return b(null,
{type:"local",entries:e})},hl:(a,b)=>{var c={};l.fl(a.Hj,(d,e)=>{if(d)return b(d);try{var f=e.transaction([l.qj],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(l.qj).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},sl:(a,b)=>{try{var c=G(a).node;var d=Tb(a)}catch(f){return b(f)}if(F(d.mode))return b(null,{timestamp:d.Zj,mode:d.mode});
if(32768===(d.mode&61440)){a=c;var e=c.Ti?c.Ti.subarray?c.Ti.subarray(0,c.Vi):new Uint8Array(c.Ti):new Uint8Array(0);a.Ti=e;return b(null,{timestamp:d.Zj,mode:d.mode,contents:c.Ti})}return b(Error("node type not supported"))},Dl:(a,b,c)=>{try{if(F(b.mode))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{k(f,d)}catch(u){if(20!=u.Xi)throw u;}}}else if(32768===(b.mode&61440)){f=b.contents;d={yk:!0};d.flags=d.flags||577;g=Ub(a,d.flags,d.mode);if("string"==typeof f){var m=
new Uint8Array(wb(f)+1),n=C(f,m,0,m.length);Wb(g,m,0,n,void 0,d.yk)}else if(ArrayBuffer.isView(f))Wb(g,f,0,f.byteLength,void 0,d.yk);else throw Error("Unsupported data type");Xb(g)}else return c(Error("node type not supported"));Yb(a,b.mode);var p=b.timestamp,q=b.timestamp,r=G(a,{vj:!0}).node;r.Ri.cj(r,{timestamp:Math.max(p,q)})}catch(u){return c(u)}c(null)},Al:(a,b)=>{try{var c=Tb(a);F(c.mode)?Zb(a):32768===(c.mode&61440)&&$b(a)}catch(d){return b(d)}b(null)},tl:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>
c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},El:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},Bl:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},yl:(a,b,c)=>{function d(q){if(q&&!m)return m=!0,c(q)}var e=0,f=[];Object.keys(a.entries).forEach(q=>{var r=a.entries[q],u=b.entries[q];u&&r.timestamp.getTime()==u.timestamp.getTime()||(f.push(q),
e++)});var g=[];Object.keys(b.entries).forEach(q=>{a.entries[q]||(g.push(q),e++)});if(!e)return c(null);var m=!1,n=("remote"===a.type?a.db:b.db).transaction([l.qj],"readwrite"),p=n.objectStore(l.qj);n.onerror=n.onabort=q=>{d(q.target.error);q.preventDefault()};n.oncomplete=()=>{m||c(null)};f.sort().forEach(q=>{"local"===b.type?l.tl(p,q,(r,u)=>{if(r)return d(r);l.Dl(q,u,d)}):l.sl(q,(r,u)=>{if(r)return d(r);l.El(p,q,u,d)})});g.sort().reverse().forEach(q=>{"local"===b.type?l.Al(q,d):l.Bl(p,q,d)})}},
ac=null,bc={},cc=[],dc=1,ec=null,fc=!1,gc=!0,D=class{constructor(a){this.name="ErrnoError";this.Xi=a}},Ib={},hc=0,ic={},jc=class{constructor(){this.aj={};this.node=null}get flags(){return this.aj.flags}set flags(a){this.aj.flags=a}get position(){return this.aj.position}set position(a){this.aj.position=a}},kc=class{constructor(a,b,c,d){a||=this;this.parent=a;this.Yi=a.Yi;this.xj=null;this.id=dc++;this.name=b;this.mode=c;this.Ri={};this.Si={};this.Ij=d}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get rl(){return F(this.mode)}get Gk(){return 8192===(this.mode&61440)}};
function G(a,b={}){a=tb(a);if(!a)return{path:"",node:null};b=Object.assign({Dk:!0,pk:0},b);if(8<b.pk)throw new D(32);a=a.split("/").filter(g=>!!g);for(var c=ac,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Jb(c,a[e]);d=nb(d+"/"+a[e]);c.xj&&(!f||f&&b.Dk)&&(c=c.xj.root);if(!f||b.vj)for(f=0;40960===(c.mode&61440);)if(c=lc(d),d=tb(pb(d),c),c=G(d,{pk:b.pk+1}).node,40<f++)throw new D(32);}return{path:d,node:c}}
function mc(a){for(var b;;){if(a===a.parent)return a=a.Yi.Hj,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function nc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ec.length}function oc(a){var b=nc(a.parent.id,a.name);if(ec[b]===a)ec[b]=a.yj;else for(b=ec[b];b;){if(b.yj===a){b.yj=a.yj;break}b=b.yj}}
function Jb(a,b){var c=F(a.mode)?(c=pc(a,"x"))?c:a.Ri.Fj?0:2:54;if(c)throw new D(c);for(c=ec[nc(a.id,b)];c;c=c.yj){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ri.Fj(a,b)}function Hb(a,b,c,d){a=new kc(a,b,c,d);b=nc(a.parent.id,a.name);a.yj=ec[b];return ec[b]=a}function F(a){return 16384===(a&61440)}function qc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function pc(a,b){if(gc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function rc(a,b){try{return Jb(a,b),20}catch(c){}return pc(a,"wx")}function sc(a,b,c){try{var d=Jb(a,b)}catch(e){return e.Xi}if(a=pc(a,"wx"))return a;if(c){if(!F(d.mode))return 54;if(d===d.parent||"/"===mc(d))return 10}else if(F(d.mode))return 31;return 0}function J(a){a=cc[a];if(!a)throw new D(8);return a}
function tc(a,b=-1){a=Object.assign(new jc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!cc[b])break a;throw new D(33);}a.fd=b;return cc[b]=a}function uc(a,b=-1){a=tc(a,b);a.Si?.Tl?.(a);return a}var Gb={open(a){a.Si=bc[a.node.Ij].Si;a.Si.open?.(a)},uj(){throw new D(70);}};function zb(a,b){bc[a]={Si:b}}function vc(){for(var a=[],b=[ac.Yi];b.length;){var c=b.pop();a.push(c);b.push(...c.Jk)}return a}
function sa(a,b){function c(g){hc--;return b(g)}function d(g){if(g){if(!d.dl)return d.dl=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);hc++;1<hc&&Ca(`warning: ${hc} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vc(),f=0;e.forEach(g=>{if(!g.type.Lj)return d(null);g.type.Lj(g,a,d)})}
function oa(a,b){var c="/"===b;if(c&&ac)throw new D(10);if(!c&&b){var d=G(b,{Dk:!1});b=d.path;d=d.node;if(d.xj)throw new D(10);if(!F(d.mode))throw new D(54);}b={type:a,wl:{},Hj:b,Jk:[]};a=a.Yi(b);a.Yi=b;b.root=a;c?ac=a:d&&(d.xj=b,d.Yi&&d.Yi.Jk.push(b))}function wc(a,b,c){var d=G(a,{parent:!0}).node;a=qb(a);if(!a||"."===a||".."===a)throw new D(28);var e=rc(d,a);if(e)throw new D(e);if(!d.Ri.wj)throw new D(63);return d.Ri.wj(d,a,b,c)}function k(a,b){return wc(a,(void 0!==b?b:511)&1023|16384,0)}
function xc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return wc(a,b|8192,c)}function yc(a,b){if(!tb(a))throw new D(44);var c=G(b,{parent:!0}).node;if(!c)throw new D(44);b=qb(b);var d=rc(c,b);if(d)throw new D(d);if(!c.Ri.Bj)throw new D(63);c.Ri.Bj(c,b,a)}function Zb(a){var b=G(a,{parent:!0}).node;a=qb(a);var c=Jb(b,a),d=sc(b,a,!0);if(d)throw new D(d);if(!b.Ri.Aj)throw new D(63);if(c.xj)throw new D(10);b.Ri.Aj(b,a);oc(c)}
function Sb(a){a=G(a,{vj:!0}).node;if(!a.Ri.$j)throw new D(54);return a.Ri.$j(a)}function $b(a){var b=G(a,{parent:!0}).node;if(!b)throw new D(44);a=qb(a);var c=Jb(b,a),d=sc(b,a,!1);if(d)throw new D(d);if(!b.Ri.Cj)throw new D(63);if(c.xj)throw new D(10);b.Ri.Cj(b,a);oc(c)}function lc(a){a=G(a).node;if(!a)throw new D(44);if(!a.Ri.Jj)throw new D(28);return tb(mc(a.parent),a.Ri.Jj(a))}function Tb(a,b){a=G(a,{vj:!b}).node;if(!a)throw new D(44);if(!a.Ri.jj)throw new D(63);return a.Ri.jj(a)}
function zc(a){return Tb(a,!0)}function Yb(a,b){a="string"==typeof a?G(a,{vj:!0}).node:a;if(!a.Ri.cj)throw new D(63);a.Ri.cj(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ub(a,b,c){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=nb(a);try{e=G(a,{vj:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new D(20);}else e=wc(a,c,0),d=!0;if(!e)throw new D(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!F(e.mode))throw new D(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:F(e.mode)&&("r"!==qc(b)||b&512)?31:pc(e,qc(b)):44))throw new D(c);if(b&512&&!d){c=e;c="string"==typeof c?G(c,{vj:!0}).node:c;if(!c.Ri.cj)throw new D(63);if(F(c.mode))throw new D(31);if(32768!==(c.mode&61440))throw new D(28);if(d=pc(c,"w"))throw new D(d);c.Ri.cj(c,{size:0,timestamp:Date.now()})}b&=-131713;e=tc({node:e,path:mc(e),flags:b,seekable:!0,position:0,Si:e.Si,Fl:[],error:!1});e.Si.open&&e.Si.open(e);!h.logReadFiles||b&1||a in ic||(ic[a]=1);return e}
function Xb(a){if(null===a.fd)throw new D(8);a.sj&&(a.sj=null);try{a.Si.close&&a.Si.close(a)}catch(b){throw b;}finally{cc[a.fd]=null}a.fd=null}function Ac(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.Si.uj)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.Si.uj(a,b,c);a.Fl=[];return a.position}
function Wb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(F(a.node.mode))throw new D(31);if(!a.Si.write)throw new D(28);a.seekable&&a.flags&1024&&Ac(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.Si.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Bc(a,b){a="string"==typeof a?a:mc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=nb(a+"/"+c);try{k(d)}catch(e){}a=d}}return d}function Cc(a,b,c,d){a=nb(("string"==typeof a?a:mc(a))+"/"+b);c=Rb(c,d);return wc(a,(void 0!==c?c:438)&4095|32768,0)}
function Pb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:mc(a),g=b?nb(a+"/"+b):a);a=Rb(d,e);g=wc(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Yb(g,a|146);b=Ub(g,577);Wb(b,c,0,c.length,0,f);Xb(b);Yb(g,a)}}
function Dc(a,b,c,d){a=nb(("string"==typeof a?a:mc(a))+"/"+b);b=Rb(!!c,!!d);Dc.Ik??(Dc.Ik=64);var e=Dc.Ik++<<8|0;zb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var p=0,q=0;q<n;q++){try{var r=c()}catch(u){throw new D(29);}if(void 0===r&&0===p)throw new D(6);if(null===r||void 0===r)break;p++;g[m+q]=r}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(q){throw new D(29);}n&&(f.node.timestamp=Date.now());return p}});return xc(a,
b,e)}function Ec(a){if(!(a.Gk||a.rl||a.link||a.Ti)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.Ti=(void 0)(a.url),a.Vi=a.Ti.length}catch(b){throw new D(29);}}}
function Fc(a,b,c,d,e){function f(n,p,q,r,u){n=n.node.Ti;if(u>=n.length)return 0;r=Math.min(n.length-u,r);if(n.slice)for(var H=0;H<r;H++)p[q+H]=n[u+H];else for(H=0;H<r;H++)p[q+H]=n.get(u+H);return r}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Gk:!1,url:c};var g=Cc(a,b,d,e);c.Ti?g.Ti=c.Ti:c.url&&(g.Ti=null,g.url=c.url);Object.defineProperties(g,{Vi:{get:function(){return this.Ti.length}}});
var m={};Object.keys(g.Si).forEach(n=>{var p=g.Si[n];m[n]=(...q)=>{Ec(g);return p(...q)}});m.read=(n,p,q,r,u)=>{Ec(g);return f(n,p,q,r,u)};m.Gj=(n,p,q)=>{Ec(g);var r=Eb(p);if(!r)throw new D(48);f(n,t,r,p,q);return{Mk:r,mj:!0}};g.Si=m;return g}var K={},Gc=(a,b)=>a?A(v,a,b):"";function Hc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":J(a).path;if(0==b.length){if(!c)throw new D(44);return a}return nb(a+"/"+b)}
function Ic(a,b,c){a=a(b);z.setInt32(4*(c>>2),a.cl,!0);z.setInt32(4*(c+4>>2),a.mode,!0);z.setUint32(4*(c+8>>2),a.vl,!0);z.setInt32(4*(c+12>>2),a.uid,!0);z.setInt32(4*(c+16>>2),a.il,!0);z.setInt32(4*(c+20>>2),a.Ij,!0);x[c+24>>3]=BigInt(a.size);z.setInt32(4*(c+32>>2),4096,!0);z.setInt32(4*(c+36>>2),a.Uk,!0);b=a.Sk.getTime();var d=a.Zj.getTime(),e=a.Vk.getTime();x[c+40>>3]=BigInt(Math.floor(b/1E3));z.setUint32(4*(c+48>>2),b%1E3*1E6,!0);x[c+56>>3]=BigInt(Math.floor(d/1E3));z.setUint32(4*(c+64>>2),d%1E3*
1E6,!0);x[c+72>>3]=BigInt(Math.floor(e/1E3));z.setUint32(4*(c+80>>2),e%1E3*1E6,!0);x[c+88>>3]=BigInt(a.ml);return 0}
var kb=void 0,Jc=[0,31,60,91,121,152,182,213,244,274,305,335],Kc=[0,31,59,90,120,151,181,212,243,273,304,334],Lc=a=>{if(!(a instanceof fb||"unwind"==a))throw a;},Mc=0,Nc=a=>{Ga=a;ib||0<Mc||(h.onExit?.(a),Fa=!0);throw new fb(a);},Oc=a=>{Ga=a;Nc(a)},Pc=()=>{if(!(ib||0<Mc))try{var a=Ga;Ga=a;Nc(a)}catch(b){Lc(b)}},Qc=a=>{if(!Fa)try{a(),Pc()}catch(b){Lc(b)}},Rc=(a,b)=>setTimeout(()=>{Qc(a)},b),Sc=!1,Tc=!1,Uc=[];
function Nb(){function a(){Tc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Vc){Vc=!0;Lb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Wc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Wc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=
document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e?.(c)};n.onerror=()=>{Ca(`Image ${m} could not be decoded`);f?.()};n.src=m}});Lb.push({canHandle:function(c){return!h.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Wc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){Ca(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",q=0,r=0,u=0;u<c.length;u++)for(q=q<<8|c[u],r+=8;6<=r;){var H=q>>r-6&63;r-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[H]}2==r?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&3)<<4],p+="=="):4==r&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;Rc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Tc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Xc=!1,Yc=void 0,Zc=void 0;function $c(){if(!Sc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function Wc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ad=[];function bd(){var a=h.canvas;ad.forEach(b=>b(a.width,a.height))}
function cd(a,b,c){b&&c?(a.Gl=b,a.jl=c):(b=a.Gl,c=a.jl);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Zc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Mb={},Vc,L=12288,dd=!1,ed=0,fd=0,gd=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},hd={},jd,N,kd=1,ld=[],O=[],md=[],nd=[],od=[],P=[],pd=[],qd=[],Q=[],rd=[],sd=[],td=[],ud={},vd={},wd=4,xd=0,yd=a=>{for(var b=kd++,c=a.length;c<b;c++)a[c]=null;return b},zd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=N[c](),g=f&&yd(d);f&&(f.name=g,d[g]=f);z.setInt32(4*(b+4*e>>2),g,!0)}},Bd=(a,b)=>{if(h.preinitializedWebGLContext){var c=h.preinitializedWebGLContext;b.kk=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else a.aj||
(a.aj=a.getContext,a.getContext=function(d,e){e=a.aj(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=a.getContext("webgl2",b);return c?Ad(c,b):0},Ad=(a,b)=>{var c=yd(qd);b={handle:c,attributes:b,version:b.kk,rj:a};a.canvas&&(a.canvas.Dj=b);qd[c]=b;return c},Dd=a=>{Cd=qd[a];h.hj=N=Cd?.rj},Ed={},Cd,Fd=a=>{var b=wb(a)+1,c=B(b);c&&C(a,v,c,b);return c},Wd=(a,b,c,d,e)=>{function f(){return g<Gd?(Pc(),!1):!0}Hd=a;Id=d;var g=Gd;Jd=!1;Kd=function(){if(!Fa)if(0<Ld.length){var m=Ld.shift();
m.Xl(m.Hl);if(Md){var n=Md,p=0==n%1?n-1:Math.floor(n);Md=m.Ql?p:(8*n+(p+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=Md??0,p=Nd.Ul??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Kd,0)}else if(f())if(Od=Od+1|0,1==Pd&&1<Qd&&0!=Od%Qd)Rd();else{0==Pd&&(Sd=performance.now());a:if(!Fa){for(m of Td)if(!1===m())break a;Qc(a);for(n of Ud)n()}f()&&Rd()}};e||(b&&0<b?Vd(0,1E3/b):Vd(1,1),Rd());if(c)throw"unwind";},Jd=!1,Rd=null,
Gd=0,Hd=null,Id=0,Pd=0,Qd=0,Od=0,Ld=[],Td=[],Ud=[];function Xd(){Rd=null;Gd++}function Yd(){Gd++;var a=Pd,b=Qd,c=Hd;Hd=null;Wd(c,0,!1,Id,!0);Vd(a,b);Rd()}var Zd=0;function $d(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Zd)Zd=b+1E3/60;else for(;b+2>=Zd;)Zd+=1E3/60;setTimeout(a,Math.max(Zd-b,0))}}
var Nd={},Kd,Md,Sd,ae,Vd=(a,b)=>{Pd=a;Qd=b;if(Hd)if(Jd||=!0,0==a)Rd=function(){setTimeout(Kd,Math.max(0,Sd+b-performance.now())|0)};else if(1==a)Rd=function(){$d(Kd)};else if(2==a){if("undefined"==typeof ae)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);ae=d=>{c.push(d);postMessage("setimmediate","*")}}else ae=setImmediate;Rd=function(){ae(Kd)}}},be=[],ce=(a,b)=>{be.length=
0;for(var c;c=v[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;be.push(112==c?z.getUint32(4*(b>>2),!0):106==c?x[b>>3]:105==c?z.getInt32(4*(b>>2),!0):z.getFloat64(8*(b>>3),!0));b+=d?8:4}return be};function de(a){var b=R.fj[a];b.target.removeEventListener(b.Zi,b.Ck,b.dj);R.fj.splice(a,1)}function ee(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of R.nj)if(e.rk==a&&d(e.xk,c))return;R.nj.push({rk:a,Lk:b,xk:c});R.nj.sort((f,g)=>f.Lk<g.Lk)}
function fe(a){R.nj=R.nj.filter(b=>b.rk!=a)}function ge(){return navigator.userActivation?navigator.userActivation.isActive:R.ik&&R.Xk.Oj}function he(){if(ge()){var a=R.nj;R.nj=[];for(var b of a)b.rk(...b.xk)}}function ie(a){if(!a.target)return-4;if(a.ej)a.Ck=function(c){++R.ik;R.Xk=a;he();a.gj(c);he();--R.ik},a.target.addEventListener(a.Zi,a.Ck,a.dj),R.fj.push(a);else for(var b=0;b<R.fj.length;++b)R.fj[b].target==a.target&&R.fj[b].Zi==a.Zi&&de(b--);return 0}
function je(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={Jl:0,hk:0,jk:0,Xj:0,wk:0,tk:0,fk:0,Sl:0,$l:0,Rl:0,gk:0,mk:0,vk:0,sk:0,bm(){for(;R.fj.length;)de(R.fj.length-1);R.nj=[]},ik:0,nj:[],fj:[],zl:(a,b)=>{for(var c=0;c<R.fj.length;++c)R.fj[c].target!=a||b&&b!=R.fj[c].Zi||de(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},ke={},le=[0,document,window],S=a=>{a=2<a?a?A(v,a):"":a;return le[a]||document.querySelector(a)},ne=a=>{var b=wb(a)+1,c=me(b);C(a,v,c,b);return c},oe=a=>{var b=T(),c=me(8),d=c+4;a=ne(a.id);
if(a=S(a))z.setInt32(4*(c>>2),a.width,!0),z.setInt32(4*(d>>2),a.height,!0);c=[z.getInt32(4*(c>>2),!0),z.getInt32(4*(d>>2),!0)];U(b);return c},pe=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},qe=(a,b,c)=>{if(a.Pl){var d=T();a=ne(a.id);pe(a,b,c);U(d)}else a.width=b,a.height=c},re=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),qe(a,d,e),a.style.width=
f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=q,a.style.paddingTop=r,a.style.paddingBottom=u,a.style.marginLeft=H,a.style.marginRight=Z,a.style.marginTop=pa,a.style.marginBottom=aa,document.body.style.margin=lb,document.documentElement.style.overflow=Vb,document.body.scroll=y,a.style.pj=xa,a.Dj&&a.Dj.rj.viewport(0,0,d,e),ke.Pj&&V(ke.Pj,37,0,ke.zk))}var c=oe(a),d=c[0],e=
c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,q=a.style.paddingRight,r=a.style.paddingTop,u=a.style.paddingBottom,H=a.style.marginLeft,Z=a.style.marginRight,pa=a.style.marginTop,aa=a.style.marginBottom,lb=document.body.style.margin,Vb=document.documentElement.style.overflow,y=document.body.scroll,xa=a.style.pj;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},se=(a,b,
c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},te=a=>0>le.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ue=(a,b)=>{if(0!=b.qk||0!=b.ck){re(a);var c=b.Cl?innerWidth:screen.width,d=b.Cl?innerHeight:screen.height,e=te(a),f=e.width;e=e.height;var g=oe(a),m=g[0];g=g[1];3==b.qk?(se(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.qk&&(c*g<m*d?(f=g*c/m,se(a,(d-f)/2,0),d=f):(f=m*d/g,se(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");
let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.el&&(a.style.pj="optimizeSpeed",a.style.pj="-moz-crisp-edges",a.style.pj="-o-crisp-edges",a.style.pj="-webkit-optimize-contrast",a.style.pj="optimize-contrast",a.style.pj="crisp-edges",a.style.pj="pixelated");n=2==b.ck?devicePixelRatio:1;0!=b.ck&&(c=c*n|0,d=d*n|0,qe(a,c,d),a.Dj&&a.Dj.rj.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;ke=b;b.Pj&&V(b.Pj,37,0,b.zk);return 0},ve=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},we=a=>{try{a()}catch(b){Wa(b)}};
function xe(){var a=W,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{ye.push(c);try{return d(...e)}finally{if(!Fa&&(ye.pop(),X&&1===ze&&0===ye.length&&(ze=0,we(Ae),"undefined"!=typeof Be&&!Ce&&De))){Ce=!0;do{e=De;De=0;var f=z.getUint32(4*(e>>2),!0),g=z.getUint32(4*(e+4>>2),!0);Ee(f,g);U(z.getUint32(4*(e+8>>2),!0));f=z.getUint32(4*(e+12>>2),!0);0!==f?(X=null,z.setUint32(4*(e+12>>2),0,!0),dynCall_vi(f,z.getUint32(4*(e+16>>2),!0))):(X=e+=20,ze=2,Fe(e),Ge(e))}while(De);Ce=!1}}}:
d;return b}var ze=0,X=null,He=0,ye=[],Ie={},Je={},Ke=0,Le=null,Me=[];function Ne(){return new Promise((a,b)=>{Le={resolve:a,reject:b}})}function Oe(){var a=B(4108),b=a+12;z.setUint32(4*(a>>2),b,!0);z.setUint32(4*(a+4>>2),b+4096,!0);Pe(a);return a}function Pe(a){var b=ye[0],c=Ie[b];void 0===c&&(c=Ke++,Ie[b]=c,Je[c]=b);z.setInt32(4*(a+8>>2),c,!0)}function Ge(a){a=z.getInt32(4*(a+8>>2),!0);return(0,W[Je[a]])()}
function Qe(a){if(!Fa){if(0===ze){var b=!1,c=!1;a((d=0)=>{if(!Fa&&(He=d,b=!0,c)){ze=2;we(()=>Fe(X));"undefined"!=typeof Nd&&Hd&&Yd();d=!1;try{var e=Ge(X)}catch(m){e=m,d=!0}var f=!1;if(!X){var g=Le;g&&(Le=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(ze=1,X=Oe(),"undefined"!=typeof Nd&&Hd&&Xd(),we(()=>Re(X)))}else 2===ze?(ze=0,we(Se),Te(X),X=null,Me.forEach(Qc)):Wa(`invalid state: ${ze}`);return He}}
var De=0,Ce=!1,Be={},Ue=(a,b)=>{z.setFloat64(8*(a>>3),b.timestamp,!0);for(var c=0;c<b.axes.length;++c)z.setFloat64(8*(a+8*c+16>>3),b.axes[c],!0);for(c=0;c<b.buttons.length;++c)"object"==typeof b.buttons[c]?z.setFloat64(8*(a+8*c+528>>3),b.buttons[c].value,!0):z.setFloat64(8*(a+8*c+528>>3),b.buttons[c],!0);for(c=0;c<b.buttons.length;++c)t[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];t[a+1104]=b.connected;z.setInt32(4*(a+1108>>2),b.index,!0);z.setInt32(4*(a+8>>2),b.axes.length,
!0);z.setInt32(4*(a+12>>2),b.buttons.length,!0);C(b.id,v,a+1112,64);C(b.mapping,v,a+1176,64)},Ve=a=>N.activeTexture(a),We=(a,b)=>{N.attachShader(O[a],P[b])},Xe=(a,b,c)=>{N.bindAttribLocation(O[a],b,c?A(v,c):"")},Ye=(a,b)=>{35051==a?N.ek=b:35052==a&&(N.ij=b);N.bindBuffer(a,ld[b])},Ze=(a,b)=>{N.bindFramebuffer(a,md[b])},$e=(a,b)=>{N.bindTexture(a,od[b])},af=a=>{N.bindVertexArray(pd[a])},bf=(a,b)=>N.blendEquationSeparate(a,b),cf=(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),df=(a,b,c,d,e,f,g,m,n,p)=>N.blitFramebuffer(a,
b,c,d,e,f,g,m,n,p),ef=(a,b,c,d)=>{c&&b?N.bufferData(a,v,d,c,b):N.bufferData(a,b,d)},ff=(a,b,c,d)=>{c&&N.bufferSubData(a,b,v,d,c)},gf=a=>N.clear(a),hf=(a,b,c,d)=>N.clearColor(a,b,c,d),jf=a=>N.clearDepth(a),kf=a=>{N.compileShader(P[a])},lf=(a,b,c,d,e,f,g,m)=>{N.ij||!g?N.compressedTexImage2D(a,b,c,d,e,f,g,m):N.compressedTexImage2D(a,b,c,d,e,f,v,m,g)},mf=(a,b,c,d,e,f,g,m,n)=>{N.ij||!m?N.compressedTexSubImage2D(a,b,c,d,e,f,g,m,n):N.compressedTexSubImage2D(a,b,c,d,e,f,g,v,n,m)},nf=()=>{var a=yd(O),b=N.createProgram();
b.name=a;b.Vj=b.Tj=b.Uj=0;b.uk=1;O[a]=b;return a},of=a=>{var b=yd(P);P[b]=N.createShader(a);return b},pf=a=>N.cullFace(a),qf=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=ld[d];e&&(N.deleteBuffer(e),e.name=0,ld[d]=null,d==N.ek&&(N.ek=0),d==N.ij&&(N.ij=0))}},rf=(a,b)=>{for(var c=0;c<a;++c){var d=z.getInt32(4*(b+4*c>>2),!0),e=md[d];e&&(N.deleteFramebuffer(e),e.name=0,md[d]=null)}},sf=a=>{if(a){var b=O[a];b&&(N.deleteProgram(b),b.name=0,O[a]=null)}},tf=a=>{if(a){var b=P[a];b&&(N.deleteShader(b),
P[a]=null)}},uf=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=od[d];e&&(N.deleteTexture(e),e.name=0,od[d]=null)}},vf=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0);N.deleteVertexArray(pd[d]);pd[d]=null}},wf=a=>N.depthFunc(a),xf=a=>{N.depthMask(!!a)},yf=a=>N.disable(a),zf=a=>{N.disableVertexAttribArray(a)},Af=(a,b,c)=>{N.drawArrays(a,b,c)},Bf=(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},Cf=[],Df=(a,b)=>{for(var c=Cf[a],d=0;d<a;d++)c[d]=z.getInt32(4*(b+4*d>>2),!0);
N.drawBuffers(c)},Ef=(a,b,c,d)=>{N.drawElements(a,b,c,d)},Ff=(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},Gf=a=>N.enable(a),Hf=a=>{N.enableVertexAttribArray(a)},If=(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,od[d],e)},Jf=a=>N.frontFace(a),Kf=(a,b)=>{zd(a,b,"createBuffer",ld)},Lf=(a,b)=>{zd(a,b,"createFramebuffer",md)},Mf=(a,b)=>{zd(a,b,"createTexture",od)},Nf=(a,b)=>{zd(a,b,"createVertexArray",pd)},Of=a=>N.generateMipmap(a),Pf=(a,b,c,d,e,f,g,m)=>{b=O[b];if(a=N[a](b,c))d=m&&C(a.name,v,m,d),e&&
z.setInt32(4*(e>>2),d,!0),f&&z.setInt32(4*(f>>2),a.size,!0),g&&z.setInt32(4*(g>>2),a.type,!0)},Qf=(a,b,c,d,e,f,g)=>{Pf("getActiveUniform",a,b,c,d,e,f,g)},Rf=(a,b)=>{z.setUint32(4*(a>>2),b,!0);var c=z.getUint32(4*(a>>2),!0);z.setUint32(4*(a+4>>2),(b-c)/4294967296,!0)},Sf=()=>{var a="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(N.getSupportedExtensions()||[]).filter(b=>a.includes(b))};function Tf(){var a=Sf();return a=a.concat(a.map(b=>"GL_"+b))}
var Uf=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:return;case 34814:case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0;break;case 33309:d=Tf().length;break;case 33307:case 33308:d=33307==a?3:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z.setInt32(4*(b+4*a>>2),e[a],!0);break;case 2:z.setFloat32(4*(b+4*a>>2),e[a],!0);break;case 4:t[b+a]=e[a]?1:0}return}d=e.name|0}}switch(c){case 1:Rf(b,d);break;case 0:z.setInt32(4*(b>>2),d,!0);break;case 2:z.setFloat32(4*(b>>2),d,!0);break;case 4:t[b]=d?1:0}}},Vf=(a,b,c,d)=>{b=N.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=
b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:return}else if(b instanceof WebGLBuffer)a=b.name|0;else return;break;default:return}switch(d){case 1:Rf(c,a);break;case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;case 4:t[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}},Wf=(a,b)=>Uf(a,b,0),Xf=(a,b,c,d)=>{a=N.getProgramInfoLog(O[a]);b=0<b&&d?C(a,v,d,b):0;c&&z.setInt32(4*
(c>>2),b,!0)},Yf=(a,b,c)=>{if(c&&!(a>=kd))if(a=O[a],35716==b)z.setInt32(4*(c>>2),N.getProgramInfoLog(a).length+1,!0);else if(35719==b){if(!a.Vj){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Vj=Math.max(a.Vj,N.getActiveUniform(a,b).name.length+1)}z.setInt32(4*(c>>2),a.Vj,!0)}else if(35722==b){if(!a.Tj)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Tj=Math.max(a.Tj,N.getActiveAttrib(a,b).name.length+1);z.setInt32(4*(c>>2),a.Tj,!0)}else if(35381==b){if(!a.Uj)for(d=N.getProgramParameter(a,
35382),b=0;b<d;++b)a.Uj=Math.max(a.Uj,N.getActiveUniformBlockName(a,b).length+1);z.setInt32(4*(c>>2),a.Uj,!0)}else z.setInt32(4*(c>>2),N.getProgramParameter(a,b),!0)},Zf=(a,b,c)=>{if(c){a=Q[a];b=2>Cd.version?N.oj.getQueryObjectEXT(a,b):N.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Rf(c,d)}},$f=(a,b,c)=>{if(c){a=N.oj.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)}},ag=(a,b,c,d)=>{a=N.getShaderInfoLog(P[a]);b=0<b&&d?C(a,v,d,b):0;c&&z.setInt32(4*
(c>>2),b,!0)},bg=(a,b,c)=>{c&&(35716==b?(a=N.getShaderInfoLog(P[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):35720==b?(a=N.getShaderSource(P[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):z.setInt32(4*(c>>2),N.getShaderParameter(P[a],b),!0))},cg=a=>{var b=ud[a];if(!b){switch(a){case 7939:b=Fd(Tf().join(" "));break;case 7936:case 7937:case 37445:case 37446:b=(b=N.getParameter(a))?Fd(b):0;break;case 7938:b=Fd(`OpenGL ES 3.0 (${N.getParameter(7938)})`);break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Fd(b)}ud[a]=b}return b},dg=(a,b)=>{if(2>Cd.version)return 0;var c=vd[a];if(c)return 0>b||b>=c.length?0:c[b];switch(a){case 7939:return c=Tf().map(Fd),c=vd[a]=c,0>b||b>=c.length?0:c[b];default:return 0}},eg=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),fg=a=>{var b=a.Mj,c=a.Ok,d;if(!b){a.Mj=b={};a.Nk={};var e=N.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=N.getActiveUniform(a,d);var g=f.name;f=f.size;var m=eg(g);m=0<m?
g.slice(0,m):g;var n=a.uk;a.uk+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Nk[n++]=m}}},gg=(a,b)=>{b=b?A(v,b):"";if(a=O[a]){fg(a);var c=a.Mj,d=0,e=b,f=eg(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ok[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}return-1},Y=a=>{var b=N.Yk,c=b.Mj[a];"number"==typeof c&&(b.Mj[a]=c=N.getUniformLocation(b,b.Nk[a]+(0<c?`[${c}]`:"")));return c},hg=(a,b,c,d)=>{if(c)if(a=O[a],fg(a),a=N.getUniform(a,Y(b)),"number"==typeof a||"boolean"==
typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0)}},ig=(a,b,c)=>{hg(a,b,c,2)},jg=(a,b,c)=>{hg(a,b,c,0)},kg=(a,b,c,d)=>{if(c)if(a=N.getVertexAttrib(a,b),34975==b)z.setInt32(4*(c>>2),a&&a.name,!0);else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;
case 5:d=Math.fround(a),z.setInt32(4*(c>>2),d,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0);break;case 5:var e=Math.fround(a[b]);z.setInt32(4*(c+4*b>>2),e,!0)}},lg=(a,b,c)=>{kg(a,b,c,0)},mg=a=>(a=pd[a])?N.isVertexArray(a):0,ng=a=>{a=O[a];N.linkProgram(a);a.Mj=0;a.Ok={}},og=(a,b)=>{3317==a?wd=b:3314==a&&(xd=b);N.pixelStorei(a,b)},pg=a=>N.readBuffer(a),qg=a=>{a-=5120;return 0==a?t:1==a?v:2==a?Ha:4==a?Ja:6==a?w:5==a||
28922==a||28520==a||30779==a||30782==a?Ka:Ia},rg=(a,b,c,d,e)=>{a=qg(a);b=d*((xd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+wd-1&-wd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},sg=(a,b,c,d,e,f,g)=>{if(N.ek)N.readPixels(a,b,c,d,e,f,g);else{var m=qg(f);g>>>=31-Math.clz32(m.BYTES_PER_ELEMENT);N.readPixels(a,b,c,d,e,f,m,g)}},tg=(a,b,c,d)=>N.scissor(a,b,c,d),ug=(a,b,c,d)=>{for(var e="",f=0;f<
b;++f){var g=d?z.getUint32(4*(d+4*f>>2),!0):void 0;e+=Gc(z.getUint32(4*(c+4*f>>2),!0),g)}N.shaderSource(P[a],e)},vg=(a,b,c,d,e,f,g,m,n)=>{if(N.ij)N.texImage2D(a,b,c,d,e,f,g,m,n);else if(n){var p=qg(m);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,d,e,f,g,m,p,n)}else p=n?rg(m,g,d,e,n):null,N.texImage2D(a,b,c,d,e,f,g,m,p)},wg=(a,b,c)=>N.texParameteri(a,b,c),xg=(a,b,c,d,e,f,g,m,n)=>{if(N.ij)N.texSubImage2D(a,b,c,d,e,f,g,m,n);else if(n){var p=qg(m);N.texSubImage2D(a,b,c,d,e,f,g,m,p,n>>>31-
Math.clz32(p.BYTES_PER_ELEMENT))}else n=n?rg(m,g,e,f,n):null,N.texSubImage2D(a,b,c,d,e,f,g,m,n)},yg=(a,b,c)=>{b&&N.uniform1fv(Y(a),w,c>>2,b)},zg=(a,b,c)=>{b&&N.uniform1iv(Y(a),Ja,c>>2,b)},Ag=(a,b,c)=>{b&&N.uniform2fv(Y(a),w,c>>2,2*b)},Bg=(a,b,c)=>{b&&N.uniform2iv(Y(a),Ja,c>>2,2*b)},Cg=(a,b,c)=>{b&&N.uniform3fv(Y(a),w,c>>2,3*b)},Dg=(a,b,c)=>{b&&N.uniform3iv(Y(a),Ja,c>>2,3*b)},Eg=(a,b,c)=>{b&&N.uniform4fv(Y(a),w,c>>2,4*b)},Fg=(a,b,c)=>{b&&N.uniform4iv(Y(a),Ja,c>>2,4*b)},Gg=(a,b,c,d)=>{b&&N.uniformMatrix3fv(Y(a),
!!c,w,d>>2,9*b)},Hg=(a,b,c,d)=>{b&&N.uniformMatrix4fv(Y(a),!!c,w,d>>2,16*b)},Ig=a=>{a=O[a];N.useProgram(a);N.Yk=a},Jg=(a,b)=>{N.vertexAttribDivisor(a,b)},Kg=(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Lg=(a,b,c,d,e,f)=>{N.vertexAttribPointer(a,b,c,!!d,e,f)},Mg=(a,b,c,d)=>N.viewport(a,b,c,d),Ng=(a,b)=>{if(!R.fullscreenEnabled())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ge()?ue(a,b):b.bl?(ee(ue,1,[a,b]),1):-2:-3:-4},Og=()=>{try{if(navigator.getGamepads)return(R.Sj=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Pg=(a,b)=>{var c={target:S(2),Zi:"beforeunload",ej:b,gj:(d=event)=>{var e=V(b,28,0,a);e&&=e?A(v,e):"";if(e)return d.preventDefault(),d.returnValue=e},dj:!0};return ie(c)},Qg=(a,b,c,d,e,f)=>{R.fk||(R.fk=B(256));a={target:S(a),Zi:f,ej:d,gj:(g=event)=>{var m=g.target.id?g.target.id:"",n=R.fk;C(je(g.target),v,n+0,128);C(m,v,n+128,128);V(d,e,n,b)&&g.preventDefault()},dj:c};return ie(a)},Rg=(a,b,c,d,e)=>{R.gk||(R.gk=B(276));return ie({target:a,
Zi:e,ej:d,gj:(f=event)=>{var g=R.gk,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;t[g]=n;t[g+1]=R.fullscreenEnabled();var p=n?m:R.xl,q=p?.id||"";C(je(p),v,g+2,128);C(q,v,g+130,128);z.setInt32(4*(g+260>>2),p?p.clientWidth:0,!0);z.setInt32(4*(g+264>>2),p?p.clientHeight:0,!0);z.setInt32(4*(g+268>>2),screen.width,!0);z.setInt32(4*(g+272>>2),screen.height,!0);n&&(R.xl=m);V(d,19,g,b)&&f.preventDefault()},dj:c})},Sg=(a,b,
c,d,e)=>{R.hk||(R.hk=B(1240));b={target:S(2),Oj:!0,Zi:e,ej:c,gj:(f=event)=>{var g=R.hk;Ue(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},dj:b};return ie(b)},Tg=(a,b,c,d,e,f)=>{R.jk||(R.jk=B(160));a={target:S(a),Zi:f,ej:d,gj:g=>{var m=R.jk;z.setFloat64(8*(m>>3),g.timeStamp,!0);var n=m>>2;z.setInt32(4*(n+2),g.location,!0);t[m+12]=g.ctrlKey;t[m+13]=g.shiftKey;t[m+14]=g.altKey;t[m+15]=g.metaKey;t[m+16]=g.repeat;z.setInt32(4*(n+5),g.charCode,!0);z.setInt32(4*(n+6),g.keyCode,!0);z.setInt32(4*(n+7),g.which,
!0);C(g.key||"",v,m+32,32);C(g.code||"",v,m+64,32);C(g.char||"",v,m+96,32);C(g.locale||"",v,m+128,32);V(d,e,m,b)&&g.preventDefault()},dj:c};return ie(a)},Ug=(a,b,c)=>{z.setFloat64(8*(a>>3),b.timeStamp,!0);var d=a>>2;z.setInt32(4*(d+2),b.screenX,!0);z.setInt32(4*(d+3),b.screenY,!0);z.setInt32(4*(d+4),b.clientX,!0);z.setInt32(4*(d+5),b.clientY,!0);t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;z.setInt16(2*(2*d+14),b.button,!0);z.setInt16(2*(2*d+15),b.buttons,!0);z.setInt32(4*
(d+8),b.movementX,!0);z.setInt32(4*(d+9),b.movementY,!0);a=te(c);z.setInt32(4*(d+10),b.clientX-(a.left|0),!0);z.setInt32(4*(d+11),b.clientY-(a.top|0),!0)},Vg=(a,b,c,d,e,f)=>{R.Xj||(R.Xj=B(64));a=S(a);return ie({target:a,Oj:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Zi:f,ej:d,gj:(g=event)=>{Ug(R.Xj,g,a);V(d,e,R.Xj,b)&&g.preventDefault()},dj:c})},Wg=(a,b,c,d,e)=>{R.mk||(R.mk=B(257));return ie({target:a,Zi:e,ej:d,gj:(f=event)=>{var g=R.mk,m=document.pointerLockElement||document.aj||document.Rk||
document.Qk;t[g]=!!m;var n=m?.id||"";C(je(m),v,g+1,128);C(n,v,g+129,128);V(d,20,g,b)&&f.preventDefault()},dj:c})},Xg=(a,b,c,d)=>{R.tk||(R.tk=B(36));a=S(a);return ie({target:a,Zi:"resize",ej:d,gj:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.tk;z.setInt32(4*(g>>2),0,!0);z.setInt32(4*(g+4>>2),f.clientWidth,!0);z.setInt32(4*(g+8>>2),f.clientHeight,!0);z.setInt32(4*(g+12>>2),innerWidth,!0);z.setInt32(4*(g+16>>2),innerHeight,!0);z.setInt32(4*(g+20>>2),outerWidth,!0);z.setInt32(4*(g+24>>
2),outerHeight,!0);z.setInt32(4*(g+28>>2),pageXOffset|0,!0);z.setInt32(4*(g+32>>2),pageYOffset|0,!0);V(d,10,g,b)&&e.preventDefault()}}},dj:c})},Yg=(a,b,c,d,e,f)=>{R.sk||(R.sk=B(1552));a=S(a);return ie({target:a,Oj:"touchstart"==f||"touchend"==f,Zi:f,ej:d,gj:g=>{var m={},n=g.touches;for(var p of n)p.Fk=p.Kk=0,m[p.identifier]=p;for(var q of g.changedTouches)q.Fk=1,m[q.identifier]=q;for(var r of g.targetTouches)m[r.identifier].Kk=1;n=R.sk;z.setFloat64(8*(n>>3),g.timeStamp,!0);t[n+12]=g.ctrlKey;t[n+13]=
g.shiftKey;t[n+14]=g.altKey;t[n+15]=g.metaKey;p=n+16;q=te(a);r=0;for(let u of Object.values(m))if(m=p>>2,z.setInt32(4*m,u.identifier,!0),z.setInt32(4*(m+1),u.screenX,!0),z.setInt32(4*(m+2),u.screenY,!0),z.setInt32(4*(m+3),u.clientX,!0),z.setInt32(4*(m+4),u.clientY,!0),z.setInt32(4*(m+5),u.pageX,!0),z.setInt32(4*(m+6),u.pageY,!0),t[p+28]=u.Fk,t[p+29]=u.Kk,z.setInt32(4*(m+8),u.clientX-(q.left|0),!0),z.setInt32(4*(m+9),u.clientY-(q.top|0),!0),p+=48,31<++r)break;z.setInt32(4*(n+8>>2),r,!0);V(d,e,n,b)&&
g.preventDefault()},dj:c})},Zg=(a,b,c)=>{var d=le[1];R.vk||(R.vk=B(8));return ie({target:d,Zi:"visibilitychange",ej:c,gj:(e=event)=>{var f=R.vk,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);t[f]=document.hidden;z.setInt32(4*(f+4>>2),g,!0);V(c,21,f,a)&&e.preventDefault()},dj:b})},$g=(a,b,c,d)=>{R.wk||(R.wk=B(96));return ie({target:a,Oj:!0,Zi:"wheel",ej:d,gj:(e=event)=>{var f=R.wk;Ug(f,e,a);z.setFloat64(8*(f+64>>3),e.deltaX,!0);z.setFloat64(8*(f+72>>3),e.deltaY,!0);
z.setFloat64(8*(f+80>>3),e.deltaZ,!0);z.setInt32(4*(f+88>>2),e.deltaMode,!0);V(d,9,f,b)&&e.preventDefault()},dj:c})};class ah{constructor(){this.mj=[void 0];this.aj=[]}get(a){return this.mj[a]}has(a){return void 0!==this.mj[a]}Nj(a){var b=this.aj.pop()||this.mj.length;this.mj[b]=a;return b}}var bh;
function ch(a,b,c,d,e){function f(){var I=0,ra=0;y.response&&lb&&0===z.getUint32(4*(a+12>>2),!0)&&(ra=y.response.byteLength);0<ra&&(I=B(ra),v.set(new Uint8Array(y.response),I));z.setUint32(4*(a+12>>2),I,!0);Rf(a+16,ra);Rf(a+24,0);(I=y.response?y.response.byteLength:0)&&Rf(a+32,I);z.setInt16(2*(a+40>>1),y.readyState,!0);z.setInt16(2*(a+42>>1),y.status,!0);y.statusText&&C(y.statusText,v,a+44,64)}var g=z.getUint32(4*(a+8>>2),!0);if(g){var m=g?A(v,g):"",n=a+108,p=Gc(n+0);p||="GET";var q=z.getUint32(4*
(n+56>>2),!0),r=z.getUint32(4*(n+68>>2),!0),u=z.getUint32(4*(n+72>>2),!0);g=z.getUint32(4*(n+76>>2),!0);var H=z.getUint32(4*(n+80>>2),!0),Z=z.getUint32(4*(n+84>>2),!0),pa=z.getUint32(4*(n+88>>2),!0),aa=z.getUint32(4*(n+52>>2),!0),lb=!!(aa&1),Vb=!!(aa&2);aa=!!(aa&64);r=r?r?A(v,r):"":void 0;u=u?u?A(v,u):"":void 0;var y=new XMLHttpRequest;y.withCredentials=!!v[n+60];y.open(p,m,!aa,r,u);aa||(y.timeout=q);y.aj=m;y.responseType="arraybuffer";H&&(m=H?A(v,H):"",y.overrideMimeType(m));if(g)for(;;){n=z.getUint32(4*
(g>>2),!0);if(!n)break;m=z.getUint32(4*(g+4>>2),!0);if(!m)break;g+=8;n=n?A(v,n):"";m=m?A(v,m):"";y.setRequestHeader(n,m)}var xa=bh.Nj(y);z.setUint32(4*(a>>2),xa,!0);g=Z&&pa?v.slice(Z,Z+pa):null;y.onload=I=>{bh.has(xa)&&(f(),200<=y.status&&300>y.status?b?.(a,y,I):c?.(a,y,I))};y.onerror=I=>{bh.has(xa)&&(f(),c?.(a,y,I))};y.ontimeout=I=>{bh.has(xa)&&c?.(a,y,I)};y.onprogress=I=>{if(bh.has(xa)){var ra=lb&&Vb&&y.response?y.response.byteLength:0,ob=0;0<ra&&lb&&Vb&&(ob=B(ra),v.set(new Uint8Array(y.response),
ob));z.setUint32(4*(a+12>>2),ob,!0);Rf(a+16,ra);Rf(a+24,I.loaded-ra);Rf(a+32,I.total);z.setInt16(2*(a+40>>1),y.readyState,!0);3<=y.readyState&&0===y.status&&0<I.loaded&&(y.status=200);z.setInt16(2*(a+42>>1),y.status,!0);y.statusText&&C(y.statusText,v,a+44,64);d?.(a,y,I);ob&&Te(ob)}};y.onreadystatechange=I=>{bh.has(xa)&&(z.setInt16(2*(a+40>>1),y.readyState,!0),2<=y.readyState&&z.setInt16(2*(a+42>>1),y.status,!0),e?.(a,y,I))};try{y.send(g)}catch(I){c?.(a,y,I)}}else c(a,0,"no url specified!")}
var na={},eh=()=>{if(!dh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ya||"./this.program"},b;for(b in na)void 0===na[b]?delete a[b]:a[b]=na[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);dh=c}return dh},dh,ua,ta=(a,b,c=[])=>{a=a.replace(/p/g,"i");return(0,h["dynCall_"+a])(b,...c)};[44].forEach(a=>{Ib[a]=new D(a);Ib[a].stack="<generic error, no stack>"});
ec=Array(4096);oa(E,"/");k("/tmp");k("/home");k("/home/web_user");(function(){k("/dev");zb(259,{read:()=>0,write:(d,e,f,g)=>g});xc("/dev/null",259);yb(1280,Bb);yb(1536,Cb);xc("/dev/tty",1280);xc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=sb(a).byteLength);return a[--b]};Dc("/dev","random",c);Dc("/dev","urandom",c);k("/dev/shm");k("/dev/shm/tmp")})();
(function(){k("/proc");var a=k("/proc/self");k("/proc/self/fd");oa({Yi(){var b=Hb(a,"fd",16895,73);b.Ri={Fj(c,d){var e=J(+d);c={parent:null,Yi:{Hj:"fake"},Ri:{Jj:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Bc;h.FS_createDataFile=Pb;h.FS_createPreloadedFile=Qb;h.FS_unlink=$b;h.FS_createLazyFile=Fc;h.FS_createDevice=Dc;
h.requestFullscreen=function(a,b){function c(){Sc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=$c,Yc&&d.requestPointerLock(),Sc=!0,Zc?("undefined"!=typeof SDL&&(f=z.getUint32(4*(SDL.screen>>2),!0),z.setInt32(4*(SDL.screen>>2),f|8388608,!0)),cd(h.canvas),bd()):cd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Zc?("undefined"!=
typeof SDL&&(f=z.getUint32(4*(SDL.screen>>2),!0),z.setInt32(4*(SDL.screen>>2),f&-8388609,!0)),cd(h.canvas),bd()):cd(d));h.onFullScreen?.(Sc);h.onFullscreen?.(Sc)}Yc=a;Zc=b;"undefined"==typeof Yc&&(Yc=!0);"undefined"==typeof Zc&&(Zc=!1);var d=h.canvas;Xc||(Xc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");
d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){cd(h.canvas,a,b);c||bd()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.hj&&a==h.canvas)return h.hj;var e;if(b){var f={antialias:!1,alpha:!1,kk:2};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Ed&&(e=Bd(a,f)))var m=qd[e].rj}else m=a.getContext("2d");if(!m)return null;c&&(h.hj=m,b&&Dd(e),Uc.forEach(n=>n()),Nb());return m};h.requestAnimationFrame=$d;h.pauseMainLoop=Xd;
h.resumeMainLoop=Yd;h.preMainLoop&&Td.push(h.preMainLoop);h.postMainLoop&&Ud.push(h.postMainLoop);for(var fh=0;32>fh;++fh)Cf.push(Array(fh));bh=new ah;
var rh={H:function(a,b,c){kb=c;try{var d=J(a);switch(b){case 0:var e=jb();if(0>e)break;for(;cc[e];)e++;return uc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=jb(),d.flags|=e,0;case 12:return e=jb(),z.setInt16(2*(e+0>>1),2,!0),0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Xi}},Yd:function(a,b){try{var c=J(a);return Ic(Tb,c.path,b)}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Xi}},gd:function(a,
b,c){try{var d=J(a);d.sj||(d.sj=Sb(d.path));a=0;for(var e=Ac(d,0,1),f=Math.floor(e/280);f<d.sj.length&&a+280<=c;){var g=d.sj[f];if("."===g){var m=d.node.id;var n=4}else if(".."===g)m=G(d.path,{parent:!0}).node.id,n=4;else{var p=Jb(d.node,g);m=p.id;n=8192===(p.mode&61440)?2:F(p.mode)?4:40960===(p.mode&61440)?10:8}x[b+a>>3]=BigInt(m);x[b+a+8>>3]=BigInt(280*(f+1));z.setInt16(2*(b+a+16>>1),280,!0);t[b+a+18]=n;C(g,v,b+a+19,256);a+=280;f+=1}Ac(d,280*f,0);return a}catch(q){if("undefined"==typeof K||"ErrnoError"!==
q.name)throw q;return-q.Xi}},Yf:function(a,b,c){kb=c;try{var d=J(a);switch(b){case 21509:return d.Ui?0:-59;case 21505:if(!d.Ui)return-59;if(d.Ui.lj.ol){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=jb();z.setInt32(4*(e>>2),25856,!0);z.setInt32(4*(e+4>>2),5,!0);z.setInt32(4*(e+8>>2),191,!0);z.setInt32(4*(e+12>>2),35387,!0);for(var f=0;32>f;f++)t[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Ui?0:-59;case 21506:case 21507:case 21508:if(!d.Ui)return-59;
if(d.Ui.lj.pl)for(e=jb(),z.getInt32(4*(e>>2),!0),z.getInt32(4*(e+4>>2),!0),z.getInt32(4*(e+8>>2),!0),z.getInt32(4*(e+12>>2),!0),a=[],f=0;32>f;f++)a.push(t[e+f+17]);return 0;case 21519:if(!d.Ui)return-59;e=jb();z.setInt32(4*(e>>2),0,!0);return 0;case 21520:return d.Ui?-28:-59;case 21531:e=jb();if(!d.Si.nl)throw new D(59);return d.Si.nl(d,b,e);case 21523:if(!d.Ui)return-59;d.Ui.lj.ql&&(f=[24,80],e=jb(),z.setInt16(2*(e>>1),f[0],!0),z.setInt16(2*(e+2>>1),f[1],!0));return 0;case 21524:return d.Ui?0:-59;
case 21515:return d.Ui?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.Xi}},rd:function(a,b){try{return a=a?A(v,a):"",Ic(zc,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.Xi}},Xc:function(a,b,c){try{return b=b?A(v,b):"",b=Hc(a,b),b=nb(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),k(b,c),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Xi}},Cd:function(a,b,c,d){try{b=b?A(v,b):"";var e=
d&256;b=Hc(a,b,d&4096);return Ic(e?zc:Tb,b,c)}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Xi}},ua:function(a,b,c,d){kb=d;try{b=b?A(v,b):"";b=Hc(a,b);var e=d?jb():0;return Ub(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Xi}},Nd:function(a,b){try{return a=a?A(v,a):"",Ic(Tb,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.Xi}},Kc:function(a,b,c){try{return b=b?A(v,b):"",b=Hc(a,b),0===c?$b(b):512===c?Zb(b):
Wa("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Xi}},Xg:()=>{Wa("")},Bb:function(a){if(bh.has(a)){var b=bh.get(a),c=bh;c.mj[a]=void 0;c.aj.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},Df:()=>1,Ab:()=>{throw Infinity;},Bg:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);z.setInt32(4*(b>>2),a.getSeconds(),!0);z.setInt32(4*(b+4>>2),a.getMinutes(),!0);z.setInt32(4*(b+8>>2),a.getHours(),!0);
z.setInt32(4*(b+12>>2),a.getDate(),!0);z.setInt32(4*(b+16>>2),a.getMonth(),!0);z.setInt32(4*(b+20>>2),a.getFullYear()-1900,!0);z.setInt32(4*(b+24>>2),a.getDay(),!0);var c=a.getFullYear();z.setInt32(4*(b+28>>2),(0!==c%4||0===c%100&&0!==c%400?Kc:Jc)[a.getMonth()]+a.getDate()-1|0,!0);z.setInt32(4*(b+36>>2),-(60*a.getTimezoneOffset()),!0);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z.setInt32(4*(b+32>>2),(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0,!0)},ff:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var m=J(d);if(0!==(b&2)&&0===(c&2)&&2!==(m.flags&2097155))throw new D(2);if(1===(m.flags&2097155))throw new D(2);if(!m.Si.Gj)throw new D(43);if(!a)throw new D(28);var n=m.Si.Gj(m,a,e,b,c);var p=n.Mk;z.setInt32(4*(f>>2),n.mj,!0);z.setUint32(4*(g>>2),p,!0);return 0}catch(q){if("undefined"==typeof K||"ErrnoError"!==q.name)throw q;return-q.Xi}},rf:function(a,b,c,d,e,f){f=
-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=J(e);if(c&2){if(32768!==(g.node.mode&61440))throw new D(43);d&2||g.Si.Yj&&g.Si.Yj(g,v.slice(a,a+b),f,b,d)}}catch(m){if("undefined"==typeof K||"ErrnoError"!==m.name)throw m;return-m.Xi}},Mg:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z.setUint32(4*(a>>2),60*Math.max(f,e),!0);z.setInt32(4*(b>>2),Number(f!=e),!0);b=g=>{var m=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(m/
60)).padStart(2,"0")}${String(m%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(C(a,v,c,17),C(b,v,d,17)):(C(a,v,d,17),C(b,v,c,17))},Uc:a=>{if(12448==a)return L=12288,1;L=12300;return 0},ed:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=z.getInt32(4*(b>>2),!0);if(12321==a)a=z.getInt32(4*(b+4>>2),!0),M.alpha=0<a;else if(12325==a)a=z.getInt32(4*(b+4>>2),!0),M.depth=0<a;else if(12326==a)a=z.getInt32(4*(b+4>>2),!0),M.stencil=0<a;else if(12337==a)a=z.getInt32(4*(b+4>>2),!0),M.antialias=0<a;else if(12338==
a)a=z.getInt32(4*(b+4>>2),!0),M.antialias=1==a;else if(12544==a)a=z.getInt32(4*(b+4>>2),!0),M.Yl=12547!=a;else if(12344==a)break;b+=8}c&&d||e?(e&&z.setInt32(4*(e>>2),1,!0),c&&0<d&&z.setUint32(4*(c>>2),62002,!0),L=12288,c=1):(L=12300,c=0)}return c},cd:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=z.getInt32(4*(d>>2),!0);if(12440==b)a=z.getInt32(4*(d+4>>2),!0);else if(12344==b)break;else return L=12292,0;d+=8}if(2>a||3<a)return L=12293,0;M.kk=a-1;M.Zl=0;jd=Bd(h.canvas,M);if(0!=jd)return L=12288,
Dd(jd),Uc.forEach(e=>e()),Dd(null),62004;L=12297;return 0},ad:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},bd:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=jd;Cd===qd[a]&&(Cd=null);"object"==typeof R&&R.zl(qd[a].rj.canvas);qd[a]&&qd[a].rj.canvas&&(qd[a].rj.canvas.Dj=void 0);qd[a]=null;L=12288;ed==b&&(ed=0);return 1},$c:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;fd==b&&(fd=0);gd==b&&(gd=0);L=12288;return 1},dd:(a,
b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return z.setInt32(4*(d>>2),M.alpha?32:24,!0),1;case 12321:return z.setInt32(4*(d>>2),M.alpha?8:0,!0),1;case 12322:return z.setInt32(4*(d>>2),8,!0),1;case 12323:return z.setInt32(4*(d>>2),8,!0),1;case 12324:return z.setInt32(4*(d>>2),8,!0),1;case 12325:return z.setInt32(4*(d>>2),M.depth?24:0,!0),1;case 12326:return z.setInt32(4*(d>>2),M.stencil?8:0,!0),1;case 12327:return z.setInt32(4*
(d>>2),12344,!0),1;case 12328:return z.setInt32(4*(d>>2),62002,!0),1;case 12329:return z.setInt32(4*(d>>2),0,!0),1;case 12330:return z.setInt32(4*(d>>2),4096,!0),1;case 12331:return z.setInt32(4*(d>>2),16777216,!0),1;case 12332:return z.setInt32(4*(d>>2),4096,!0),1;case 12333:return z.setInt32(4*(d>>2),0,!0),1;case 12334:return z.setInt32(4*(d>>2),0,!0),1;case 12335:return z.setInt32(4*(d>>2),12344,!0),1;case 12337:return z.setInt32(4*(d>>2),M.antialias?4:0,!0),1;case 12338:return z.setInt32(4*(d>>
2),M.antialias?1:0,!0),1;case 12339:return z.setInt32(4*(d>>2),4,!0),1;case 12340:return z.setInt32(4*(d>>2),12344,!0),1;case 12341:case 12342:case 12343:return z.setInt32(4*(d>>2),-1,!0),1;case 12345:case 12346:return z.setInt32(4*(d>>2),0,!0),1;case 12347:return z.setInt32(4*(d>>2),0,!0),1;case 12348:return z.setInt32(4*(d>>2),1,!0),1;case 12349:case 12350:return z.setInt32(4*(d>>2),0,!0),1;case 12351:return z.setInt32(4*(d>>2),12430,!0),1;case 12352:return z.setInt32(4*(d>>2),4,!0),1;case 12354:return z.setInt32(4*
(d>>2),0,!0),1;default:return L=12292,0}},id:a=>{L=12288;return 0!=a&&1!=a?0:62E3},Sc:()=>L,hd:(a,b,c)=>{if(62E3!=a)return L=12296,0;b&&z.setInt32(4*(b>>2),1,!0);c&&z.setInt32(4*(c>>2),4,!0);dd=!0;L=12288;return 1},_c:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;Dd(d?jd:null);ed=d;gd=b;fd=c;L=12288;return 1},Tc:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(hd[b])return hd[b];switch(b){case 12371:a=Fd("Emscripten");break;
case 12372:a=Fd("1.4 Emscripten EGL");break;case 12373:a=Fd("");break;case 12429:a=Fd("OpenGL_ES");break;default:return L=12300,0}return hd[b]=a},Zc:()=>{if(dd)if(h.hj)if(h.hj.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Yc:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?Vd(0,0):Vd(1,b);L=12288;return 1},fd:a=>{if(62E3!=a)return L=12296,0;gd=fd=ed=0;dd=!1;L=12288;return 1},Vc:()=>{L=12288;return 1},Wc:()=>{L=12288;return 1},w:(a,b,c)=>{b=ce(b,c);return eb[a](...b)},e:(a,
b,c)=>{b=ce(b,c);return eb[a](...b)},Qb:(a,b,c)=>{b=ce(b,c);return eb[a](...b)},ja:()=>{Xd();Hd=null},I:()=>Date.now(),Mc:()=>{if(!R.fullscreenEnabled())return-1;fe(ue);var a=le[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Qc:()=>{fe(ve);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Cf:(a,b)=>{if(!Fa)if(0===ze){ze=1;var c=a+20;Pe(c);X=c;Re(c);
c=T();z.setUint32(4*(a+8>>2),c,!0);De=b}else ze=0,Se(),X=null},r:()=>devicePixelRatio,j:(a,b,c)=>{a=S(a);if(!a)return-4;a=te(a);z.setFloat64(8*(b>>3),a.width,!0);z.setFloat64(8*(c>>3),a.height,!0);return 0},U:(a,b)=>{if(0>a||a>=R.Sj.length)return-5;if(!R.Sj[a])return-7;Ue(b,R.Sj[a]);return 0},We:()=>2147483648,F:()=>performance.now(),Ic:()=>R.Sj.length,Rc:(a,b)=>{z.setInt32(4*(a>>2),screen.width,!0);z.setInt32(4*(b>>2),screen.height,!0)},fb:Ve,eb:We,cf:(a,b)=>{N.beginQuery(a,Q[b])},wb:(a,b)=>{N.oj.beginQueryEXT(a,
Q[b])},Ke:a=>N.beginTransformFeedback(a),db:Xe,cb:Ye,He:(a,b,c)=>{N.bindBufferBase(a,b,ld[c])},Ie:(a,b,c,d,e)=>{N.bindBufferRange(a,b,ld[c],d,e)},bb:Ze,ab:(a,b)=>{N.bindRenderbuffer(a,nd[b])},Md:(a,b)=>{N.bindSampler(a,rd[b])},$a:$e,Ed:(a,b)=>{N.bindTransformFeedback(a,sd[b])},Pe:af,ob:af,Za:(a,b,c,d)=>N.blendColor(a,b,c,d),Ya:a=>N.blendEquation(a),Xa:bf,Wa:(a,b)=>N.blendFunc(a,b),Va:cf,Se:df,Ua:ef,Ta:ff,Sa:a=>N.checkFramebufferStatus(a),Ra:gf,je:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),ke:(a,b,c)=>{N.clearBufferfv(a,
b,w,c>>2)},me:(a,b,c)=>{N.clearBufferiv(a,b,Ja,c>>2)},le:(a,b,c)=>{N.clearBufferuiv(a,b,Ka,c>>2)},Qa:hf,Pa:jf,Oa:a=>N.clearStencil(a),Wd:(a,b,c)=>{c=Number(c);return N.clientWaitSync(td[a],b,c)},vf:(a,b)=>{N.Vl.clipControlEXT(a,b)},Na:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Ma:kf,La:lf,jf:(a,b,c,d,e,f,g,m,n)=>{N.ij?N.compressedTexImage3D(a,b,c,d,e,f,g,m,n):N.compressedTexImage3D(a,b,c,d,e,f,g,v,n,m)},Ka:mf,hf:(a,b,c,d,e,f,g,m,n,p,q)=>{N.ij?N.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,p,q):N.compressedTexSubImage3D(a,
b,c,d,e,f,g,m,n,v,q,p)},he:(a,b,c,d,e)=>N.copyBufferSubData(a,b,c,d,e),Ja:(a,b,c,d,e,f,g,m)=>N.copyTexImage2D(a,b,c,d,e,f,g,m),Ia:(a,b,c,d,e,f,g,m)=>N.copyTexSubImage2D(a,b,c,d,e,f,g,m),kf:(a,b,c,d,e,f,g,m,n)=>N.copyTexSubImage3D(a,b,c,d,e,f,g,m,n),Ha:nf,Ga:of,Fa:pf,Ea:qf,Da:rf,Ca:sf,ef:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Q[d];e&&(N.deleteQuery(e),Q[d]=null)}},zb:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Q[d];e&&(N.oj.deleteQueryEXT(e),Q[d]=null)}},
Ba:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=nd[d];e&&(N.deleteRenderbuffer(e),e.name=0,nd[d]=null)}},Pd:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=rd[d];e&&(N.deleteSampler(e),e.name=0,rd[d]=null)}},Aa:tf,Xd:a=>{if(a){var b=td[a];b&&(N.deleteSync(b),b.name=0,td[a]=null)}},za:uf,Dd:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=sd[d];e&&(N.deleteTransformFeedback(e),e.name=0,sd[d]=null)}},Oe:vf,nb:vf,ya:wf,xa:xf,wa:(a,b)=>N.depthRange(a,
b),Ah:(a,b)=>{N.detachShader(O[a],P[b])},zh:yf,yh:zf,xh:Af,ae:Bf,ib:Bf,ld:Bf,sf:Bf,md:Bf,_e:Df,pf:Df,kb:Df,wh:Ef,$d:Ff,hb:Ff,jd:Ff,kd:Ff,qf:Ff,nf:(a,b,c,d,e,f)=>{N.drawElements(a,d,e,f)},vh:Gf,uh:Hf,bf:a=>N.endQuery(a),vb:a=>{N.oj.endQueryEXT(a)},Je:()=>N.endTransformFeedback(),_d:(a,b)=>(a=N.fenceSync(a,b))?(b=yd(td),a.name=b,td[b]=a,b):0,th:()=>N.finish(),sh:()=>N.flush(),rh:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,nd[d])},qh:If,Qe:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,od[c],d,e)},ph:Jf,
oh:Kf,mh:Lf,gf:(a,b)=>{zd(a,b,"createQuery",Q)},Hb:(a,b)=>{for(var c=0;c<a;c++){var d=N.oj.createQueryEXT();if(!d){for(;c<a;)d=4*(b+4*c++>>2),z.setInt32(d,0,!0);break}var e=yd(Q);d.name=e;Q[e]=d;z.setInt32(4*(b+4*c>>2),e,!0)}},lh:(a,b)=>{zd(a,b,"createRenderbuffer",nd)},Qd:(a,b)=>{zd(a,b,"createSampler",rd)},kh:Mf,Bd:(a,b)=>{zd(a,b,"createTransformFeedback",sd)},Ne:Nf,mb:Nf,nh:Of,jh:(a,b,c,d,e,f,g)=>{Pf("getActiveAttrib",a,b,c,d,e,f,g)},ih:Qf,ce:(a,b,c,d,e)=>{a=O[a];if(a=N.getActiveUniformBlockName(a,
b))e&&0<c?(c=C(a,v,e,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0)},de:(a,b,c,d)=>{a=O[a];if(35393==c)z.setInt32(4*(d>>2),N.getActiveUniformBlockName(a,b).length+1,!0);else if(a=N.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)z.setInt32(4*(d+4*c>>2),a[c],!0);else z.setInt32(4*(d>>2),a,!0)},fe:(a,b,c,d,e)=>{a=O[a];for(var f=[],g=0;g<b;g++)f.push(z.getInt32(4*(c+4*g>>2),!0));if(a=N.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)z.setInt32(4*(e+
4*g>>2),a[g],!0)},hh:(a,b,c,d)=>{a=N.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);z.setInt32(4*(c>>2),e,!0);for(b=0;b<e;++b)z.setInt32(4*(d+4*b>>2),P.indexOf(a[b]),!0)},fh:(a,b)=>N.getAttribLocation(O[a],b?A(v,b):""),eh:(a,b)=>Uf(a,b,4),Rd:(a,b,c)=>{Rf(c,N.getBufferParameter(a,b))},dh:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getBufferParameter(a,b),!0)},ch:()=>N.getError(),bh:(a,b)=>Uf(a,b,2),we:(a,b)=>N.getFragDataLocation(O[a],b?A(v,b):""),ah:(a,b,c,d)=>{a=N.getFramebufferAttachmentParameter(a,
b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z.setInt32(4*(d>>2),a,!0)},Sd:(a,b,c)=>Vf(a,b,c,1),Ud:(a,b)=>{Uf(a,b,1)},Le:(a,b,c)=>Vf(a,b,c,0),$g:Wf,pd:(a,b,c,d,e)=>{a=N.getInternalformatParameter(a,b,c);if(null!==a)for(b=0;b<a.length&&b<d;++b)z.setInt32(4*(e+4*b>>2),a[b],!0)},xd:()=>{},Zg:Xf,_g:Yf,qb:Zf,sb:$f,pb:Zf,$e:(a,b,c)=>{a=N.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)},rb:$f,af:(a,b,c)=>{z.setInt32(4*(c>>2),N.getQuery(a,
b),!0)},tb:(a,b,c)=>{c&&(a=N.oj.getQueryEXT(a,b),z.setInt32(4*(c>>2),a,!0))},Yg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getRenderbufferParameter(a,b),!0)},Gd:(a,b,c)=>{z.setFloat32(4*(c>>2),N.getSamplerParameter(rd[a],b),!0)},Hd:(a,b,c)=>{z.setInt32(4*(c>>2),N.getSamplerParameter(rd[a],b),!0)},Vg:ag,Ug:(a,b,c,d)=>{a=N.getShaderPrecisionFormat(a,b);z.setInt32(4*(c>>2),a.rangeMin,!0);z.setInt32(4*(c+4>>2),a.rangeMax,!0);z.setInt32(4*(d>>2),a.precision,!0)},Tg:(a,b,c,d)=>{if(a=N.getShaderSource(P[a]))b=0<
b&&d?C(a,v,d,b):0,c&&z.setInt32(4*(c>>2),b,!0)},Wg:bg,Sg:cg,ie:dg,Td:(a,b,c,d,e)=>{a=N.getSyncParameter(td[a],b);null!==a&&(z.setInt32(4*(e>>2),a,!0),d&&z.setInt32(4*(d>>2),1,!0))},Rg:(a,b,c)=>{c&&z.setFloat32(4*(c>>2),N.getTexParameter(a,b),!0)},Qg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getTexParameter(a,b),!0)},Fe:(a,b,c,d,e,f,g)=>{a=O[a];if(a=N.getTransformFeedbackVarying(a,b))g&&0<c?(c=C(a.name,v,g,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0),e&&z.setInt32(4*(e>>2),a.size,!0),f&&
z.setInt32(4*(f>>2),a.type,!0)},ee:(a,b)=>N.getUniformBlockIndex(O[a],b?A(v,b):""),ge:(a,b,c,d)=>{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Gc(z.getInt32(4*(c+4*f>>2),!0)));if(a=N.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)z.setInt32(4*(d+4*f>>2),a[f],!0)},Ng:gg,Pg:ig,Og:jg,xe:(a,b,c)=>hg(a,b,c,0),De:lg,Ce:lg,Jg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getVertexAttribOffset(a,b),!0)},Lg:(a,b,c)=>{kg(a,b,c,2)},Kg:(a,b,c)=>{kg(a,b,c,5)},Ig:(a,b)=>N.hint(a,b),ud:(a,b,c)=>{for(var d=Cf[b],e=0;e<b;e++)d[e]=
z.getInt32(4*(c+4*e>>2),!0);N.invalidateFramebuffer(a,d)},td:(a,b,c,d,e,f,g)=>{for(var m=Cf[b],n=0;n<b;n++)m[n]=z.getInt32(4*(c+4*n>>2),!0);N.invalidateSubFramebuffer(a,m,d,e,f,g)},Hg:a=>(a=ld[a])?N.isBuffer(a):0,Gg:a=>N.isEnabled(a),Fg:a=>(a=md[a])?N.isFramebuffer(a):0,Eg:a=>(a=O[a])?N.isProgram(a):0,df:a=>(a=Q[a])?N.isQuery(a):0,xb:a=>(a=Q[a])?N.oj.isQueryEXT(a):0,Dg:a=>(a=nd[a])?N.isRenderbuffer(a):0,Od:a=>(a=rd[a])?N.isSampler(a):0,Cg:a=>(a=P[a])?N.isShader(a):0,Zd:a=>N.isSync(td[a]),Ag:a=>(a=
od[a])?N.isTexture(a):0,Ad:a=>N.isTransformFeedback(sd[a]),Me:mg,lb:mg,zg:a=>N.lineWidth(a),yg:ng,zd:()=>N.pauseTransformFeedback(),xg:og,uf:(a,b)=>{N.cm.polygonModeWEBGL(a,b)},wg:(a,b)=>N.polygonOffset(a,b),wf:(a,b,c)=>{N.Wl.polygonOffsetClampEXT(a,b,c)},wd:()=>{},vd:()=>{},ub:(a,b)=>{N.oj.queryCounterEXT(Q[a],b)},of:pg,vg:sg,ug:()=>{},tg:(a,b,c,d)=>N.renderbufferStorage(a,b,c,d),Re:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),yd:()=>N.resumeTransformFeedback(),sg:(a,b)=>{N.sampleCoverage(a,
!!b)},Jd:(a,b,c)=>{N.samplerParameterf(rd[a],b,c)},Id:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);N.samplerParameterf(rd[a],b,c)},Ld:(a,b,c)=>{N.samplerParameteri(rd[a],b,c)},Kd:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);N.samplerParameteri(rd[a],b,c)},rg:tg,qg:()=>{},pg:ug,og:(a,b,c)=>N.stencilFunc(a,b,c),ng:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),mg:a=>N.stencilMask(a),lg:(a,b)=>N.stencilMaskSeparate(a,b),kg:(a,b,c)=>N.stencilOp(a,b,c),jg:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),ig:vg,mf:(a,b,c,d,e,f,g,m,n,
p)=>{if(N.ij)N.texImage3D(a,b,c,d,e,f,g,m,n,p);else if(p){var q=qg(n);N.texImage3D(a,b,c,d,e,f,g,m,n,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,c,d,e,f,g,m,n,null)},hg:(a,b,c)=>N.texParameterf(a,b,c),gg:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);N.texParameterf(a,b,c)},fg:wg,eg:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);N.texParameteri(a,b,c)},sd:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),qd:(a,b,c,d,e,f)=>N.texStorage3D(a,b,c,d,e,f),dg:xg,lf:(a,b,c,d,e,f,g,m,n,p,q)=>{if(N.ij)N.texSubImage3D(a,
b,c,d,e,f,g,m,n,p,q);else if(q){var r=qg(p);N.texSubImage3D(a,b,c,d,e,f,g,m,n,p,r,q>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,f,g,m,n,p,null)},Ge:(a,b,c,d)=>{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Gc(z.getInt32(4*(c+4*f>>2),!0)));N.transformFeedbackVaryings(a,e,d)},cg:(a,b)=>{N.uniform1f(Y(a),b)},bg:yg,ag:(a,b)=>{N.uniform1i(Y(a),b)},$f:zg,ve:(a,b)=>{N.uniform1ui(Y(a),b)},qe:(a,b,c)=>{b&&N.uniform1uiv(Y(a),Ka,c>>2,b)},_f:(a,b,c)=>{N.uniform2f(Y(a),b,c)},Zf:Ag,Xf:(a,b,c)=>
{N.uniform2i(Y(a),b,c)},Wf:Bg,ue:(a,b,c)=>{N.uniform2ui(Y(a),b,c)},pe:(a,b,c)=>{b&&N.uniform2uiv(Y(a),Ka,c>>2,2*b)},Vf:(a,b,c,d)=>{N.uniform3f(Y(a),b,c,d)},Uf:Cg,Tf:(a,b,c,d)=>{N.uniform3i(Y(a),b,c,d)},Sf:Dg,te:(a,b,c,d)=>{N.uniform3ui(Y(a),b,c,d)},oe:(a,b,c)=>{b&&N.uniform3uiv(Y(a),Ka,c>>2,3*b)},Rf:(a,b,c,d,e)=>{N.uniform4f(Y(a),b,c,d,e)},Qf:Eg,Pf:(a,b,c,d,e)=>{N.uniform4i(Y(a),b,c,d,e)},Of:Fg,se:(a,b,c,d,e)=>{N.uniform4ui(Y(a),b,c,d,e)},ne:(a,b,c)=>{b&&N.uniform4uiv(Y(a),Ka,c>>2,4*b)},be:(a,b,c)=>
{a=O[a];N.uniformBlockBinding(a,b,c)},Nf:(a,b,c,d)=>{b&&N.uniformMatrix2fv(Y(a),!!c,w,d>>2,4*b)},Ze:(a,b,c,d)=>{b&&N.uniformMatrix2x3fv(Y(a),!!c,w,d>>2,6*b)},Xe:(a,b,c,d)=>{b&&N.uniformMatrix2x4fv(Y(a),!!c,w,d>>2,8*b)},Mf:Gg,Ye:(a,b,c,d)=>{b&&N.uniformMatrix3x2fv(Y(a),!!c,w,d>>2,6*b)},Ue:(a,b,c,d)=>{b&&N.uniformMatrix3x4fv(Y(a),!!c,w,d>>2,12*b)},Lf:Hg,Ve:(a,b,c,d)=>{b&&N.uniformMatrix4x2fv(Y(a),!!c,w,d>>2,8*b)},Te:(a,b,c,d)=>{b&&N.uniformMatrix4x3fv(Y(a),!!c,w,d>>2,12*b)},Kf:Ig,Jf:a=>{N.validateProgram(O[a])},
If:(a,b)=>N.vertexAttrib1f(a,b),Hf:(a,b)=>{N.vertexAttrib1f(a,z.getFloat32(4*(b>>2),!0))},Gf:(a,b,c)=>N.vertexAttrib2f(a,b,c),Ff:(a,b)=>{N.vertexAttrib2f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0))},Ef:(a,b,c,d)=>N.vertexAttrib3f(a,b,c,d),Bf:(a,b)=>{N.vertexAttrib3f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0))},Af:(a,b,c,d,e)=>N.vertexAttrib4f(a,b,c,d,e),zf:(a,b)=>{N.vertexAttrib4f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*
(b+8>>2),!0),z.getFloat32(4*(b+12>>2),!0))},Fd:Jg,gb:Jg,nd:Jg,tf:Jg,od:Jg,Be:(a,b,c,d,e)=>N.vertexAttribI4i(a,b,c,d,e),ze:(a,b)=>{N.vertexAttribI4i(a,z.getInt32(4*(b>>2),!0),z.getInt32(4*(b+4>>2),!0),z.getInt32(4*(b+8>>2),!0),z.getInt32(4*(b+12>>2),!0))},Ae:(a,b,c,d,e)=>N.vertexAttribI4ui(a,b,c,d,e),ye:(a,b)=>{N.vertexAttribI4ui(a,z.getUint32(4*(b>>2),!0),z.getUint32(4*(b+4>>2),!0),z.getUint32(4*(b+8>>2),!0),z.getUint32(4*(b+12>>2),!0))},Ee:Kg,yf:Lg,xf:Mg,Vd:(a,b,c)=>{c=Number(c);N.waitSync(td[a],
b,c)},C:()=>1,Db:()=>!0,Nc:(a,b,c)=>{b={qk:z.getInt32(4*(c>>2),!0),ck:z.getInt32(4*(c+4>>2),!0),el:z.getInt32(4*(c+8>>2),!0),bl:b,Pj:z.getInt32(4*(c+12>>2),!0),zk:z.getInt32(4*(c+16>>2),!0)};return Ng(a,b)},sa:(a,b)=>{a=S(a);return a?a.requestPointerLock?ge()?ve(a):b?(ee(ve,2,[a]),1):-2:-1:-4},Ch:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-Ea.buffer.byteLength+65535)/
65536;try{Ea.grow(d);La();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},_:Og,Y:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Pg(a,b),ka:(a,b,c,d)=>Qg(a,b,c,d,12,"blur"),q:pe,E:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},la:(a,b,c,d)=>Qg(a,b,c,d,13,"focus"),aa:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=S(a);if(!a)return-4;Rg(a,b,c,d,"webkitfullscreenchange");return Rg(a,b,c,d,"fullscreenchange")},T:(a,b,c)=>Og()?-1:Sg(a,b,c,26,"gamepadconnected"),
Q:(a,b,c)=>Og()?-1:Sg(a,b,c,27,"gamepaddisconnected"),da:(a,b,c,d)=>Tg(a,b,c,d,2,"keydown"),ba:(a,b,c,d)=>Tg(a,b,c,d,1,"keypress"),ca:(a,b,c,d)=>Tg(a,b,c,d,3,"keyup"),L:(a,b,c)=>{Wd(()=>dynCall_v(a),b,c)},qa:(a,b,c,d)=>Vg(a,b,c,d,5,"mousedown"),oa:(a,b,c,d)=>Vg(a,b,c,d,33,"mouseenter"),na:(a,b,c,d)=>Vg(a,b,c,d,34,"mouseleave"),ra:(a,b,c,d)=>Vg(a,b,c,d,8,"mousemove"),pa:(a,b,c,d)=>Vg(a,b,c,d,6,"mouseup"),ea:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.aj||
document.body.Rk||document.body.Qk))return-1;a=S(a);if(!a)return-4;Wg(a,b,c,d,"mozpointerlockchange");Wg(a,b,c,d,"webkitpointerlockchange");Wg(a,b,c,d,"mspointerlockchange");return Wg(a,b,c,d,"pointerlockchange")},$:(a,b,c,d)=>Xg(a,b,c,d),fa:(a,b,c,d)=>Yg(a,b,c,d,25,"touchcancel"),ha:(a,b,c,d)=>Yg(a,b,c,d,23,"touchend"),ga:(a,b,c,d)=>Yg(a,b,c,d,24,"touchmove"),ia:(a,b,c,d)=>Yg(a,b,c,d,22,"touchstart"),Z:(a,b,c)=>Zg(a,b,c),ma:(a,b,c,d)=>(a=S(a))?"undefined"!=typeof a.onwheel?$g(a,b,c,d):-1:-4,Oc:a=>
document.title=a?A(v,a):"",t:a=>Qe(b=>Rc(b,a)),Cb:function(a,b,c,d,e){function f(u){r?u():Qc(u)}var g=a+108,m=z.getUint32(4*(g+36>>2),!0),n=z.getUint32(4*(g+40>>2),!0),p=z.getUint32(4*(g+44>>2),!0),q=z.getUint32(4*(g+48>>2),!0),r=!!(z.getUint32(4*(g+52>>2),!0)&64);ch(a,u=>{f(()=>{m?dynCall_vi(m,u):b?.(u)})},u=>{f(()=>{n?dynCall_vi(n,u):c?.(u)})},u=>{f(()=>{p?dynCall_vi(p,u):d?.(u)})},u=>{f(()=>{q?dynCall_vi(q,u):e?.(u)})});return a},_a:(a,b)=>{var c=0;eh().forEach((d,e)=>{var f=b+c;z.setUint32(4*
(a+4*e>>2),f,!0);e=f;for(f=0;f<d.length;++f)t[e++]=d.charCodeAt(f);t[e]=0;c+=d.length+1});return 0},jb:(a,b)=>{var c=eh();z.setUint32(4*(a>>2),c.length,!0);var d=0;c.forEach(e=>d+=e.length+1);z.setUint32(4*(b>>2),d,!0);return 0},m:Oc,s:function(a){try{var b=J(a);Xb(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.Xi}},Bh:function(a,b){try{var c=J(a);t[b]=c.Ui?2:F(c.mode)?3:40960===(c.mode&61440)?7:4;z.setInt16(2*(b+2>>1),0,!0);x[b+8>>3]=BigInt(0);x[b+16>>3]=BigInt(0);
return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return d.Xi}},ta:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var p=e,q=f,r=t;if(0>n||0>q)throw new D(28);if(null===p.fd)throw new D(8);if(1===(p.flags&2097155))throw new D(8);if(F(p.node.mode))throw new D(31);if(!p.Si.read)throw new D(28);var u="undefined"!=typeof q;if(!u)q=p.position;else if(!p.seekable)throw new D(70);var H=p.Si.read(p,r,
m,n,q);u||(p.position+=H);var Z=H;if(0>Z){var pa=-1;break a}b+=Z;if(Z<n)break;"undefined"!=typeof f&&(f+=Z)}pa=b}z.setUint32(4*(d>>2),pa,!0);return 0}catch(aa){if("undefined"==typeof K||"ErrnoError"!==aa.name)throw aa;return aa.Xi}},gh:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=J(a);Ac(e,b,c);x[d>>3]=BigInt(e.position);e.sj&&0===b&&0===c&&(e.sj=null);return 0}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return f.Xi}},
Pc:function(a){try{var b=J(a);return Qe(c=>{var d=b.node.Yi;d.type.Lj?d.type.Lj(d,!1,e=>{e?c(29):c(0)}):c(0)})}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.Xi}},va:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var m=z.getUint32(4*(a>>2),!0),n=z.getUint32(4*(a+4>>2),!0);a+=8;var p=Wb(e,t,m,n,f);if(0>p){var q=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}q=b}z.setUint32(4*(d>>2),q,!0);return 0}catch(r){if("undefined"==typeof K||"ErrnoError"!==
r.name)throw r;return r.Xi}},Mb:Ve,qc:We,pc:Xe,D:Ye,z:Ze,N:$e,Dc:af,tc:bf,sc:cf,vc:df,A:ef,P:ff,wc:gf,Vb:hf,Ub:jf,Rb:kf,Ec:lf,Hc:mf,rc:nf,Tb:of,Cc:pf,V:qf,yc:rf,R:sf,B:tf,W:uf,$b:vf,Bc:wf,Nb:xf,p:yf,Wb:zf,Kb:Af,Lb:Bf,xc:Df,Ib:Ef,Jb:Ff,o:Gf,_b:Hf,zc:If,Gb:Jf,X:Kf,Ac:Lf,Jc:Mf,ac:Nf,Fc:Of,cc:Qf,k:Wf,dc:Xf,y:Yf,Pb:ag,O:bg,i:cg,G:dg,bc:gg,l:ig,x:jg,oc:ng,M:og,S:pg,Ob:sg,Lc:tg,Sb:ug,d:vg,g:wg,Gc:xg,nc:yg,jc:zg,mc:Ag,ic:Bg,lc:Cg,hc:Dg,kc:Eg,gc:Fg,fc:Gg,ec:Hg,uc:Ig,Xb:Jg,Yb:Kg,Zb:Lg,Fb:Mg,J:gh,f:hh,v:ih,
u:jh,K:kh,h:lh,a:mh,b:nh,c:oh,n:ph,yb:qh,Eb:function(a,b){h.setStatus(a>=b?"":"Prefetching resources\u2026 ("+a+"/"+b+")",!0)},re:function(){try{return!!navigator.platform.match(/mac/i)}catch(a){return!1}}},W=function(){function a(c){W=c.exports;W=xe();Ea=W.Dh;La();ua=W.Ph;Na.unshift(W.Eh);Va("wasm-instantiate");return W}var b={a:rh};Ua("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return Ca(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ya??=Xa("taisei.wasm")?
"taisei.wasm":h.locateFile?h.locateFile("taisei.wasm",za):za+"taisei.wasm";bb(b,function(c){a(c.instance)});return{}}();h._vfs_sync_callback=(a,b,c)=>(h._vfs_sync_callback=W.Fh)(a,b,c);var sh=h._main=(a,b)=>(sh=h._main=W.Gh)(a,b),Db=(a,b)=>(Db=W.Hh)(a,b),B=a=>(B=W.Ih)(a),Te=a=>(Te=W.Jh)(a),th=(a,b)=>(th=W.Kh)(a,b),Ee=(a,b)=>(Ee=W.Lh)(a,b),U=a=>(U=W.Mh)(a),me=a=>(me=W.Nh)(a),T=()=>(T=W.Oh)(),V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=W.Qh)(a,b,c,d);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=W.Rh)(a,b,c,d,e,f,g);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=W.Sh)(a,b,c),uh=h.dynCall_ii=(a,b)=>(uh=h.dynCall_ii=W.Th)(a,b);h.dynCall_jiji=(a,b,c,d)=>(h.dynCall_jiji=W.Uh)(a,b,c,d);var dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=W.Vh)(a,b),vh=h.dynCall_viii=(a,b,c,d)=>(vh=h.dynCall_viii=W.Wh)(a,b,c,d),wh=h.dynCall_viiii=(a,b,c,d,e)=>(wh=h.dynCall_viiii=W.Xh)(a,b,c,d,e);
h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=W.Yh)(a,b,c,d,e,f);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=W.Zh)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=W._h)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiiiiiii=W.$h)(a,b,c,d,e,f,g,m,n);var xh=h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(xh=h.dynCall_viiiiiiiii=W.ai)(a,b,c,d,e,f,g,m,n,p),yh=h.dynCall_i=a=>(yh=h.dynCall_i=W.bi)(a);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=W.ci)(a,b,c);
var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=W.di)(a);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_viiiiiii=W.ei)(a,b,c,d,e,f,g,m);var dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=W.fi)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=W.gi)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=W.hi)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=W.ii)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=W.ji)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=W.ki)(a,b,c,d,e);
h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=W.li)(a,b,c,d,e,f);var zh=h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(zh=h.dynCall_viiiiii=W.mi)(a,b,c,d,e,f,g);h.dynCall_vfff=(a,b,c,d)=>(h.dynCall_vfff=W.ni)(a,b,c,d);h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,q)=>(h.dynCall_viiiiiiiiii=W.oi)(a,b,c,d,e,f,g,m,n,p,q);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,q,r)=>(h.dynCall_viiiiiiiiiii=W.pi)(a,b,c,d,e,f,g,m,n,p,q,r);h.dynCall_viifi=(a,b,c,d,e)=>(h.dynCall_viifi=W.qi)(a,b,c,d,e);
var Ah=h.dynCall_iiiii=(a,b,c,d,e)=>(Ah=h.dynCall_iiiii=W.ri)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=W.si)(a,b);h.dynCall_iiiiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,q,r)=>(h.dynCall_iiiiiiiiiiii=W.ti)(a,b,c,d,e,f,g,m,n,p,q,r);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=W.ui)(a,b,c,d,e,f);h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiiii=W.vi)(a,b,c,d,e,f,g);h.dynCall_vd=(a,b)=>(h.dynCall_vd=W.wi)(a,b);h.dynCall_iiji=(a,b,c,d)=>(h.dynCall_iiji=W.xi)(a,b,c,d);
h.dynCall_viidi=(a,b,c,d,e)=>(h.dynCall_viidi=W.yi)(a,b,c,d,e);h.dynCall_ff=(a,b)=>(h.dynCall_ff=W.zi)(a,b);h.dynCall_iiif=(a,b,c,d)=>(h.dynCall_iiif=W.Ai)(a,b,c,d);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiiiiii=W.Bi)(a,b,c,d,e,f,g,m,n);h.dynCall_iiiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,q)=>(h.dynCall_iiiiiiiiiii=W.Ci)(a,b,c,d,e,f,g,m,n,p,q);h.dynCall_viiif=(a,b,c,d,e)=>(h.dynCall_viiif=W.Di)(a,b,c,d,e);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_iiiiiiii=W.Ei)(a,b,c,d,e,f,g,m);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_iiiiiiiiii=W.Fi)(a,b,c,d,e,f,g,m,n,p);h.dynCall_iiidd=(a,b,c,d,e)=>(h.dynCall_iiidd=W.Gi)(a,b,c,d,e);h.dynCall_id=(a,b)=>(h.dynCall_id=W.Hi)(a,b);h.dynCall_dd=(a,b)=>(h.dynCall_dd=W.Ii)(a,b);h.dynCall_d=a=>(h.dynCall_d=W.Ji)(a);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=W.Ki)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=W.Li)(a,b);h.dynCall_dii=(a,b,c)=>(h.dynCall_dii=W.Mi)(a,b,c);
var Re=a=>(Re=W.Ni)(a),Ae=()=>(Ae=W.Oi)(),Fe=a=>(Fe=W.Pi)(a),Se=()=>(Se=W.Qi)();function ih(a,b,c){var d=T();try{return dynCall_iii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;th(1,0)}}function kh(a,b,c,d,e){var f=T();try{return Ah(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;th(1,0)}}function jh(a,b,c,d){var e=T();try{return V(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;th(1,0)}}function gh(a){var b=T();try{return yh(a)}catch(c){U(b);if(c!==c+0)throw c;th(1,0)}}
function nh(a,b,c,d){var e=T();try{vh(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;th(1,0)}}function hh(a,b){var c=T();try{return uh(a,b)}catch(d){U(c);if(d!==d+0)throw d;th(1,0)}}function ph(a,b,c,d,e,f,g){var m=T();try{zh(a,b,c,d,e,f,g)}catch(n){U(m);if(n!==n+0)throw n;th(1,0)}}function mh(a,b,c){var d=T();try{dynCall_vii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;th(1,0)}}function lh(a,b){var c=T();try{dynCall_vi(a,b)}catch(d){U(c);if(d!==d+0)throw d;th(1,0)}}
function oh(a,b,c,d,e){var f=T();try{wh(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;th(1,0)}}function qh(a,b,c,d,e,f,g,m,n,p){var q=T();try{xh(a,b,c,d,e,f,g,m,n,p)}catch(r){U(q);if(r!==r+0)throw r;th(1,0)}}h.addRunDependency=Ua;h.removeRunDependency=Va;
h.ccall=(a,b,c,d,e)=>{function f(r){--Mc;0!==n&&U(n);return"string"===b?r?A(v,r):"":"boolean"===b?!!r:r}var g={string:r=>{var u=0;null!==r&&void 0!==r&&0!==r&&(u=ne(r));return u},array:r=>{var u=me(r.length);t.set(r,u);return u}};a=h["_"+a];var m=[],n=0;if(d)for(var p=0;p<d.length;p++){var q=g[c[p]];q?(0===n&&(n=T()),m[p]=q(d[p])):m[p]=d[p]}c=X;d=a(...m);e=e?.async;Mc+=1;if(X!=c)return Ne().then(f);d=f(d);return e?Promise.resolve(d):d};h.FS_createPreloadedFile=Qb;h.FS_unlink=a=>$b(a);
h.FS_createPath=Bc;h.FS_createDevice=Dc;h.FS_createDataFile=(a,b,c,d,e,f)=>{Pb(a,b,c,d,e,f)};h.FS_createLazyFile=Fc;var Bh;Ta=function Ch(){Bh||Dh();Bh||(Ta=Ch)};function Eh(a=[]){var b=sh;a.unshift(ya);var c=a.length,d=me(4*(c+1)),e=d;a.forEach(g=>{g=ne(g);z.setUint32(4*(e>>2),g,!0);e+=4});z.setUint32(4*(e>>2),0,!0);try{var f=b(c,d);Oc(f,!0)}catch(g){Lc(g)}}
function Dh(){var a=wa;function b(){if(!Bh&&(Bh=!0,h.calledRun=!0,!Fa)){if(!h.noFSInit&&!fc){var c,d;fc=!0;e??=h.stdin;c??=h.stdout;d??=h.stderr;e?Dc("/dev","stdin",e):yc("/dev/tty","/dev/stdin");c?Dc("/dev","stdout",null,c):yc("/dev/tty","/dev/stdout");d?Dc("/dev","stderr",null,d):yc("/dev/tty1","/dev/stderr");Ub("/dev/stdin",0);Ub("/dev/stdout",1);Ub("/dev/stderr",1)}gc=!1;hb(Na);hb(Oa);h.onRuntimeInitialized?.();Fh&&Eh(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Pa.unshift(e)}hb(Pa)}}if(!(0<Ra)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Qa();hb(Ma);0<Ra||(h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Fh=!0;h.noInitialRun&&(Fh=!1);Dh();
